<?php
require_once "../config/settings.php";

function xssafe($data, $encoding = 'UTF-8')
{
    if (is_array($data)) {
        return $data;
    }
    return htmlspecialchars($data, ENT_QUOTES | ENT_HTML401, $encoding);
}


//putenv("TZ=GMT");
date_default_timezone_set('UTC');

$uri = 'image_loader.phtml';

$site = isset($_GET["site"]) ? xssafe($_GET["site"]) : "kdsm";
$var = isset($_GET["var"]) ? xssafe($_GET["var"]) : "tf";
$nam = isset($_GET["nam"]) ? xssafe($_GET["nam"]) : "1";
$nam4km = isset($_GET["nam4km"]) ? xssafe($_GET["nam4km"]) : "1";
$namm = isset($_GET["namm"]) ? xssafe($_GET["namm"]) : "1";
$gfs = isset($_GET["gfs"]) ? xssafe($_GET["gfs"]) : "1";
$gfsm = isset($_GET["gfsm"]) ? xssafe($_GET["gfsm"]) : "1";
$rap = isset($_GET["rap"]) ? xssafe($_GET["rap"]) : "1";
$nam_mos = isset($_GET["nam_mos"]) ? xssafe($_GET["nam_mos"]) : "1";
$namm_mos = isset($_GET["namm_mos"]) ? xssafe($_GET["namm_mos"]) : "1";
$gfs_mos = isset($_GET["gfs_mos"]) ? xssafe($_GET["gfs_mos"]) : "1";
$gfsm_mos = isset($_GET["gfsm_mos"]) ? xssafe($_GET["gfsm_mos"]) : "1";
$con = isset($_GET["con"]) ? xssafe($_GET["con"]) : "1";
$obs = isset($_GET["obs"]) ? xssafe($_GET["obs"]) : "1";
$nws = isset($_GET["nws"]) ? xssafe($_GET["nws"]) : "1";
$ratio = isset($_GET["ratio"]) ? xssafe($_GET["ratio"]) : "11";
$compaction = isset($_GET["compaction"]) ? xssafe($_GET["compaction"]) : "1";
$cobb = isset($_GET["cobb"]) ? xssafe($_GET["cobb"]) : "1";
$max_t = isset($_GET["max_t"]) ? xssafe($_GET["max_t"]) : "1";
$mean_mt = isset($_GET["mean_mt"]) ? xssafe($_GET["mean_mt"]) : "1";
$max_mt = isset($_GET["max_mt"]) ? xssafe($_GET["max_mt"]) : "1";
$mean = isset($_GET["mean"]) ? xssafe($_GET["mean"]) : "1";
$date = isset($_GET["date"]) ? xssafe($_GET["date"]) : "";
$year = isset($_GET["year"]) ? xssafe($_GET["year"]) : "";
$month = isset($_GET["month"]) ? xssafe($_GET["month"]) : "";
$day = isset($_GET["day"]) ? xssafe($_GET["day"]) : "";
$hour = isset($_GET["hour"]) ? xssafe($_GET["hour"]) : "";
$archive = isset($_GET["archive"]) ? xssafe($_GET["archive"]) : "0";

//$gfs_init_date = 0;
//$gfsm_init_date = 0;

$site = strtolower($site);

if ($year == "" || $month == "" || $day == "" || $hour == "") {
    $year = date("Y");
    $month = date("m");
    $day = date("d");
    $hour = date("H");
    $date = "" . $year . "" . $month . "" . $day . "" . $hour . "";
} else {
    if (checkdate($month, $day, $year) == False) {
        header('Content-type: text/plain');
        echo "You entered a bad time, please review and try again:\n\nYear=" . $year . "\nMonth=" . $month . "\nDay=" . $day . "\nHour=" . $hour . "";
        die();
    } else {
        $date = "" . $year . "" . $month . "" . $day . "" . $hour . "";
    }
}

$on_list = array($nam, $namm, $gfs, $gfsm, $rap, $nam_mos, $gfs_mos, $gfsm_mos, $con, $nws, $obs, $compaction, $cobb, $max_t, $mean_mt, $max_mt, $mean, $archive);

if (in_array("on", $on_list)) {
    if ($compaction == "on") {
        $compaction_check = 1;
    } else {
        $compaction_check = 0;
    }
    if ($cobb == "on") {
        $cobb_check = 1;
    } else {
        $cobb_check = 0;
    }
    if ($max_t == "on") {
        $max_t_check = 1;
    } else {
        $max_t_check = 0;
    }
    if ($mean_mt == "on") {
        $mean_mt_check = 1;
    } else {
        $mean_mt_check = 0;
    }
    if ($max_mt == "on") {
        $max_mt_check = 1;
    } else {
        $max_mt_check = 0;
    }

    if ($mean == "on") {
        $mean_check = 1;
    } else {
        $mean_check = 0;
    }
    if ($nam == "on") {
        $nam_check = 1;
    } else {
        $nam_check = 0;
    }
    if ($namm == "on") {
        $namm_check = 1;
    } else {
        $namm_check = 0;
    }
    if ($nam4km == "on") {
        $nam4km_check = 1;
    } else {
        $nam4km_check = 0;
    }
    if ($gfs == "on") {
        $gfs_check = 1;
    } else {
        $gfs_check = 0;
    }
    if ($gfsm == "on") {
        $gfsm_check = 1;
    } else {
        $gfsm_check = 0;
    }
    if ($rap == "on") {
        $rap_check = 1;
    } else {
        $rap_check = 0;
    }
    if ($nam_mos == "on") {
        $nam_mos_check = 1;
    } else {
        $nam_mos_check = 0;
    }
    if ($gfs_mos == "on") {
        $gfs_mos_check = 1;
    } else {
        $gfs_mos_check = 0;
    }
    if ($gfsm_mos == "on") {
        $gfsm_mos_check = 1;
    } else {
        $gfsm_mos_check = 0;
    }
    if ($nws == "on") {
        $nws_check = 1;
    } else {
        $nws_check = 0;
    }
    if ($obs == "on") {
        $obs_check = 1;
    } else {
        $obs_check = 0;
    }
    if ($con == "on") {
        $con_check = 1;
    } else {
        $con_check = 0;
    }
    if ($archive == "on") {
        $archive_check = 1;
    } else {
        $archive_check = 0;
    }
} else {
    $nam_check = 1;
    $namm_check = 1;
    $nam4km_check = 1;
    $gfs_check = 1;
    $gfsm_check = 1;
    $rap_check = 1;
    $nam_mos_check = 1;
    $gfs_mos_check = 1;
    $gfsm_mos_check = 1;
    $con_check = 1;
    $nws_check = 1;
    $obs_check = 1;
    $compaction_check = 1;
    $cobb_check = 1;
    $max_t_check = 1;
    $mean_mt_check = 1;
    $max_mt_check = 1;
    $mean_check = 1;
    $archive_check = 0;
}


$slater = "p#a";
$sym = "#";
$site_l = $site;
preg_match_all(".$sym.", $site, $id);
$check1 = @$id[0][0];
if ($check1 == $sym) {
    $exam = str_split($site);
    if ($exam[0] == $sym) {
        $exam[0] = "%23";
    }
    if ($exam[1] == $sym) {
        $exam[1] = "%23";
    }
    if ($exam[2] == $sym) {
        $exam[2] = "%23";
    }
    $site_l = "" . $exam[0] . "" . $exam[1] . "" . $exam[2] . "";
}


?>

<html>

<head>

    <div id="fb-root"></div>
    <script>
        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {
                return;
            }
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=192828874111938";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <script language="JavaScript">
        function disable2(archiveMode) {
            document.sidemenus.year.disabled = !(archiveMode);
            document.sidemenus.month.disabled = !(archiveMode);
            document.sidemenus.day.disabled = !(archiveMode);
            document.sidemenus.hour.disabled = !(archiveMode);
            //document.sidemenus.nws.disabled = archiveMode;
            //document.sidemenus.cobb.disabled = archiveMode;
        }
    </script>

    <script type="text/javascript">
        function writeText(txt) {
            document.getElementById("desc").innerHTML = txt;
        }

        function setMouse(obj) {
            obj.style.cursor = 'crosshair';
        }
    </script>

    <script type="text/javascript" src="images/neat.js">
    </script>

    <meta name="keywords" content="bufkit, bufkit warehouse, bufkit data,
bufkit documentation, bufkit files, bufkit download, bufkit links, install
bufkit, bufget, use bufkit, bufkit archive, meteogram, generator">

    <style rel="stylesheet" type="text/css">
        body {
            background: #FFFFFF;
        }

        th {
            background: #dddddd;
            font-size: 10pt;
            font-family: helvetica;
            text-align: center;
        }

        td {
            font-size: 8pt;
            font-family: helvetica;
        }

        h2 {
            font-size: 18pt;
            font-family: helvetica;
            text-align: center;
        }

        #menu {
            display: block;
            position: fixed;
            left: 1040px;
            top: 98px;
        }

        #menus {
            display: block;
            position: absolute;
            left: 2px;
            top: 243px;
        }

        #header {
            display: block;
            position: fixed;
            left: 2px;
            top: 0px;
        }

        #hoverText {
            display: block;
            position: fixed;
            left: 2px;
            top: 98px;
        }

        #sidemenus {
            display: block;
            position: absolute;
            left: 1112px;
            top: 243px;
        }

        * html #menu {
            position: absolute;
        }

        * html #menus {
            position: absolute;
        }

        * html #header {
            position: absolute;
        }

        * html #hoverText {
            position: absolute;
        }

        * html #sidemenus {
            position: absolute;
        }

        .hoverText {
            background: #FFFFFF;
            border: solid black 3px;
            height: 148px;
            width: 1040px;
        }

        .header {
            background: #FFFFFF;
            border: solid black 3px;
            height: 100px;
            width: 1260px;
        }

        .menu {
            background: #FFFFFF;
            border: solid black 3px;
            width: 222;
            height: 148;
        }

        .menus {
            background: #FFFFFF;
            border: solid black 3px;
            height: 2000;
            width: 1260;
        }

        .basemap {
            position: absolute;
            left: 0px;
            top: 40px;
            border: solid black 3px;
        }

        .sidemenus {
            background: #FFFFFF;
            border: solid black 3px;
            height: 4147;
            width: 150;
        }
    </style>

    <title>Meteogram Generator</title>
</head>

<body>

    <div id="menus">
        <table class="menus">
            <tr>
                <td valign="top" align="left">

                    <?php

                    $var_set1 = "nam=" . $nam_check . "&namm=" . $namm_check . "&nam4km=" . $nam4km_check . "&gfs=" . $gfs_check . "&gfsm=" . $gfsm_check . "&rap=" . $rap_check . "&nam_mos=" . $nam_mos_check . "&gfs_mos=" . $gfs_mos_check . "&gfsm_mos=" . $gfsm_mos_check . "&nws=" . $nws_check . "&obs=" . $obs_check . "&con=" . $con_check . "";
                    $var_set2 = "max_t=" . $max_t_check . "&cobb=" . $cobb_check . "&compaction=" . $compaction_check . "&ratio=" . $ratio . "";
                    $var_set3 = "mean_mt=" . $mean_mt_check . "&max_mt=" . $max_mt_check . "&mean=" . $mean_check . "";
                    if ($archive_check == 1) {
                        $var_set1 = "" . $var_set1 . "&date=" . $date . "";
                    }

                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=snow_accum&" . $var_set1 . "&" . $var_set2 . "\" alt=\"snow accumulation plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";
                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=qpf_accum&" . $var_set1 . "\" alt=\"precip accumulation plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";
                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=tf&" . $var_set1 . "\" alt=\"temperature plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";
                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=hiwc&" . $var_set1 . "\" alt=\"apparent temp plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";
                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=td&" . $var_set1 . "\" alt=\"dewpoint plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";
                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=wind&" . $var_set1 . "&" . $var_set3 . "\" alt=\"wind speed plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";
                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=wdir&" . $var_set1 . "\" alt=\"wind direction plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";
                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=frz_rain&" . $var_set1 . "\" alt=\"freezing rain plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";
                    echo "<p>\n<img src=\"images/plotter.php?site=" . $site_l . "&var=sleet&" . $var_set1 . "\" alt=\"sleet plot\" usemap=\"#precip\" border=\"0\">\n</p>\n";

                    ?>

                </td>
            </tr>
        </table>
    </div>

    <div id="sidemenus">
        <table class="sidemenus">
            <form action="image_loader.phtml?site=<?php echo $site_l; ?>" method="get" name=sidemenus>
                <tr>
                    <td valign="top" align="left">
                        <p>
                            <center>
                                <b><u>Configuration Options:</b></u>
                        </p>
                        <p>
                            <u>Site:</u>
                            <input type="text" size="6" name="site" value="<?php echo $site; ?>" maxlength=6 />
                        </p>
                        <p>
                        <table border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="55"><input type=checkbox name="nam" <?php if ($nam_check == 1) {
                                                                                    echo "checked=\"yes\"";
                                                                                } ?>>NAM</input></td>
                                <td width="80"><input type=checkbox name="nam_mos" <?php if ($nam_mos_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>NAM MOS</input></td>
                            </tr>
                            <tr>
                                <td width="55"><input type=checkbox name="namm" <?php if ($namm_check == 1) {
                                                                                    echo "checked=\"yes\"";
                                                                                } ?>>NAMM</input></td>
                                <td width="80"><input type=checkbox name="gfs_mos" <?php if ($gfs_mos_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>GFS MOS</input></td>
                            </tr>
                            <tr>
                                <td width="55"><input type=checkbox name="gfs" <?php if ($gfs_check == 1) {
                                                                                    echo "checked=\"yes\"";
                                                                                } ?>>GFS</input></td>
                                <td width="80"><input type=checkbox name="gfsm_mos" <?php if ($gfsm_mos_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>GFSM MOS</input></td>
                            </tr>
                            <tr>
                                <td width="55"><input type=checkbox name="gfsm" <?php if ($gfsm_check == 1) {
                                                                                    echo "checked=\"yes\"";
                                                                                } ?>>GFSM</input></td>
                                <td width="80"><input type=checkbox name="nws" <?php if ($nws_check == 1) {
                                                                                    echo "checked=\"yes\"";
                                                                                } ?>>NWS</input></td>
                            </tr>
                            <tr>
                                <td width="55"><input type=checkbox name="rap" <?php if ($rap_check == 1) {
                                                                                    echo "checked=\"yes\"";
                                                                                } ?>>RAP</input></td>
                                <td width="80"><input type=checkbox name="obs" <?php if ($obs_check == 1) {
                                                                                    echo "checked=\"yes\"";
                                                                                } ?>>OBS</input></td>
                            </tr>
                        </table>
                        <table border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="55"><input type=checkbox name="nam4km" <?php if ($nam4km_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>NAM 4km</input></td>
                            </tr>
                            <tr>
                                <td width="135"><input type=checkbox name="con" <?php if ($con_check == 1) {
                                                                                    echo "checked=\"yes\"";
                                                                                } ?>>MODEL AVERAGE</input></td>
                            </tr>
                        </table>
                        </p>
                        <hr color=#000000>
                        <p>
                            <input name=archive type="checkbox" onClick="disable2(this.checked)" /> Archived Mode
                        </p>
                        <p>
                            Year:
                            <select name="year" disabled="disabled">
                                <option value="2023" <?php if ($year == 2023) {
                                                            echo "Selected";
                                                        } ?>>2023
                                <option value="2022" <?php if ($year == 2022) {
                                                            echo "Selected";
                                                        } ?>>2022
                                <option value="2021" <?php if ($year == 2021) {
                                                            echo "Selected";
                                                        } ?>>2021
                                <option value="2020" <?php if ($year == 2020) {
                                                            echo "Selected";
                                                        } ?>>2020
                                <option value="2019" <?php if ($year == 2019) {
                                                            echo "Selected";
                                                        } ?>>2019
                                <option value="2018" <?php if ($year == 2018) {
                                                            echo "Selected";
                                                        } ?>>2018
                                <option value="2017" <?php if ($year == 2017) {
                                                            echo "Selected";
                                                        } ?>>2017
                                <option value="2016" <?php if ($year == 2016) {
                                                            echo "Selected";
                                                        } ?>>2016
                                <option value="2015" <?php if ($year == 2015) {
                                                            echo "Selected";
                                                        } ?>>2015
                                <option value="2014" <?php if ($year == 2014) {
                                                            echo "Selected";
                                                        } ?>>2014
                                <option value="2013" <?php if ($year == 2013) {
                                                            echo "Selected";
                                                        } ?>>2013
                                <option value="2012" <?php if ($year == 2012) {
                                                            echo "Selected";
                                                        } ?>>2012
                                <option value="2011" <?php if ($year == 2011) {
                                                            echo "Selected";
                                                        } ?>>2011
                                </option>
                            </select>
                        </p>
                        <p>
                            Month:
                            <select name="month" disabled="disabled">
                                <option value="01" <?php if ($month == "01") {
                                                        echo "Selected";
                                                    } ?>>1
                                <option value="02" <?php if ($month == "02") {
                                                        echo "Selected";
                                                    } ?>>2
                                <option value="03" <?php if ($month == "03") {
                                                        echo "Selected";
                                                    } ?>>3
                                <option value="04" <?php if ($month == "04") {
                                                        echo "Selected";
                                                    } ?>>4
                                <option value="05" <?php if ($month == "05") {
                                                        echo "Selected";
                                                    } ?>>5
                                <option value="06" <?php if ($month == "06") {
                                                        echo "Selected";
                                                    } ?>>6
                                <option value="07" <?php if ($month == "07") {
                                                        echo "Selected";
                                                    } ?>>7
                                <option value="08" <?php if ($month == "08") {
                                                        echo "Selected";
                                                    } ?>>8
                                <option value="09" <?php if ($month == "09") {
                                                        echo "Selected";
                                                    } ?>>9
                                <option value="10" <?php if ($month == "10") {
                                                        echo "Selected";
                                                    } ?>>10
                                <option value="11" <?php if ($month == "11") {
                                                        echo "Selected";
                                                    } ?>>11
                                <option value="12" <?php if ($month == "12") {
                                                        echo "Selected";
                                                    } ?>>12
                                </option>
                            </select>
                        </p>
                        <p>
                            Day:
                            <select name="day" disabled="disabled">
                                <option value="01" <?php if ($day == "01") {
                                                        echo "Selected";
                                                    } ?>>1
                                <option value="02" <?php if ($day == "02") {
                                                        echo "Selected";
                                                    } ?>>2
                                <option value="03" <?php if ($day == "03") {
                                                        echo "Selected";
                                                    } ?>>3
                                <option value="04" <?php if ($day == "04") {
                                                        echo "Selected";
                                                    } ?>>4
                                <option value="05" <?php if ($day == "05") {
                                                        echo "Selected";
                                                    } ?>>5
                                <option value="06" <?php if ($day == "06") {
                                                        echo "Selected";
                                                    } ?>>6
                                <option value="07" <?php if ($day == "07") {
                                                        echo "Selected";
                                                    } ?>>7
                                <option value="08" <?php if ($day == "08") {
                                                        echo "Selected";
                                                    } ?>>8
                                <option value="09" <?php if ($day == "09") {
                                                        echo "Selected";
                                                    } ?>>9
                                <option value="10" <?php if ($day == "10") {
                                                        echo "Selected";
                                                    } ?>>10
                                <option value="11" <?php if ($day == "11") {
                                                        echo "Selected";
                                                    } ?>>11
                                <option value="12" <?php if ($day == "12") {
                                                        echo "Selected";
                                                    } ?>>12
                                <option value="13" <?php if ($day == "13") {
                                                        echo "Selected";
                                                    } ?>>13
                                <option value="14" <?php if ($day == "14") {
                                                        echo "Selected";
                                                    } ?>>14
                                <option value="15" <?php if ($day == "15") {
                                                        echo "Selected";
                                                    } ?>>15
                                <option value="16" <?php if ($day == "16") {
                                                        echo "Selected";
                                                    } ?>>16
                                <option value="17" <?php if ($day == "17") {
                                                        echo "Selected";
                                                    } ?>>17
                                <option value="18" <?php if ($day == "18") {
                                                        echo "Selected";
                                                    } ?>>18
                                <option value="19" <?php if ($day == "19") {
                                                        echo "Selected";
                                                    } ?>>19
                                <option value="20" <?php if ($day == "20") {
                                                        echo "Selected";
                                                    } ?>>20
                                <option value="21" <?php if ($day == "21") {
                                                        echo "Selected";
                                                    } ?>>21
                                <option value="22" <?php if ($day == "22") {
                                                        echo "Selected";
                                                    } ?>>22
                                <option value="23" <?php if ($day == "23") {
                                                        echo "Selected";
                                                    } ?>>23
                                <option value="24" <?php if ($day == "24") {
                                                        echo "Selected";
                                                    } ?>>24
                                <option value="25" <?php if ($day == "25") {
                                                        echo "Selected";
                                                    } ?>>25
                                <option value="26" <?php if ($day == "26") {
                                                        echo "Selected";
                                                    } ?>>26
                                <option value="27" <?php if ($day == "27") {
                                                        echo "Selected";
                                                    } ?>>27
                                <option value="28" <?php if ($day == "28") {
                                                        echo "Selected";
                                                    } ?>>28
                                <option value="29" <?php if ($day == "29") {
                                                        echo "Selected";
                                                    } ?>>29
                                <option value="30" <?php if ($day == "30") {
                                                        echo "Selected";
                                                    } ?>>30
                                <option value="31" <?php if ($day == "31") {
                                                        echo "Selected";
                                                    } ?>>31
                                </option>
                            </select>
                        </p>
                        <p>
                            Hour:
                            <select name="hour" disabled="disabled">
                                <option value="00" <?php if ($hour == "00") {
                                                        echo "Selected";
                                                    } ?>>0
                                <option value="01" <?php if ($hour == "01") {
                                                        echo "Selected";
                                                    } ?>>1
                                <option value="02" <?php if ($hour == "02") {
                                                        echo "Selected";
                                                    } ?>>2
                                <option value="03" <?php if ($hour == "03") {
                                                        echo "Selected";
                                                    } ?>>3
                                <option value="04" <?php if ($hour == "04") {
                                                        echo "Selected";
                                                    } ?>>4
                                <option value="05" <?php if ($hour == "05") {
                                                        echo "Selected";
                                                    } ?>>5
                                <option value="06" <?php if ($hour == "06") {
                                                        echo "Selected";
                                                    } ?>>6
                                <option value="07" <?php if ($hour == "07") {
                                                        echo "Selected";
                                                    } ?>>7
                                <option value="08" <?php if ($hour == "08") {
                                                        echo "Selected";
                                                    } ?>>8
                                <option value="09" <?php if ($hour == "09") {
                                                        echo "Selected";
                                                    } ?>>9
                                <option value="10" <?php if ($hour == "10") {
                                                        echo "Selected";
                                                    } ?>>10
                                <option value="11" <?php if ($hour == "11") {
                                                        echo "Selected";
                                                    } ?>>11
                                <option value="12" <?php if ($hour == "12") {
                                                        echo "Selected";
                                                    } ?>>12
                                <option value="13" <?php if ($hour == "13") {
                                                        echo "Selected";
                                                    } ?>>13
                                <option value="14" <?php if ($hour == "14") {
                                                        echo "Selected";
                                                    } ?>>14
                                <option value="15" <?php if ($hour == "15") {
                                                        echo "Selected";
                                                    } ?>>15
                                <option value="16" <?php if ($hour == "16") {
                                                        echo "Selected";
                                                    } ?>>16
                                <option value="17" <?php if ($hour == "17") {
                                                        echo "Selected";
                                                    } ?>>17
                                <option value="18" <?php if ($hour == "18") {
                                                        echo "Selected";
                                                    } ?>>18
                                <option value="19" <?php if ($hour == "19") {
                                                        echo "Selected";
                                                    } ?>>19
                                <option value="20" <?php if ($hour == "20") {
                                                        echo "Selected";
                                                    } ?>>20
                                <option value="21" <?php if ($hour == "21") {
                                                        echo "Selected";
                                                    } ?>>21
                                <option value="22" <?php if ($hour == "22") {
                                                        echo "Selected";
                                                    } ?>>22
                                <option value="23" <?php if ($hour == "23") {
                                                        echo "Selected";
                                                    } ?>>23
                                </option>
                            </select>
                        </p>
                        <hr color=#000000>
                        <p>
                            <input type="submit" value="Re-Generate!" />
                        </p>
                        <hr color=#000000>
                        <p>
                            <b><u>Snowfall Plot:</b></u>
                        </p>
                        <p>
                            <u>Snow Ratio:</u>
                            <select name="ratio">
                                <option value="30" <?php if ($ratio == 30) {
                                                        echo "Selected";
                                                    } ?>>30
                                <option value="29" <?php if ($ratio == 29) {
                                                        echo "Selected";
                                                    } ?>>29
                                <option value="28" <?php if ($ratio == 28) {
                                                        echo "Selected";
                                                    } ?>>28
                                <option value="27" <?php if ($ratio == 27) {
                                                        echo "Selected";
                                                    } ?>>27
                                <option value="26" <?php if ($ratio == 26) {
                                                        echo "Selected";
                                                    } ?>>26
                                <option value="25" <?php if ($ratio == 25) {
                                                        echo "Selected";
                                                    } ?>>25
                                <option value="24" <?php if ($ratio == 24) {
                                                        echo "Selected";
                                                    } ?>>24
                                <option value="23" <?php if ($ratio == 23) {
                                                        echo "Selected";
                                                    } ?>>23
                                <option value="22" <?php if ($ratio == 22) {
                                                        echo "Selected";
                                                    } ?>>22
                                <option value="21" <?php if ($ratio == 21) {
                                                        echo "Selected";
                                                    } ?>>21
                                <option value="20" <?php if ($ratio == 20) {
                                                        echo "Selected";
                                                    } ?>>20
                                <option value="19" <?php if ($ratio == 19) {
                                                        echo "Selected";
                                                    } ?>>19
                                <option value="18" <?php if ($ratio == 18) {
                                                        echo "Selected";
                                                    } ?>>18
                                <option value="17" <?php if ($ratio == 17) {
                                                        echo "Selected";
                                                    } ?>>17
                                <option value="16" <?php if ($ratio == 16) {
                                                        echo "Selected";
                                                    } ?>>16
                                <option value="15" <?php if ($ratio == 15) {
                                                        echo "Selected";
                                                    } ?>>15
                                <option value="14" <?php if ($ratio == 14) {
                                                        echo "Selected";
                                                    } ?>>14
                                <option value="13" <?php if ($ratio == 13) {
                                                        echo "Selected";
                                                    } ?>>13
                                <option value="12" <?php if ($ratio == 12) {
                                                        echo "Selected";
                                                    } ?>>12
                                <option value="11" <?php if ($ratio == 11) {
                                                        echo "Selected";
                                                    } ?>>11
                                <option value="10" <?php if ($ratio == 10) {
                                                        echo "Selected";
                                                    } ?>>10
                                <option value="9" <?php if ($ratio == 9) {
                                                        echo "Selected";
                                                    } ?>>9
                                <option value="8" <?php if ($ratio == 8) {
                                                        echo "Selected";
                                                    } ?>>8
                                <option value="7" <?php if ($ratio == 7) {
                                                        echo "Selected";
                                                    } ?>>7
                                <option value="6" <?php if ($ratio == 6) {
                                                        echo "Selected";
                                                    } ?>>6
                                <option value="5" <?php if ($ratio == 5) {
                                                        echo "Selected";
                                                    } ?>>5
                                <option value="4" <?php if ($ratio == 4) {
                                                        echo "Selected";
                                                    } ?>>4
                                <option value="3" <?php if ($ratio == 3) {
                                                        echo "Selected";
                                                    } ?>>3
                                <option value="2" <?php if ($ratio == 2) {
                                                        echo "Selected";
                                                    } ?>>2
                                <option value="1" <?php if ($ratio == 1) {
                                                        echo "Selected";
                                                    } ?>>1
                                <option value="0" <?php if ($ratio == 0) {
                                                        echo "Selected";
                                                    } ?>>NP
                                </option>
                            </select>
                            :1</font>
                        </p>

                        <table border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="135"><input type=checkbox name="max_t" <?php if ($max_t_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>Max-T in Prof.</input></td>
                            </tr>
                            <tr>
                                <td width="135"><input type=checkbox name="cobb" <?php if ($cobb_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>Cobb Method</input></td>
                            </tr>
                            <tr>
                                <td width="135"><input type=checkbox name="compaction" <?php if ($compaction_check == 1) {
                                                                                            echo "checked=\"yes\"";
                                                                                        } ?>>Compaction</input></td>
                            </tr>
                        </table>

                        <p>
                            <a href="compaction.html">What is Compaction?</a>
                        </p>
                        <hr color=#000000>
                        <p>
                            <b><u>Wind Speed Plot:</b></u>
                        </p>

                        <table border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="135"><input type=checkbox name="mean_mt" <?php if ($mean_mt_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>Mean Mom. Transfer</input></td>
                            </tr>
                            <tr>
                                <td width="135"><input type=checkbox name="max_mt" <?php if ($max_mt_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>Max Mom. Transfer</input></td>
                            </tr>
                            <tr>
                                <td width="135"><input type=checkbox name="mean" <?php if ($mean_check == 1) {
                                                                                        echo "checked=\"yes\"";
                                                                                    } ?>>Mean Wind</input></td>
                            </tr>
                        </table>

                        <p>
                            <a href="momentum_transfer.html">Momentum Transfer (MT)?</a>
                        </p>
                        <hr color=#000000>

                        <p>
                            <b><u>Other:</b></u>
                        </p>
                        <p>
                            <a href="apparent_temperature.html">Apparent Temperature?</a>
                        </p>

                        </center>
                    </td>
                </tr>
        </table>
        </form>
    </div>

    <div id="header">
        <table class="header">

            <tr>
                <td align=center>
                    <img src="images/title.png" alt="Header" usemap="#ThisMap" border="0">
                    <MAP name="ThisMap">

                        <area shape=rect coords="29,9,89,49" href="http://www.ge-at.iastate.edu/" alt="ISU/GEAT" title="ISU/GEAT" />

                        <area shape=rect coords="855,9,918,53" href="http://mesonet.agron.iastate.edu" alt="IEM" title="IEM" />

                        <area shape=rect coords="972,8,1232,56" href="http://www.meteor.iastate.edu/~ckarsten/bufkit/bufkit.html" alt="Bufkit Warehouse" title="Bufkit Warehouse" />

                </td>
            </tr>

        </table>
    </div>


    <div id="menu">
        <table class="menu">
            <tr>
                <td valign="top" align="center">

                    Browse the <a href="data/index.html">Google Map</a> for other locations (click <b>Visualize Data!</b>).
                    <br>
                    <p>
                        <a href="http://www.facebook.com/pages/The-Bufkit-Warehouse/106061659471133">Bufkit Warehouse</a> on Facebook!

                    <div class="fb-like" data-href="http://www.facebook.com/pages/The-Bufkit-Warehouse/106061659471133" data-send="false" data-layout="button_count" data-width="40" data-show-faces="false"></div>
                    </p>
                    <u>Questions/Comments?</u>
                    karstens.chris@gmail.com
            </tr>
            </td>
        </table>
    </div>

    <div id="hoverText">
        <table class="hoverText" border="0">
            <tr>
                <td valign="top" align="left">
                    <table border="0" cellspacing="0" cellpadding="0">

                        <tr>
                            <td align=center>
                                <p id="desc"></p>
                            </td>
                        </tr>

                    </table>
                </td>
            </tr>
        </table>
    </div>


    <?php

    // define wind dir function
    function get_wind_dir($cam_ang)
    {
        if (0 <= $cam_ang && $cam_ang <= 11) {
            $dir = "N";
        } elseif (11 < $cam_ang && $cam_ang <= 34) {
            $dir = "NNE";
        } elseif (34 < $cam_ang && $cam_ang <= 45) {
            $dir = "NE";
        } elseif (45 < $cam_ang && $cam_ang <= 56) {
            $dir = "NE";
        } elseif (56 < $cam_ang && $cam_ang <= 79) {
            $dir = "ENE";
        } elseif (79 < $cam_ang && $cam_ang <= 101) {
            $dir = "E";
        } elseif (101 < $cam_ang && $cam_ang <= 124) {
            $dir = "ESE";
        } elseif (124 < $cam_ang && $cam_ang <= 135) {
            $dir = "SE";
        } elseif (135 < $cam_ang && $cam_ang <= 146) {
            $dir = "SE";
        } elseif (146 < $cam_ang && $cam_ang <= 169) {
            $dir = "SSE";
        } elseif (169 < $cam_ang && $cam_ang <= 191) {
            $dir = "S";
        } elseif (191 < $cam_ang && $cam_ang <= 214) {
            $dir = "SSW";
        } elseif (214 < $cam_ang && $cam_ang <= 225) {
            $dir = "SW";
        } elseif (225 < $cam_ang && $cam_ang <= 236) {
            $dir = "SW";
        } elseif (236 < $cam_ang && $cam_ang <= 259) {
            $dir = "WSW";
        } elseif (259 < $cam_ang && $cam_ang <= 281) {
            $dir = "W";
        } elseif (281 < $cam_ang && $cam_ang <= 304) {
            $dir = "WNW";
        } elseif (304 < $cam_ang && $cam_ang <= 315) {
            $dir = "NW";
        } elseif (315 < $cam_ang && $cam_ang <= 326) {
            $dir = "NW";
        } elseif (326 < $cam_ang && $cam_ang <= 349) {
            $dir = "NNW";
        } elseif (349 < $cam_ang && $cam_ang <= 360) {
            $dir = "N";
        }

        return $dir;
    }


    // check if site is in master list.  If not, terminate script and tell user
    $found = 0;
    $sites = array();
    for ($z = 0; $z <= 1; $z++) {
        if ($z == 0) {
            $master_list = "images/nam_bufrstations.txt";
        } elseif ($z == 1) {
            $master_list = "images/gfs3_bufrstations.txt";
        }
        $data = file($master_list);
        foreach ($data as $line) {
            $d = explode(" ", trim(preg_replace('/\s+/', ' ', $line)));
            $sites[] = strtolower($d[3]);
            if ($site == strtolower($d[3])) {
                $found = 1;
                if ($z == 0) {
                    if ($site == "kaus") {
                        $lat = $d[1] - 0.1;
                        $lon = $d[2];
                    } else {
                        $lat = $d[1];
                        $lon = $d[2];
                    }
                } elseif ($z == 1) {
                    if (strpbrk($d[1], "N")) {
                        $lat = trim($d[1], "N");
                    } else {
                        $lat = trim($d[1], "S") * -1;
                    }
                    if (strpbrk($d[2], "E")) {
                        $lon = trim($d[2], "E");
                    } else {
                        $lon = trim($d[2], "W") * -1;
                    }
                }
                break;
            }
        }
        if ($found == 1) {
            break;
        }
    }
    if (!(in_array($site, $sites))) {
        die("Site " . $site . " is not available.  Try again.");
    }

    $var1 = "qpf";
    $var2 = "qpf_accum";
    $var3 = "tf";
    $var4 = "td";
    $var5 = "wspd";
    $var6 = "wdir";
    $var7 = "uwnd";
    $var8 = "vwnd";

    for ($z = 0; $z <= 5; $z++) {
        if ($z == 0) {
            $mdl = "nam";
            $nam_var1 = array();
            $nam_var2 = array();
            $nam_var3 = array();
            $nam_var4 = array();
            $nam_var5 = array();
            $nam_var6 = array();
            $nam_date = array();
            $nam_time = array();
            $nam_wind_x = array();
            $nam_wind_y = array();
            if ($archive_check == 1) {
                if ($hour >= 0 && $hour <= 11) {
                    $parse_date = "" . $year . "" . $month . "" . $day . "00";
                } else {
                    $parse_date = "" . $year . "" . $month . "" . $day . "12";
                }
            }
        } elseif ($z == 1) {
            $mdl = "namm";
            $namm_date = array();
            $namm_var1 = array();
            $namm_var2 = array();
            $namm_var3 = array();
            $namm_var4 = array();
            $namm_var5 = array();
            $namm_var6 = array();
            $namm_time = array();
            $namm_wind_x = array();
            $namm_wind_y = array();
            if ($archive_check == 1) {
                if ($hour >= 0 && $hour <= 5) {
                    $temp_date = strtotime("" . $year . "-" . $month . "-" . $day . " 00:00:00") - 21600;
                    $parse_date = date("YmdH", $temp_date);
                } elseif ($hour >= 6 && $hour <= 17) {
                    $parse_date = "" . $year . "" . $month . "" . $day . "06";
                } else {
                    $parse_date = "" . $year . "" . $month . "" . $day . "18";
                }
            }
        } elseif ($z == 2) {
            $mdl = "gfs";
            $gfs_date = array();
            $gfs_var1 = array();
            $gfs_var2 = array();
            $gfs_var3 = array();
            $gfs_var4 = array();
            $gfs_var5 = array();
            $gfs_var6 = array();
            $gfs_time = array();
            $gfs_wind_x = array();
            $gfs_wind_y = array();
            if ($archive_check == 1) {
                if ($hour >= 0 && $hour <= 11) {
                    $parse_date = "" . $year . "" . $month . "" . $day . "00";
                } else {
                    $parse_date = "" . $year . "" . $month . "" . $day . "12";
                }
            }
        } elseif ($z == 3) {
            $mdl = "gfsm";
            $gfsm_date = array();
            $gfsm_var1 = array();
            $gfsm_var2 = array();
            $gfsm_var3 = array();
            $gfsm_var4 = array();
            $gfsm_var5 = array();
            $gfsm_var6 = array();
            $gfsm_time = array();
            $gfsm_wind_x = array();
            $gfsm_wind_y = array();
            if ($archive_check == 1) {
                if ($hour >= 0 && $hour <= 5) {
                    $temp_date = strtotime("" . $year . "-" . $month . "-" . $day . " 00:00:00") - 21600;
                    $parse_date = date("YmdH", $temp_date);
                } elseif ($hour >= 6 && $hour <= 17) {
                    $parse_date = "" . $year . "" . $month . "" . $day . "06";
                } else {
                    $parse_date = "" . $year . "" . $month . "" . $day . "18";
                }
            }
        } elseif ($z == 4) {
            $mdl = "rap";
            $rap_date = array();
            $rap_var1 = array();
            $rap_var2 = array();
            $rap_var3 = array();
            $rap_var4 = array();
            $rap_var5 = array();
            $rap_var6 = array();
            $rap_time = array();
            $rap_wind_x = array();
            $rap_wind_y = array();
            $parse_date = "" . $year . "" . $month . "" . $day . "" . $hour . "";;
        } elseif ($z == 5) {
            $mdl = "nam4km";
            $nam4km_var1 = array();
            $nam4km_var2 = array();
            $nam4km_var3 = array();
            $nam4km_var4 = array();
            $nam4km_var5 = array();
            $nam4km_var6 = array();
            $nam4km_date = array();
            $nam4km_time = array();
            $nam4km_wind_x = array();
            $nam4km_wind_y = array();
            if ($archive_check == 1) {
                if ($hour >= 0 && $hour <= 11) {
                    $parse_date = "" . $year . "" . $month . "" . $day . "00";
                } else {
                    $parse_date = "" . $year . "" . $month . "" . $day . "12";
                }
            }
        }
        if ($archive_check != 1) {
            $link = ROOTURL . "/data/parser.php?model=" . $mdl . "&site=" . $site_l . "";
        } else {
            $link = ROOTURL . "/data/parser.php?model=" . $mdl . "&site=" . $site_l . "&date=" . $parse_date . "";
            //echo "".$link."\n";
        }
        $data = file($link);
        $z2 = 0;
        if ($data == False) {
            continue;
        } else {
            foreach ($data as $line) {
                $d = explode("\t", trim($line));
                $z2++;
                if ($z2 == 1) {
                    if (array_search($var1, $d)) {
                        $index1 = array_search($var1, $d);
                    } else {
                        continue;
                    }
                    if (array_search($var2, $d)) {
                        $index2 = array_search($var2, $d);
                    } else {
                        continue;
                    }
                    if (array_search($var3, $d)) {
                        $index3 = array_search($var3, $d);
                    } else {
                        continue;
                    }
                    if (array_search($var4, $d)) {
                        $index4 = array_search($var4, $d);
                    } else {
                        continue;
                    }
                    if (array_search($var5, $d)) {
                        $index5 = array_search($var5, $d);
                    } else {
                        continue;
                    }
                    if (array_search($var6, $d)) {
                        $index6 = array_search($var6, $d);
                    } else {
                        continue;
                    }
                    if (array_search($var7, $d)) {
                        $index7 = array_search($var7, $d);
                    } else {
                        continue;
                    }
                    if (array_search($var8, $d)) {
                        $index8 = array_search($var8, $d);
                    } else {
                        continue;
                    }
                } elseif ($z == 0) {
                    $mod_time = strtotime($d[1]);
                    $nam_var1[] = "" . round($d[$index1], 2) . " in.";
                    $nam_var2[] = "" . round($d[$index2], 2) . " in.";
                    $nam_var3[] = "" . round($d[$index3], 0) . " F";
                    $nam_var4[] = "" . round($d[$index4], 0) . " F";
                    $nam_var5[] = "" . round($d[$index5], 0) . " mph";
                    $nam_var6[] = get_wind_dir($d[$index6]);
                    $nam_time[] = $mod_time;
                    $nam_date[] = date("m/d @ H\z", $mod_time);
                    $nam_wind_x[] = $d[$index7];
                    $nam_wind_y[] = $d[$index8];
                    if ($z2 == 2) {
                        $nam_init = date("H", $mod_time);
                    }
                } elseif ($z == 1) {
                    $mod_time = strtotime($d[1]);
                    $namm_var1[] = "" . round($d[$index1], 2) . " in.";
                    $namm_var2[] = "" . round($d[$index2], 2) . " in.";
                    $namm_var3[] = "" . round($d[$index3], 0) . " F";
                    $namm_var4[] = "" . round($d[$index4], 0) . " F";
                    $namm_var5[] = "" . round($d[$index5], 0) . " mph";
                    $namm_var6[] = get_wind_dir($d[$index6]);
                    $namm_time[] = $mod_time;
                    $namm_date[] = date("m/d @ H\z", $mod_time);
                    $namm_wind_x[] = $d[$index7];
                    $namm_wind_y[] = $d[$index8];
                    if ($z2 == 2) {
                        $namm_init = date("H", $mod_time);
                    }
                } elseif ($z == 2) {
                    $mod_time = strtotime($d[1]);
                    $gfs_var1[] = "" . round($d[$index1], 2) . " in.";
                    $gfs_var2[] = "" . round($d[$index2], 2) . " in.";
                    $gfs_var3[] = "" . round($d[$index3], 0) . " F";
                    $gfs_var4[] = "" . round($d[$index4], 0) . " F";
                    $gfs_var5[] = "" . round($d[$index5], 0) . " mph";
                    $gfs_var6[] = get_wind_dir($d[$index6]);
                    $gfs_time[] = $mod_time;
                    $gfs_date[] = date("m/d @ H\z", $mod_time);
                    $gfs_wind_x[] = $d[$index7];
                    $gfs_wind_y[] = $d[$index8];
                    if ($z2 == 2) {
                        $gfs_init = date("H", $mod_time);
                        $gfs_init_date    = date("YmdH", $mod_time);
                    }
                } elseif ($z == 3) {
                    $mod_time = strtotime($d[1]);
                    $gfsm_var1[] = "" . round($d[$index1], 2) . " in.";
                    $gfsm_var2[] = "" . round($d[$index2], 2) . " in.";
                    $gfsm_var3[] = "" . round($d[$index3], 0) . " F";
                    $gfsm_var4[] = "" . round($d[$index4], 0) . " F";
                    $gfsm_var5[] = "" . round($d[$index5], 0) . " mph";
                    $gfsm_var6[] = get_wind_dir($d[$index6]);
                    $gfsm_time[] = $mod_time;
                    $gfsm_date[] = date("m/d @ H\z", $mod_time);
                    $gfsm_wind_x[] = $d[$index7];
                    $gfsm_wind_y[] = $d[$index8];
                    if ($z2 == 2) {
                        $gfsm_init = date("H", $mod_time);
                        $gfsm_init_date = date("YmdH", $mod_time);
                    }
                } elseif ($z == 4) {
                    $mod_time = strtotime($d[1]);
                    $rap_var1[] = "" . round($d[$index1], 2) . " in.";
                    $rap_var2[] = "" . round($d[$index2], 2) . " in.";
                    $rap_var3[] = "" . round($d[$index3], 0) . " F";
                    $rap_var4[] = "" . round($d[$index4], 0) . " F";
                    $rap_var5[] = "" . round($d[$index5], 0) . " mph";
                    $rap_var6[] = get_wind_dir($d[$index6]);
                    $rap_time[] = $mod_time;
                    $rap_date[] = date("m/d @ H\z", $mod_time);
                    $rap_wind_x[] = $d[$index7];
                    $rap_wind_y[] = $d[$index8];
                    if ($z2 == 2) {
                        $rap_init = date("H", $mod_time);
                    }
                } elseif ($z == 5) {
                    $mod_time = strtotime($d[1]);
                    $nam4km_var1[] = "" . round($d[$index1], 2) . " in.";
                    $nam4km_var2[] = "" . round($d[$index2], 2) . " in.";
                    $nam4km_var3[] = "" . round($d[$index3], 0) . " F";
                    $nam4km_var4[] = "" . round($d[$index4], 0) . " F";
                    $nam4km_var5[] = "" . round($d[$index5], 0) . " mph";
                    $nam4km_var6[] = get_wind_dir($d[$index6]);
                    $nam4km_time[] = $mod_time;
                    $nam4km_date[] = date("m/d @ H\z", $mod_time);
                    $nam4km_wind_x[] = $d[$index7];
                    $nam4km_wind_y[] = $d[$index8];
                    if ($z2 == 2) {
                        $nam4km_init = date("H", $mod_time - 3600);
                    }
                }
            }
        }
    }

    //print_r($gfs_time);
    //die();

    if (!empty($gfs_time) && !empty($gfsm_time)) {
        $min = min($gfs_time[0], $gfsm_time[0]);
        $max = max($gfs_time[count($gfs_time) - 1], @$gfsm_time[count($gfsm_time) - 1]);
    } else {
        $link = ROOTURL . "data/parser.php?model=gfs&site=kdsm&date=" . $gfs_init_date . "";
        $data = file($link);
        foreach ($data as $line) {
            $d = explode("\t", trim($line));
            $buf_t_gfs[] = strtotime($d[1]);
        }
        $link = ROOTURL . "data/parser.php?model=gfsm&site=kdsm&" . $gfsm_init_date . "";
        $data = file($link);
        foreach ($data as $line) {
            $d = explode("\t", trim($line));
            $buf_t_gfsm[] = strtotime($d[1]);
        }
        $min = min($buf_t_gfs[1], $buf_t_gfsm[1]);
        $max = max($buf_t_gfs[count($buf_t_gfs) - 1], $buf_t_gfsm[count($buf_t_gfsm) - 1]);
    }
    $diff = ($max - $min) / 3600;
    //echo "".$max.",".$min.",".$diff.",hello\n";
    //die();
    if ($archive_check == 1) {
        $link = "https://mesonet.agron.iastate.edu/request/asos/csv.php?lat=" . $lat . "&lon=" . $lon . "&date=" . date("Y-m-d", $min) . "";
    } else {
        $link = "https://mesonet.agron.iastate.edu/request/asos/csv.php?lat=" . $lat . "&lon=" . $lon . "";
    }
    $obs_time = array();
    $obs_temp = array();
    $obs_dew = array();
    $obs_wspd = array();
    $obs_wdir = array();
    $obs_precip = array();
    $obs_precip_accum = array();
    $obs_date = array();
    $ob_station = "";
    $z = 0;
    $kf = -1;
    $data = file($link);
    $oHourLast = -99;
    foreach ($data as $line) {
        $z++;
        if ($z > 1) {
            $d = explode(",", trim($line));
            $ob_time = strtotime("" . $d[1] . "Z");
            $minute = date("i", $ob_time);
            $oHour = date("H", $ob_time);
            if ($ob_time >= ($min - 3600) && $d[2] != -99 && $minute >= 45 && $minute <= 56 && $oHour != $oHourLast) {
                $kf++;
                $obs_lat = $d[10];
                $obs_lon = $d[9];
                $lat_diff = abs($lat - $obs_lat);
                $lon_diff = abs($lon - $obs_lon);
                if ($lat_diff > 1 || $lon_diff > 1) {
                    break;
                }
                if (strlen($d[0]) == 3) {
                    $ob_station = "K" . $d[0] . "";
                } else {
                    $ob_station = $d[0];
                }
                $obs_time1[] = $ob_time;
                $ob_time2 = $ob_time + 3600;
                $obs_time[] = strtotime(date("Y-m-d H:00:00", $ob_time2));
                $obs_temp[] = "" . round($d[2], 1) . " F";
                $obs_dew[] = "" . round($d[3], 1) . " F";
                $obs_wspd[] = "" . round($d[4] * 1.15077945, 0) . " mph";
                $obs_wdir[] = get_wind_dir($d[5]);
                $obs_precip[] = "" . round($d[6], 2) . " in.";
                $obs_precip_accum[] = "" . round(array_sum($obs_precip), 2) . " in.";
                $obs_date[] = date("m/d @ H\z", $ob_time2);
                $oHourLast = $oHour;
            }
        }
    }

    //echo "".$ob_station."\n";
    //die();

    //start of NWS fetching

    function file_curl($url)
    {
        $ch = curl_init();
        $timeout = 5;
        curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
        $data = curl_exec($ch);
        curl_close($ch);
        $array = explode("\n", $data);
        return $array;
    }

    $init_year = date('Y', $min);
    $init_mon = date('m', $min);
    $init_day = date('d', $min);
    $init_h = date('H', $min);
    $end_year = date('Y', $max);
    $end_mon = date('m', $max);
    $end_day = date('d', $max);
    $end_h = date('H', $max);

    $init_time =  "" . $init_year . "-" . $init_mon . "-" . $init_day . "T" . $init_h . "";
    $end_time =  "" . $end_year . "-" . $end_mon . "-" . $end_day . "T" . $end_h . "";

    $link4_1 = "http://preview.weather.gov/xml/SOAP_server/ndfdXMLclient.php?whichClient=NDFDgen&lat=" . $lat . "&lon=" . $lon . "&listLatLon=&lat1=&lon1=&lat2=&lon2=&resolutionSub=&listLat1=&listLon1=";
    $link4_2 = "&listLat2=&listLon2=&resolutionList=&endPoint1Lat=&endPoint1Lon=&endPoint2Lat=&endPoint2Lon=&listEndPoint1Lat=&listEndPoint1Lon=&listEndPoint2Lat=&listEndPoint2Lon=&zipCodeList=";
    $link4_3 = "&listZipCodeList=&centerPointLat=&centerPointLon=&distanceLat=&distanceLon=&resolutionSquare=&listCenterPointLat=&listCenterPointLon=&listDistanceLat=&listDistanceLon=";
    $link4_4 = "&listResolutionSquare=&citiesLevel=&listCitiesLevel=&sector=&gmlListLatLon=&featureType=&requestedTime=&startTime=&endTime=&compType=&propertyName=";
    $link4_5 = "&product=time-series&begin=" . $init_time . "%3A00%3A00&end=" . $end_time . "%3A00%3A00&temp=temp&qpf=qpf&dew=dew&wspd=wspd&wdir=wdir&Submit=Submit";
    $link4 = "" . $link4_1 . "" . $link4_2 . "" . $link4_3 . "" . $link4_4 . "" . $link4_5 . "";
    //echo $link4;
    //die();

    $nws_start_time_1 = "start-valid-time";
    $nws_end_time_1 = "/time-layout";
    $nws_start_time_2 = "end-valid-time";
    $nws_end_time_2 = "/time-layout";
    $nws_wind_dir_start = "<name>Wind Direction</name>";
    $nws_wind_dir_end = "</direction>";
    $nws_wind_spd_start = "<name>Wind Speed</name>";
    $nws_wind_spd_end = "</wind-speed>";
    $nws_temp_start = "<name>Temperature</name>";
    $nws_temp_end = "</temperature>";
    $nws_dpt_start = "<name>Dew Point Temperature</name>";
    $nws_dpt_end = "</temperature>";
    $nws_precip_start = "<name>Liquid Precipitation Amount</name>";
    $nws_precip_end = "</precipitation>";

    $nws_int = 0;
    $trip1 = 1;
    $trip2 = 0;
    $precip_trip = 0;
    $temp_trip = 0;
    $dpt_trip = 0;
    $wind_spd_trip = 0;
    $wind_dir_trip = 0;
    $q = -1;
    $lf = -1;
    $m = -1;
    $p = -1;
    $tn = -1;
    $d = -1;
    $w = -1;
    $value = "value";

    $nws_time_1 = array();
    $nws_date = array();
    $nws_precip = array();
    $nws_sum = array();
    $nws_temp = array();
    $nws_dpt = array();
    $nws_wind_spd = array();
    $nws_wind_dir = array();

    $data = file_curl($link4);
    foreach ($data as $line) {
        preg_match_all(".$nws_start_time_1.", $line, $id1);
        $check1 = @$id1[0][0];

        preg_match_all(".$nws_end_time_1.", $line, $id2);
        $check2 = @$id2[0][0];

        preg_match_all(".$nws_start_time_2.", $line, $id3);
        $check3 = @$id3[0][0];

        preg_match_all(".$nws_end_time_2.", $line, $id4);
        $check4 = @$id4[0][0];

        preg_match_all(".$nws_precip_start.", $line, $id5);
        $check5 = @$id5[0][0];

        preg_match_all(".$nws_precip_end.", $line, $id6);
        $check6 = @$id6[0][0];

        preg_match_all(".$nws_temp_start.", $line, $id7);
        $check7 = @$id7[0][0];

        preg_match_all(".$nws_temp_end.", $line, $id8);
        $check8 = @$id8[0][0];

        preg_match_all(".$nws_dpt_start.", $line, $id9);
        $check9 = @$id9[0][0];

        preg_match_all(".$nws_dpt_end.", $line, $id10);
        $check10 = @$id10[0][0];

        preg_match_all(".$nws_wind_spd_start.", $line, $id11);
        $check11 = @$id11[0][0];

        preg_match_all(".$nws_wind_spd_end.", $line, $id12);
        $check12 = @$id12[0][0];

        preg_match_all(".$nws_wind_dir_start.", $line, $id13);
        $check13 = @$id13[0][0];

        preg_match_all(".$nws_wind_dir_end.", $line, $id14);
        $check14 = @$id14[0][0];

        preg_match_all(".$value.", $line, $id15);
        $check15 = @$id15[0][0];

        if ($check2 == $nws_end_time_1) {
            $trip1 = 0;
        }

        //get nws precip time
        if ($check4 == $nws_end_time_2) {
            $trip2 = $trip2 + 1;
        }
        if ($check3 == $nws_start_time_2 && $trip2 == 1) {
            $q++;
            $get_t_1 = explode(">", trim($line));
            $get_t_2 = explode("-", trim($get_t_1[1]));
            $t_array = array($get_t_2[0], $get_t_2[1], $get_t_2[2]);
            $get_t = implode("-", $t_array);
            $nws_time_2[$q] = strtotime($get_t) + 21600;
        }

        //get nws precip
        if ($check5 == $nws_precip_start) {
            $precip_trip = 1;
        }

        if ($check6 == $nws_precip_end) {
            $precip_trip = 0;
        }
        if ($check15 == $value && $precip_trip == 1) {
            $p++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_precip[$p] = "" . $get_nws_t2[0] . " in.";
            $nws_precip2[$p] = $get_nws_t2[0];
            $add_nws_precip[$p] = array_sum($nws_precip2);
            $nws_sum[$p] = "" . $add_nws_precip[$p] . " in.";
            $p++;
            $nws_precip[$p] = "" . $get_nws_t2[0] . " in.";
            $nws_sum[$p] = "" . $add_nws_precip[$p - 1] . " in.";
        }


        //get nws time 1
        if ($check1 == $nws_start_time_1 && $trip1 == 1) {
            $lf++;
            $get_t_1 = explode(">", trim($line));
            $get_t_2 = explode("<", trim($get_t_1[1]));
            $get_t = $get_t_2[0];
            $nws_time_1[$lf] = strtotime($get_t);
            if ((@$nws_time_1[$lf] - @$nws_time_1[$lf - 1]) == 10800) {
                $nws_int++;
            }
            $nws_mon = date('m', $nws_time_1[$lf]);
            $nws_day = date('d', $nws_time_1[$lf]);
            $nws_hr = date('H', $nws_time_1[$lf]);
            $nws_date[$lf] = "" . $nws_mon . "/" . $nws_day . " @ " . $nws_hr . "z";
            $nws_precip[$lf] = "-";
            $nws_sum[$lf] = "-";
        }

        //get nws temp
        if ($check7 == $nws_temp_start) {
            $temp_trip = 1;
        }
        if ($check8 == $nws_temp_end) {
            $temp_trip = 0;
        }
        if ($check15 == $value && $temp_trip == 1) {
            $tn++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_temp[$tn] = "" . $get_nws_t2[0] . " F";
        }

        //get nws dewpoint  
        if ($check9 == $nws_dpt_start) {
            $dpt_trip = 1;
        }
        if ($check10 == $nws_dpt_end) {
            $dpt_trip = 0;
        }
        if ($check15 == $value && $dpt_trip == 1) {
            $d++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_dpt[$d] = "" . $get_nws_t2[0] . " F";
        }

        //get nws wind speed
        if ($check11 == $nws_wind_spd_start) {
            $wind_spd_trip = 1;
        }
        if ($check12 == $nws_wind_spd_end) {
            $wind_spd_trip = 0;
        }
        if ($check15 == $value && $wind_spd_trip == 1) {
            $w++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_wind_spd[$w] = "" . $get_nws_t2[0] . " mph";
        }

        //get nws wind direction
        if ($check13 == $nws_wind_dir_start) {
            $wind_dir_trip = 1;
        }
        if ($check14 == $nws_wind_dir_end) {
            $wind_dir_trip = 0;
        }
        if ($check15 == $value && $wind_dir_trip == 1) {
            $m++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_wind_dir[$m] = get_wind_dir($get_nws_t2[0]);
        }
    }

    //start of MOS fetching
    // MOS data
    for ($z = 0; $z <= 2; $z++) {
        if ($z == 0) {
            $mos_year = @date('Y', $nam_time[0]);
            $mos_mon = @date('m', $nam_time[0]);
            $mos_day = @date('d', $nam_time[0]);
            $mos_h = @date('H', $nam_time[0]);
            $nam_mos_temp = array();
            $nam_mos_dew = array();
            $nam_mos_wspd = array();
            $nam_mos_wdir = array();
            $nam_mos_precip = array();
            $nam_mos_temp = array();
            $nam_mos_snow = array();
            $nam_mos_snow_accum = array();
            $nam_mos_time = array();
            $nam_mos_hiwc = array();
            $nam_mos_wind_x = array();
            $nam_mos_wind_y = array();
            $nam_mos_wind_dir = array();
            $nam_mos_date = array();
            $mos_time = "" . $mos_year . "-" . $mos_mon . "-" . $mos_day . "%20" . $mos_h . ":00";
            $link = "http://mesonet.agron.iastate.edu/mos/csv.php?station=" . $ob_station . "&runtime=" . $mos_time . "&model=NAM";
        } elseif ($z == 1) {
            $mos_year = @date('Y', $gfs_time[0]);
            $mos_mon = @date('m', $gfs_time[0]);
            $mos_day = @date('d', $gfs_time[0]);
            $mos_h = @date('H', $gfs_time[0]);
            $gfs_mos_temp = array();
            $gfs_mos_dew = array();
            $gfs_mos_wspd = array();
            $gfs_mos_wdir = array();
            $gfs_mos_precip = array();
            $gfs_mos_temp = array();
            $gfs_mos_snow = array();
            $gfs_mos_snow_accum = array();
            $gfs_mos_time = array();
            $gfs_mos_hiwc = array();
            $gfs_mos_wind_x = array();
            $gfs_mos_wind_y = array();
            $gfs_mos_wind_dir = array();
            $gfs_mos_date = array();
            $mos_time = "" . $mos_year . "-" . $mos_mon . "-" . $mos_day . "%20" . $mos_h . ":00";
            $link = "http://mesonet.agron.iastate.edu/mos/csv.php?station=" . $ob_station . "&runtime=" . $mos_time . "&model=GFS";
        } elseif ($z == 2) {
            $mos_year = @date('Y', $gfsm_time[0]);
            $mos_mon = @date('m', $gfsm_time[0]);
            $mos_day = @date('d', $gfsm_time[0]);
            $mos_h = @date('H', $gfsm_time[0]);
            $gfsm_mos_temp = array();
            $gfsm_mos_dew = array();
            $gfsm_mos_wspd = array();
            $gfsm_mos_wdir = array();
            $gfsm_mos_precip = array();
            $gfsm_mos_temp = array();
            $gfsm_mos_snow = array();
            $gfsm_mos_snow_accum = array();
            $gfsm_mos_time = array();
            $gfsm_mos_hiwc = array();
            $gfsm_mos_wind_x = array();
            $gfsm_mos_wind_y = array();
            $gfsm_mos_wind_dir = array();
            $gfsm_mos_date = array();
            $mos_time = "" . $mos_year . "-" . $mos_mon . "-" . $mos_day . "%20" . $mos_h . ":00";
            $link = "http://mesonet.agron.iastate.edu/mos/csv.php?station=" . $ob_station . "&runtime=" . $mos_time . "&model=GFS";
        }
        $k = -1;
        $data = file($link);
        foreach ($data as $line) {
            $k++;
            $d = explode(",", trim($line));
            if ($k >= 1) {
                if ($z == 0 && $nam_mos_check == 1) {
                    $nam_mos_time[] = strtotime($d[3]);
                    $nam_mos_date[] = date("m/d @ H\z", strtotime($d[3]));
                    $nam_mos_temp[] = "" . $d[5] . " F";
                    $nam_mos_dew[] = "" . $d[6] . " F";
                    $nam_mos_wdir[] = $d[8];
                    $nam_mos_wspd[] = "" . round($d[9] * 1.15077945, 0) . " mph";
                    $nam_mos_snow[] = $d[16];
                    $nam_mos_qpf[] = $d[12];
                    $nam_mos_wind_x[] = cos(deg2rad(270 - $d[8])) * ($d[9] * 0.514444444);
                    $nam_mos_wind_y[] = sin(deg2rad(270 - $d[8])) * ($d[9] * 0.514444444);
                    $nam_mos_wind_dir[] = get_wind_dir($d[8]);
                    $nam_mos_snow_accum[] = array_sum($nam_mos_snow);
                    $nam_mos_qpf_accum[] = array_sum($nam_mos_qpf);
                    $temp_c = ($d[5] - 32) * (5 / 9);
                    $dpt_c = ($d[6] - 32) * (5 / 9);
                    $rh = 100 * (exp(((1 / ($dpt_c + 273.15)) - (1 / ($temp_c + 273.15))) / (-461.495 / 2500000)));
                    if ($d[5] >= 80 && $dpt_c >= 12) {
                        $nam_mos_hiwc[] = -42.379 + (2.04901523 * $d[5]) + (10.14333127 * $rh) + (-0.22475541 * $d[5] * $rh) + (-0.00683783 * $d[5] * $d[5]) + (-0.05481717 * $rh * $rh) + (0.00122874 * $d[5] * $d[5] * $rh) + (0.00085282 * $d[5] * $rh * $rh) + (-0.00000199 * $d[5] * $d[5] * $rh * $rh);
                    } elseif ($d[5] > 50 || $d[9] == 0) {
                        $nam_mos_hiwc[] = $d[5];
                    } else {
                        $nam_mos_hiwc[] = 35.74 + (0.6215 * $d[5]) - (35.75 * pow($d[9], 0.16)) + ((0.4275 * $d[5]) * pow($d[9], 0.16));
                    }
                } elseif ($z == 1 && $gfs_mos_check == 1) {
                    $gfs_mos_time[] = strtotime($d[3]);
                    $gfs_mos_date[] = date("m/d @ H\z", strtotime($d[3]));
                    $gfs_mos_temp[] = "" . $d[5] . " F";
                    $gfs_mos_dew[] = "" . $d[6] . " F";
                    $gfs_mos_wdir[] = $d[8];
                    $gfs_mos_wspd[] = "" . round($d[9] * 1.15077945, 0) . " mph";
                    $gfs_mos_snow[] = $d[16];
                    $gfs_mos_qpf[] = $d[12];
                    $gfs_mos_wind_x[] = cos(deg2rad(270 - $d[8])) * ($d[9] * 0.514444444);
                    $gfs_mos_wind_y[] = sin(deg2rad(270 - $d[8])) * ($d[9] * 0.514444444);
                    $gfs_mos_wind_dir[] = get_wind_dir($d[8]);
                    $gfs_mos_snow_accum[] = array_sum($gfs_mos_snow);
                    $gfs_mos_qpf_accum[] = array_sum($gfs_mos_qpf);
                    $temp_c = ($d[5] - 32) * (5 / 9);
                    $dpt_c = ($d[6] - 32) * (5 / 9);
                    $rh = 100 * (exp(((1 / ($dpt_c + 273.15)) - (1 / ($temp_c + 273.15))) / (-461.495 / 2500000)));
                    if ($d[5] >= 80 && $dpt_c >= 12) {
                        $gfs_mos_hiwc[] = -42.379 + (2.04901523 * $d[5]) + (10.14333127 * $rh) + (-0.22475541 * $d[5] * $rh) + (-0.00683783 * $d[5] * $d[5]) + (-0.05481717 * $rh * $rh) + (0.00122874 * $d[5] * $d[5] * $rh) + (0.00085282 * $d[5] * $rh * $rh) + (-0.00000199 * $d[5] * $d[5] * $rh * $rh);
                    } elseif ($d[5] > 50 || $d[9] == 0) {
                        $gfs_mos_hiwc[] = $d[5];
                    } else {
                        $gfs_mos_hiwc[] = 35.74 + (0.6215 * $d[5]) - (35.75 * pow($d[9], 0.16)) + ((0.4275 * $d[5]) * pow($d[9], 0.16));
                    }
                } elseif ($z == 2 && $gfsm_mos_check == 1) {
                    $gfsm_mos_time[] = strtotime($d[3]);
                    $gfsm_mos_date[] = date("m/d @ H\z", strtotime($d[3]));
                    $gfsm_mos_temp[] = "" . $d[5] . " F";
                    $gfsm_mos_dew[] = "" . $d[6] . " F";
                    $gfsm_mos_wdir[] = $d[8];
                    $gfsm_mos_wspd[] = "" . round($d[9] * 1.15077945, 0) . " mph";
                    $gfsm_mos_snow[] = $d[16];
                    $gfsm_mos_qpf[] = $d[12];
                    $gfsm_mos_wind_x[] = cos(deg2rad(270 - $d[8])) * ($d[9] * 0.514444444);
                    $gfsm_mos_wind_y[] = sin(deg2rad(270 - $d[8])) * ($d[9] * 0.514444444);
                    $gfsm_mos_wind_dir[] = get_wind_dir($d[8]);
                    $gfsm_mos_snow_accum[] = array_sum($gfsm_mos_snow);
                    $gfsm_mos_qpf_accum[] = array_sum($gfsm_mos_qpf);
                    $temp_c = ($d[5] - 32) * (5 / 9);
                    $dpt_c = ($d[6] - 32) * (5 / 9);
                    $rh = 100 * (exp(((1 / ($dpt_c + 273.15)) - (1 / ($temp_c + 273.15))) / (-461.495 / 2500000)));
                    if ($d[5] >= 80 && $dpt_c >= 12) {
                        $gfsm_mos_hiwc[] = -42.379 + (2.04901523 * $d[5]) + (10.14333127 * $rh) + (-0.22475541 * $d[5] * $rh) + (-0.00683783 * $d[5] * $d[5]) + (-0.05481717 * $rh * $rh) + (0.00122874 * $d[5] * $d[5] * $rh) + (0.00085282 * $d[5] * $rh * $rh) + (-0.00000199 * $d[5] * $d[5] * $rh * $rh);
                    } elseif ($d[5] > 50 || $d[9] == 0) {
                        $gfsm_mos_hiwc[] = $d[5];
                    } else {
                        $gfsm_mos_hiwc[] = 35.74 + (0.6215 * $d[5]) - (35.75 * pow($d[9], 0.16)) + ((0.4275 * $d[5]) * pow($d[9], 0.16));
                    }
                }
            }
        }
    }

    //echo "".$link."\n";
    //print_r($gfs_mos_date);
    //print_r($gfs_mos_temp);
    //die();

    //3-hourly model consensus
    $con_temp = array();
    $con_dew = array();
    $con_ws = array();
    $con_p = array();
    $con_pa = array();
    $con_wd = array();
    $consensus_t = array();
    for ($i = $min; $i <= $max; $i = $i + 10800) {
        $total_temp = 0;
        $total_dew = 0;
        $total_ws = 0;
        $total_wd = 0;
        $total_wd_x = 0;
        $total_wd_y = 0;
        $total_p = 0;
        $total_pa = 0;
        $n = 0;
        if (in_array($i, $nam_time)) {
            $n++;
            $index = array_search($i, $nam_time);
            @$total_p = $total_p + $nam_var1[$index];
            @$total_pa = $total_pa + $nam_var2[$index];
            @$total_temp = $total_temp + $nam_var3[$index];
            @$total_dew = $total_dew + $nam_var4[$index];
            @$total_ws = $total_ws + $nam_var5[$index];
            $total_wd_x = $total_wd_x + $nam_wind_x[$index];
            $total_wd_y = $total_wd_y + $nam_wind_y[$index];
        }
        if (in_array($i, $namm_time)) {
            $n++;
            $index = array_search($i, $namm_time);
            @$total_p = $total_p + $namm_var1[$index];
            @$total_pa = $total_pa + $namm_var2[$index];
            @$total_temp = $total_temp + $namm_var3[$index];
            @$total_dew = $total_dew + $namm_var4[$index];
            @$total_ws = $total_ws + $namm_var5[$index];
            $total_wd_x = $total_wd_x + $namm_wind_x[$index];
            $total_wd_y = $total_wd_y + $namm_wind_y[$index];
        }
        if (in_array($i, $gfs_time)) {
            $n++;
            $index = array_search($i, $gfs_time);
            @$total_p = $total_p + $gfs_var1[$index];
            @$total_pa = $total_pa + $gfs_var2[$index];
            @$total_temp = $total_temp + $gfs_var3[$index];
            @$total_dew = $total_dew + $gfs_var4[$index];
            @$total_ws = $total_ws + $gfs_var5[$index];
            $total_wd_x = $total_wd_x + $gfs_wind_x[$index];
            $total_wd_y = $total_wd_y + $gfs_wind_y[$index];
        }
        if (in_array($i, $gfsm_time)) {
            $n++;
            $index = array_search($i, $gfsm_time);
            @$total_p = $total_p + $gfsm_var1[$index];
            @$total_pa = $total_pa + $gfsm_var2[$index];
            @$total_temp = $total_temp + $gfsm_var3[$index];
            @$total_dew = $total_dew + $gfsm_var4[$index];
            @$total_ws = $total_ws + $gfsm_var5[$index];
            $total_wd_x = $total_wd_x + $gfsm_wind_x[$index];
            $total_wd_y = $total_wd_y + $gfsm_wind_y[$index];
        }
        if (in_array($i, $rap_time)) {
            $n++;
            $index = array_search($i, $rap_time);
            @$total_p = $total_p + $rap_var1[$index];
            @$total_pa = $total_pa + $rap_var2[$index];
            @$total_temp = $total_temp + $rap_var3[$index];
            @$total_dew = $total_dew + $rap_var4[$index];
            @$total_ws = $total_ws + $rap_var5[$index];
            $total_wd_x = $total_wd_x + $rap_wind_x[$index];
            $total_wd_y = $total_wd_y + $rap_wind_y[$index];
        }
        if (in_array($i, $nam4km_time)) {
            $n++;
            $index = array_search($i, $nam4km_time);
            @$total_p = $total_p + $nam4km_var1[$index];
            @$total_pa = $total_pa + $nam4km_var2[$index];
            @$total_temp = $total_temp + $nam4km_var3[$index];
            @$total_dew = $total_dew + $nam4km_var4[$index];
            @$total_ws = $total_ws + $nam4km_var5[$index];
            $total_wd_x = $total_wd_x + $nam4km_wind_x[$index];
            $total_wd_y = $total_wd_y + $nam4km_wind_y[$index];
        }
        if (in_array($i, $gfs_mos_time)) {
            $n++;
            $index = array_search($i, $gfs_mos_time);
            @$total_temp = $total_temp + $gfs_mos_temp[$index];
            @$total_dew = $total_dew + $gfs_mos_dew[$index];
            @$total_ws = $total_ws + $gfs_mos_wspd[$index];
            $total_wd_x = $total_wd_x + $gfs_mos_wind_x[$index];
            $total_wd_y = $total_wd_y + $gfs_mos_wind_y[$index];
        }
        if (in_array($i, $gfsm_mos_time)) {
            $n++;
            $index = array_search($i, $gfsm_mos_time);
            @$total_temp = $total_temp + $gfsm_mos_temp[$index];
            @$total_dew = $total_dew + $gfsm_mos_dew[$index];
            @$total_ws = $total_ws +    $gfsm_mos_wspd[$index];
            $total_wd_x = $total_wd_x + $gfsm_mos_wind_x[$index];
            $total_wd_y = $total_wd_y + $gfsm_mos_wind_y[$index];
        }
        if (in_array($i, $nam_mos_time)) {
            $n++;
            $index = array_search($i, $nam_mos_time);
            @$total_temp = $total_temp + $nam_mos_temp[$index];
            @$total_dew = $total_dew + $nam_mos_dew[$index];
            @$total_ws = $total_ws + $nam_mos_wspd[$index];
            $total_wd_x = $total_wd_x + $nam_mos_wind_x[$index];
            $total_wd_y = $total_wd_y + $nam_mos_wind_y[$index];
        }

        if ($n > 1) {
            $con_temp[] = round($total_temp / $n, 0);
            $con_dew[] = round($total_dew / $n, 0);
            $con_ws[] = round($total_ws / $n, 0);
            $con_p[] = round($total_p / $n, 2);
            $con_pa[] = round($total_pa / $n, 2);
            $total_wind_x = $total_wd_x / $n;
            $total_wind_y = $total_wd_y / $n;
            $wind_dir = @rad2deg(atan($total_wind_y / $total_wind_x));
            if ($total_wind_x < 0 && $total_wind_y > 0) {
                $wind_dir = $wind_dir + 180;
            }
            if ($total_wind_x == 0 && $total_wind_y > 0) {
                $wind_dir = $wind_dir + 90;
            } elseif ($total_wind_x < 0 && $total_wind_y <= 0) {
                $wind_dir = $wind_dir + 180;
            }
            $con_wd[] = get_wind_dir(($wind_dir * (-1)) + 270);
            $consensus_t[] = $i;
            $con_date[] = date("m/d @ H\z", $i);
        }
    }

    //print_r($consensus_t);
    //die();
    ?>


    <map id="precip" name="precip">
        <form>

            <?php

            $string_nam1 = "";
            $string_nam2 = "";
            $string_nam3 = "";
            $string_nam4 = "";
            $string_nam5 = "";
            $string_nam6 = "";
            $string_nam7 = "";
            $string_nam8 = "";
            $string_namm1 = "";
            $string_namm2 = "";
            $string_namm3 = "";
            $string_namm4 = "";
            $string_namm5 = "";
            $string_namm6 = "";
            $string_namm7 = "";
            $string_namm8 = "";
            $string_gfs1 = "";
            $string_gfs2 = "";
            $string_gfs3 = "";
            $string_gfs4 = "";
            $string_gfs5 = "";
            $string_gfs6 = "";
            $string_gfs7 = "";
            $string_gfs8 = "";
            $string_gfsm1 = "";
            $string_gfsm2 = "";
            $string_gfsm3 = "";
            $string_gfsm4 = "";
            $string_gfsm5 = "";
            $string_gfsm6 = "";
            $string_gfsm7 = "";
            $string_gfsm8 = "";
            $string_rap1 = "";
            $string_rap2 = "";
            $string_rap3 = "";
            $string_rap4 = "";
            $string_rap5 = "";
            $string_rap6 = "";
            $string_rap7 = "";
            $string_rap8 = "";
            $string_nam4km1 = "";
            $string_nam4km2 = "";
            $string_nam4km3 = "";
            $string_nam4km4 = "";
            $string_nam4km5 = "";
            $string_nam4km6 = "";
            $string_nam4km7 = "";
            $string_nam4km8 = "";
            $string_nam_mos1 = "";
            $string_nam_mos2 = "";
            $string_nam_mos3 = "";
            $string_nam_mos4 = "";
            $string_nam_mos5 = "";
            $string_nam_mos6 = "";
            $string_nam_mos7 = "";
            $string_nam_mos8 = "";
            $string_gfs_mos1 = "";
            $string_gfs_mos2 = "";
            $string_gfs_mos3 = "";
            $string_gfs_mos4 = "";
            $string_gfs_mos5 = "";
            $string_gfs_mos6 = "";
            $string_gfs_mos7 = "";
            $string_gfs_mos8 = "";
            $string_gfsm_mos1 = "";
            $string_gfsm_mos2 = "";
            $string_gfsm_mos3 = "";
            $string_gfsm_mos4 = "";
            $string_gfsm_mos5 = "";
            $string_gfsm_mos6 = "";
            $string_gfsm_mos7 = "";
            $string_gfsm_mos8 = "";
            $string_con1 = "";
            $string_con2 = "";
            $string_con3 = "";
            $string_con4 = "";
            $string_con5 = "";
            $string_con6 = "";
            $string_con7 = "";
            $string_con8 = "";
            $string_nws1 = "";
            $string_nws2 = "";
            $string_nws3 = "";
            $string_nws4 = "";
            $string_nws5 = "";
            $string_nws6 = "";
            $string_nws7 = "";
            $string_nws8 = "";
            $string_obs1 = "";
            $string_obs2 = "";
            $string_obs3 = "";
            $string_obs4 = "";
            $string_obs5 = "";
            $string_obs6 = "";
            $string_obs7 = "";
            $string_obs8 = "";

            $ul = 61;
            $ur = 41;
            $lr = 64;
            $ll = 359;
            $ul1 = $ul;
            $lr1 = $lr;

            $model_count = ($max - $min) / 3600;
            $index = "";
            //echo "".$min.",".$max.",".$diff."\n";
            //die();

            for ($i = $min; $i <= $max; $i = $i + 3600) {
                if ($nam_check == 1) {
                    if (in_array($i, $nam_time)) {
                        $index = array_search($i, $nam_time);
                        $string_nam1 = "<td width=83 align=center><font color=000000>" . $nam_init . "z NAM</font></td>";
                        $string_nam2 = "<td width=83 align=center><font color=000000>" . $nam_date[$index] . "</font></td>";
                        $string_nam3 = "<td width=83 align=center><font color=0000FF>" . $nam_var1[$index] . "</font></td>";
                        $string_nam4 = "<td width=83 align=center><font color=000099>" . $nam_var2[$index] . "</font></td>";
                        $string_nam5 = "<td width=83 align=center><font color=CC0000>" . $nam_var3[$index] . "</font></td>";
                        $string_nam6 = "<td width=83 align=center><font color=006600>" . $nam_var4[$index] . "</font></td>";
                        $string_nam7 = "<td width=83 align=center><font color=000000>" . $nam_var5[$index] . "</font></td>";
                        $string_nam8 = "<td width=83 align=center><font color=000000>" . $nam_var6[$index] . "</font></td>";
                    } elseif (!empty($nam_time) && $i < min($nam_time) || !empty($nam_time) && $i > max($nam_time)) {
                        $string_nam1 = "<td width=83 align=center><font color=000000>" . $nam_init . "z NAM</font></td>";
                        $string_nam2 = "<td width=83 align=center></td>";
                        $string_nam3 = "<td width=83 align=center></td>";
                        $string_nam4 = "<td width=83 align=center></td>";
                        $string_nam5 = "<td width=83 align=center></td>";
                        $string_nam6 = "<td width=83 align=center></td>";
                        $string_nam7 = "<td width=83 align=center></td>";
                        $string_nam8 = "<td width=83 align=center></td>";
                    }
                }
                if ($namm_check == 1) {
                    if (in_array($i, $namm_time)) {
                        $index = array_search($i, $namm_time);
                        $string_namm1 = "<td width=83 align=center><font color=000000>" . $namm_init . "z NAM</font></td>";
                        $string_namm2 = "<td width=83 align=center><font color=000000>" . $namm_date[$index] . "</font></td>";
                        $string_namm3 = "<td width=83 align=center><font color=0000FF>" . $namm_var1[$index] . "</font></td>";
                        $string_namm4 = "<td width=83 align=center><font color=000099>" . $namm_var2[$index] . "</font></td>";
                        $string_namm5 = "<td width=83 align=center><font color=CC0000>" . $namm_var3[$index] . "</font></td>";
                        $string_namm6 = "<td width=83 align=center><font color=006600>" . $namm_var4[$index] . "</font></td>";
                        $string_namm7 = "<td width=83 align=center><font color=000000>" . $namm_var5[$index] . "</font></td>";
                        $string_namm8 = "<td width=83 align=center><font color=000000>" . $namm_var6[$index] . "</font></td>";
                    } elseif (!empty($namm_time) && $i < min($namm_time) || !empty($namm_time) && $i > max($namm_time)) {
                        $string_namm1 = "<td width=83 align=center><font color=000000>" . $namm_init . "z NAM</font></td>";
                        $string_namm2 = "<td width=83 align=center></td>";
                        $string_namm3 = "<td width=83 align=center></td>";
                        $string_namm4 = "<td width=83 align=center></td>";
                        $string_namm5 = "<td width=83 align=center></td>";
                        $string_namm6 = "<td width=83 align=center></td>";
                        $string_namm7 = "<td width=83 align=center></td>";
                        $string_namm8 = "<td width=83 align=center></td>";
                    }
                }
                if ($gfs_check == 1) {
                    if (in_array($i, $gfs_time)) {
                        $index = array_search($i, $gfs_time);
                        $string_gfs1 = "<td width=83 align=center><font color=000000>" . $gfs_init . "z GFS</font></td>";
                        $string_gfs2 = "<td width=83 align=center><font color=000000>" . $gfs_date[$index] . "</font></td>";
                        $string_gfs3 = "<td width=83 align=center><font color=0000FF>" . $gfs_var1[$index] . "</font></td>";
                        $string_gfs4 = "<td width=83 align=center><font color=000099>" . $gfs_var2[$index] . "</font></td>";
                        $string_gfs5 = "<td width=83 align=center><font color=CC0000>" . $gfs_var3[$index] . "</font></td>";
                        $string_gfs6 = "<td width=83 align=center><font color=006600>" . $gfs_var4[$index] . "</font></td>";
                        $string_gfs7 = "<td width=83 align=center><font color=000000>" . $gfs_var5[$index] . "</font></td>";
                        $string_gfs8 = "<td width=83 align=center><font color=000000>" . $gfs_var6[$index] . "</font></td>";
                    } elseif (!empty($gfs_time) && $i < min($gfs_time) || !empty($gfs_time) && $i > max($gfs_time)) {
                        $string_gfs1 = "<td width=83 align=center><font color=000000>" . $gfs_init . "z GFS</font></td>";
                        $string_gfs2 = "<td width=83 align=center></td>";
                        $string_gfs3 = "<td width=83 align=center></td>";
                        $string_gfs4 = "<td width=83 align=center></td>";
                        $string_gfs5 = "<td width=83 align=center></td>";
                        $string_gfs6 = "<td width=83 align=center></td>";
                        $string_gfs7 = "<td width=83 align=center></td>";
                        $string_gfs8 = "<td width=83 align=center></td>";
                    }
                }
                if ($gfsm_check == 1) {
                    if (in_array($i, $gfsm_time)) {
                        $index = array_search($i, $gfsm_time);
                        $string_gfsm1 = "<td width=83 align=center><font color=000000>" . $gfsm_init . "z GFS</font></td>";
                        $string_gfsm2 = "<td width=83 align=center><font color=000000>" . $gfsm_date[$index] . "</font></td>";
                        $string_gfsm3 = "<td width=83 align=center><font color=0000FF>" . $gfsm_var1[$index] . "</font></td>";
                        $string_gfsm4 = "<td width=83 align=center><font color=000099>" . $gfsm_var2[$index] . "</font></td>";
                        $string_gfsm5 = "<td width=83 align=center><font color=CC0000>" . $gfsm_var3[$index] . "</font></td>";
                        $string_gfsm6 = "<td width=83 align=center><font color=006600>" . $gfsm_var4[$index] . "</font></td>";
                        $string_gfsm7 = "<td width=83 align=center><font color=000000>" . $gfsm_var5[$index] . "</font></td>";
                        $string_gfsm8 = "<td width=83 align=center><font color=000000>" . $gfsm_var6[$index] . "</font></td>";
                    } elseif (!empty($gfsm_time) && $i < min($gfsm_time) || !empty($gfsm_time) && $i > max($gfsm_time)) {
                        $string_gfsm1 = "<td width=83 align=center><font color=000000>" . $gfsm_init . "z GFS</font></td>";
                        $string_gfsm2 = "<td width=83 align=center></td>";
                        $string_gfsm3 = "<td width=83 align=center></td>";
                        $string_gfsm4 = "<td width=83 align=center></td>";
                        $string_gfsm5 = "<td width=83 align=center></td>";
                        $string_gfsm6 = "<td width=83 align=center></td>";
                        $string_gfsm7 = "<td width=83 align=center></td>";
                        $string_gfsm8 = "<td width=83 align=center></td>";
                    }
                }
                if ($rap_check == 1) {
                    if (in_array($i, $rap_time)) {
                        $index = array_search($i, $rap_time);
                        if ($date >= 2012050100) {
                            $string_rap1 = "<td width=83 align=center><font color=000000>" . $rap_init . "z RAP</font></td>";
                        } else {
                            $string_rap1 = "<td width=83 align=center><font color=000000>" . $rap_init . "z RUC</font></td>";
                        }
                        $string_rap2 = "<td width=83 align=center><font color=000000>" . $rap_date[$index] . "</font></td>";
                        $string_rap3 = "<td width=83 align=center><font color=0000FF>" . $rap_var1[$index] . "</font></td>";
                        $string_rap4 = "<td width=83 align=center><font color=000099>" . $rap_var2[$index] . "</font></td>";
                        $string_rap5 = "<td width=83 align=center><font color=CC0000>" . $rap_var3[$index] . "</font></td>";
                        $string_rap6 = "<td width=83 align=center><font color=006600>" . $rap_var4[$index] . "</font></td>";
                        $string_rap7 = "<td width=83 align=center><font color=000000>" . $rap_var5[$index] . "</font></td>";
                        $string_rap8 = "<td width=83 align=center><font color=000000>" . $rap_var6[$index] . "</font></td>";
                    } elseif (!empty($rap_time) && $i < min($rap_time) || !empty($rap_time) && $i > max($rap_time)) {
                        if ($date >= 2012050100) {
                            $string_rap1 = "<td width=83 align=center><font color=000000>" . $rap_init . "z RAP</font></td>";
                        } else {
                            $string_rap1 = "<td width=83 align=center><font color=000000>" . $rap_init . "z RUC</font></td>";
                        }
                        $string_rap2 = "<td width=83 align=center></td>";
                        $string_rap3 = "<td width=83 align=center></td>";
                        $string_rap4 = "<td width=83 align=center></td>";
                        $string_rap5 = "<td width=83 align=center></td>";
                        $string_rap6 = "<td width=83 align=center></td>";
                        $string_rap7 = "<td width=83 align=center></td>";
                        $string_rap8 = "<td width=83 align=center></td>";
                    }
                }
                if ($nam4km_check == 1) {
                    if (in_array($i, $nam4km_time)) {
                        $index = array_search($i, $nam4km_time);
                        $string_nam4km1 = "<td width=83 align=center><font color=000000>" . $nam4km_init . "z NAM 4km</font></td>";
                        $string_nam4km2 = "<td width=83 align=center><font color=000000>" . $nam4km_date[$index] . "</font></td>";
                        $string_nam4km3 = "<td width=83 align=center><font color=0000FF>" . $nam4km_var1[$index] . "</font></td>";
                        $string_nam4km4 = "<td width=83 align=center><font color=000099>" . $nam4km_var2[$index] . "</font></td>";
                        $string_nam4km5 = "<td width=83 align=center><font color=CC0000>" . $nam4km_var3[$index] . "</font></td>";
                        $string_nam4km6 = "<td width=83 align=center><font color=006600>" . $nam4km_var4[$index] . "</font></td>";
                        $string_nam4km7 = "<td width=83 align=center><font color=000000>" . $nam4km_var5[$index] . "</font></td>";
                        $string_nam4km8 = "<td width=83 align=center><font color=000000>" . $nam4km_var6[$index] . "</font></td>";
                    } elseif (!empty($nam4km_time) && $i < min($nam4km_time) || !empty($nam4km_time) && $i > max($nam4km_time)) {
                        $string_nam4km1 = "<td width=83 align=center><font color=000000>" . $nam4km_init . "z NAM 4km</font></td>";
                        $string_nam4km2 = "<td width=83 align=center></td>";
                        $string_nam4km3 = "<td width=83 align=center></td>";
                        $string_nam4km4 = "<td width=83 align=center></td>";
                        $string_nam4km5 = "<td width=83 align=center></td>";
                        $string_nam4km6 = "<td width=83 align=center></td>";
                        $string_nam4km7 = "<td width=83 align=center></td>";
                        $string_nam4km8 = "<td width=83 align=center></td>";
                    }
                }
                if ($nam_mos_check == 1) {
                    if (in_array($i, $nam_mos_time)) {
                        $index = array_search($i, $nam_mos_time);
                        $string_nam_mos1 = "<td width=83 align=center><font color=000000>" . $nam_init . "z NAM MOS</font></td>";
                        $string_nam_mos2 = "<td width=83 align=center><font color=000000>" . $nam_mos_date[$index] . "</font></td>";
                        $string_nam_mos3 = "<td width=83 align=center><font color=0000FF>-</font></td>";
                        $string_nam_mos4 = "<td width=83 align=center><font color=000099>-</font></td>";
                        $string_nam_mos5 = "<td width=83 align=center><font color=CC0000>" . $nam_mos_temp[$index] . "</font></td>";
                        $string_nam_mos6 = "<td width=83 align=center><font color=006600>" . $nam_mos_dew[$index] . "</font></td>";
                        $string_nam_mos7 = "<td width=83 align=center><font color=000000>" . $nam_mos_wspd[$index] . "</font></td>";
                        $string_nam_mos8 = "<td width=83 align=center><font color=000000>" . $nam_mos_wind_dir[$index] . "</font></td>";
                    } elseif (!empty($nam_mos_time) && $i < min($nam_mos_time) || !empty($nam_mos_time) && $i > max($nam_mos_time)) {
                        $string_nam_mos1 = "<td width=83 align=center><font color=000000>" . $nam_init . "z NAM MOS</font></td>";
                        $string_nam_mos2 = "<td width=83 align=center></td>";
                        $string_nam_mos3 = "<td width=83 align=center></td>";
                        $string_nam_mos4 = "<td width=83 align=center></td>";
                        $string_nam_mos5 = "<td width=83 align=center></td>";
                        $string_nam_mos6 = "<td width=83 align=center></td>";
                        $string_nam_mos7 = "<td width=83 align=center></td>";
                        $string_nam_mos8 = "<td width=83 align=center></td>";
                    }
                }
                if ($gfs_mos_check == 1) {
                    if (in_array($i, $gfs_mos_time)) {
                        $index = array_search($i, $gfs_mos_time);
                        $string_gfs_mos1 = "<td width=83 align=center><font color=000000>" . $gfs_init . "z GFS MOS</font></td>";
                        $string_gfs_mos2 = "<td width=83 align=center><font color=000000>" . $gfs_mos_date[$index] . "</font></td>";
                        $string_gfs_mos3 = "<td width=83 align=center><font color=0000FF>-</font></td>";
                        $string_gfs_mos4 = "<td width=83 align=center><font color=000099>-</font></td>";
                        $string_gfs_mos5 = "<td width=83 align=center><font color=CC0000>" . $gfs_mos_temp[$index] . "</font></td>";
                        $string_gfs_mos6 = "<td width=83 align=center><font color=006600>" . $gfs_mos_dew[$index] . "</font></td>";
                        $string_gfs_mos7 = "<td width=83 align=center><font color=000000>" . $gfs_mos_wspd[$index] . "</font></td>";
                        $string_gfs_mos8 = "<td width=83 align=center><font color=000000>" . $gfs_mos_wind_dir[$index] . "</font></td>";
                    } elseif (!empty($gfs_mos_time) && $i < min($gfs_mos_time) || !empty($gfs_mos_time) && $i > max($gfs_mos_time)) {
                        $string_gfs_mos1 = "<td width=83 align=center><font color=000000>" . $gfs_init . "z GFS MOS</font></td>";
                        $string_gfs_mos2 = "<td width=83 align=center></td>";
                        $string_gfs_mos3 = "<td width=83 align=center></td>";
                        $string_gfs_mos4 = "<td width=83 align=center></td>";
                        $string_gfs_mos5 = "<td width=83 align=center></td>";
                        $string_gfs_mos6 = "<td width=83 align=center></td>";
                        $string_gfs_mos7 = "<td width=83 align=center></td>";
                        $string_gfs_mos8 = "<td width=83 align=center></td>";
                    }
                }
                if ($gfsm_mos_check == 1) {
                    if (in_array($i, $gfsm_mos_time)) {
                        $index = array_search($i, $gfsm_mos_time);
                        $string_gfsm_mos1 = "<td width=83 align=center><font color=000000>" . $gfsm_init . "z GFS MOS</font></td>";
                        $string_gfsm_mos2 = "<td width=83 align=center><font color=000000>" . $gfsm_mos_date[$index] . "</font></td>";
                        $string_gfsm_mos3 = "<td width=83 align=center><font color=0000FF>-</font></td>";
                        $string_gfsm_mos4 = "<td width=83 align=center><font color=000099>-</font></td>";
                        $string_gfsm_mos5 = "<td width=83 align=center><font color=CC0000>" . $gfsm_mos_temp[$index] . "</font></td>";
                        $string_gfsm_mos6 = "<td width=83 align=center><font color=006600>" . $gfsm_mos_dew[$index] . "</font></td>";
                        $string_gfsm_mos7 = "<td width=83 align=center><font color=000000>" . $gfsm_mos_wspd[$index] . "</font></td>";
                        $string_gfsm_mos8 = "<td width=83 align=center><font color=000000>" . $gfsm_mos_wind_dir[$index] . "</font></td>";
                    } elseif (!empty($gfsm_mos_time) && $i < min($gfsm_mos_time) || !empty($gfsm_mos_time) && $i > max($gfsm_mos_time)) {
                        $string_gfsm_mos1 = "<td width=83 align=center><font color=000000>" . $gfsm_init . "z GFS MOS</font></td>";
                        $string_gfsm_mos2 = "<td width=83 align=center></td>";
                        $string_gfsm_mos3 = "<td width=83 align=center></td>";
                        $string_gfsm_mos4 = "<td width=83 align=center></td>";
                        $string_gfsm_mos5 = "<td width=83 align=center></td>";
                        $string_gfsm_mos6 = "<td width=83 align=center></td>";
                        $string_gfsm_mos7 = "<td width=83 align=center></td>";
                        $string_gfsm_mos8 = "<td width=83 align=center></td>";
                    }
                }
                if ($con_check == 1) {
                    if (in_array($i, $consensus_t)) {
                        $index = array_search($i, $consensus_t);
                        $string_con1 = "<td width=90 align=center><font color=000000><b>Model Average</b></font></td>";
                        $string_con2 = "<td width=90 align=center><font color=000000><b>" . $con_date[$index] . "</b></font></td>";
                        $string_con3 = "<td width=90 align=center><font color=0000FF><b>" . $con_p[$index] . " in.</b></font></td>";
                        $string_con4 = "<td width=90 align=center><font color=000099><b>" . $con_pa[$index] . " in.</b></font></td>";
                        $string_con5 = "<td width=90 align=center><font color=CC0000><b>" . $con_temp[$index] . " F</b></font></td>";
                        $string_con6 = "<td width=90 align=center><font color=006600><b>" . $con_dew[$index] . " F</b></font></td>";
                        $string_con7 = "<td width=90 align=center><font color=000000><b>" . $con_ws[$index] . " mph</b></font></td>";
                        $string_con8 = "<td width=90 align=center><font color=000000><b>" . $con_wd[$index] . "</b></font></td>";
                    } elseif (!empty($consensus_t) && $i < min($consensus_t) || !empty($consensus_t) && $i > max($consensus_t)) {
                        $string_con1 = "<td width=90 align=center><font color=000000><b>Model Average</b></font></td>";
                        $string_con2 = "<td width=90 align=center></td>";
                        $string_con3 = "<td width=90 align=center></td>";
                        $string_con4 = "<td width=90 align=center></td>";
                        $string_con5 = "<td width=90 align=center></td>";
                        $string_con6 = "<td width=90 align=center></td>";
                        $string_con7 = "<td width=90 align=center></td>";
                        $string_con8 = "<td width=90 align=center></td>";
                    }
                }
                if ($nws_check == 1) {
                    if (in_array($i, $nws_time_1)) {
                        $index = array_search($i, $nws_time_1);
                        $string_nws1 = "<td width=83 align=center><font color=000000>NWS</font></td>";
                        $string_nws2 = "<td width=83 align=center><font color=000000>" . $nws_date[$index] . "</font></td>";
                        $string_nws3 = "<td width=83 align=center><font color=0000FF>" . $nws_precip[$index] . "</font></td>";
                        $string_nws4 = "<td width=83 align=center><font color=000099>" . $nws_sum[$index] . "</font></td>";
                        $string_nws5 = "<td width=83 align=center><font color=CC0000>" . $nws_temp[$index] . "</font></td>";
                        $string_nws6 = "<td width=83 align=center><font color=006600>" . $nws_dpt[$index] . "</font></td>";
                        $string_nws7 = "<td width=83 align=center><font color=000000>" . $nws_wind_spd[$index] . "</font></td>";
                        $string_nws8 = "<td width=83 align=center><font color=000000>" . $nws_wind_dir[$index] . "</font></td>";
                    } elseif (!empty($nws_time_1) && $i < min($nws_time_1) || !empty($nws_time_1) && $i > max($nws_time_1)) {
                        $string_nws1 = "<td width=83 align=center><font color=000000>NWS</font></td>";
                        $string_nws2 = "<td width=83 align=center></td>";
                        $string_nws3 = "<td width=83 align=center></td>";
                        $string_nws4 = "<td width=83 align=center></td>";
                        $string_nws5 = "<td width=83 align=center></td>";
                        $string_nws6 = "<td width=83 align=center></td>";
                        $string_nws7 = "<td width=83 align=center></td>";
                        $string_nws8 = "<td width=83 align=center></td>";
                    }
                }
                if ($obs_check == 1) {
                    if (in_array($i, $obs_time)) {
                        $index = array_search($i, $obs_time);
                        $string_obs1 = "<td width=83 align=center><font color=000000>OBS - " . $ob_station . "</font></td>";
                        $string_obs2 = "<td width=83 align=center><font color=000000>" . $obs_date[$index] . "</font></td>";
                        $string_obs3 = "<td width=83 align=center><font color=0000FF>" . $obs_precip[$index] . "</font></td>";
                        $string_obs4 = "<td width=83 align=center><font color=000099>" . $obs_precip_accum[$index] . "</font></td>";
                        $string_obs5 = "<td width=83 align=center><font color=CC0000>" . $obs_temp[$index] . "</font></td>";
                        $string_obs6 = "<td width=83 align=center><font color=006600>" . $obs_dew[$index] . "</font></td>";
                        $string_obs7 = "<td width=83 align=center><font color=000000>" . $obs_wspd[$index] . "</font></td>";
                        $string_obs8 = "<td width=83 align=center><font color=000000>" . $obs_wdir[$index] . "</font></td>";
                    } elseif (!empty($obs_time) && $i < min($obs_time) || !empty($obs_time) && $i > max($obs_time)) {
                        $string_obs1 = "<td width=83 align=center><font color=000000>OBS - " . $ob_station . "</font></td>";
                        $string_obs2 = "<td width=83 align=center></td>";
                        $string_obs3 = "<td width=83 align=center></td>";
                        $string_obs4 = "<td width=83 align=center></td>";
                        $string_obs5 = "<td width=83 align=center></td>";
                        $string_obs6 = "<td width=83 align=center></td>";
                        $string_obs7 = "<td width=83 align=center></td>";
                        $string_obs8 = "<td width=83 align=center></td>";
                    }
                }

                $string_begin = "<area shape=rect coords=" . $ul . "," . $ur . "," . $lr . "," . $ll . " onMouseOver=\"writeText('";
                $string_end = "'); setMouse(this); \" />\n";

                $str_new1 = "<tr><td width=62><u>Model:</u></td>" . $string_nam1 . "" . $string_namm1 . "" . $string_nam4km1 . "" . $string_gfs1 . "" . $string_gfsm1 . "" . $string_rap1 . "" . $string_nam_mos1 . "" . $string_gfs_mos1 . "" . $string_gfsm_mos1 . "" . $string_con1 . "" . $string_nws1 . "" . $string_obs1 . "</tr>";
                $str_new2 = "<tr><td><u>Day/Time:</u></td>" . $string_nam2 . "" . $string_namm2 . "" . $string_nam4km2 . "" . $string_gfs2 . "" . $string_gfsm2 . "" . $string_rap2 . "" . $string_nam_mos2 . "" . $string_gfs_mos2 . "" . $string_gfsm_mos2 . "" . $string_con2 . "" . $string_nws2 . "" . $string_obs2 . "</tr>";
                $str_new3 = "<tr><td><u>QPF:</u></td>" . $string_nam3 . "" . $string_namm3 . "" . $string_nam4km3 . "" . $string_gfs3 . "" . $string_gfsm3 . "" . $string_rap3 . "" . $string_nam_mos3 . "" . $string_gfs_mos3 . "" . $string_gfsm_mos3 . "" . $string_con3 . "" . $string_nws3 . "" . $string_obs3 . "</tr>";
                $str_new4 = "<tr><td><u>Total QPF:</u></td>" . $string_nam4 . "" . $string_namm4 . "" . $string_nam4km4 . "" . $string_gfs4 . "" . $string_gfsm4 . "" . $string_rap4 . "" . $string_nam_mos4 . "" . $string_gfs_mos4 . "" . $string_gfsm_mos4 . "" . $string_con4 . "" . $string_nws4 . "" . $string_obs4 . "</tr>";
                $str_new5 = "<tr><td><u>2m Temp:</u></td>" . $string_nam5 . "" . $string_namm5 . "" . $string_nam4km5 . "" . $string_gfs5 . "" . $string_gfsm5 . "" . $string_rap5 . "" . $string_nam_mos5 . "" . $string_gfs_mos5 . "" . $string_gfsm_mos5 . "" . $string_con5 . "" . $string_nws5 . "" . $string_obs5 . "</tr>";
                $str_new6 = "<tr><td><u>2m Dewp:</u></td>" . $string_nam6 . "" . $string_namm6 . "" . $string_nam4km6 . "" . $string_gfs6 . "" . $string_gfsm6 . "" . $string_rap6 . "" . $string_nam_mos6 . "" . $string_gfs_mos6 . "" . $string_gfsm_mos6 . "" . $string_con6 . "" . $string_nws6 . "" . $string_obs6 . "</tr>";
                $str_new7 = "<tr><td><u>10m W-Spd:</u></td>" . $string_nam7 . "" . $string_namm7 . "" . $string_nam4km7 . "" . $string_gfs7 . "" . $string_gfsm7 . "" . $string_rap7 . "" . $string_nam_mos7 . "" . $string_gfs_mos7 . "" . $string_gfsm_mos7 . "" . $string_con7 . "" . $string_nws7 . "" . $string_obs7 . "</tr>";
                $str_new8 = "<tr><td><u>10m W-Dir:</u></td>" . $string_nam8 . "" . $string_namm8 . "" . $string_nam4km8 . "" . $string_gfs8 . "" . $string_gfsm8 . "" . $string_rap8 . "" . $string_nam_mos8 . "" . $string_gfs_mos8 . "" . $string_gfsm_mos8 . "" . $string_con8 . "" . $string_nws8 . "" . $string_obs8 . "</tr>";

                echo "" . $string_begin . "<table border=0 cellspacing=0 cellpadding=0>" . $str_new1 . "" . $str_new2 . "" . $str_new3 . "" . $str_new4 . "" . $str_new5 . "" . $str_new6 . "" . $str_new7 . "" . $str_new8 . "</table>" . $string_end . "";

                //$ul1 = $ul1+(899/($model_count+1));
                $ul1 = $lr + 1;
                $lr1 = $lr1 + (899 / ($model_count));

                $ul = round(($ul1), 0);
                $lr = round(($lr1), 0);
                //echo "".$i.",".$index."\n";

            }

            //echo "".$con.",".$obs."\n";

            ?>

        </form>
    </map>

    <script type="text/javascript">
        var sc_project = 5230524;
        var sc_invisible = 1;
        var sc_partition = 59;
        var sc_click_stat = 1;
        var sc_security = "5b0b2ca6";
    </script>

    <script type="text/javascript" src="http://www.statcounter.com/counter/counter.js"></script><noscript>
        <div class="statcounter"><a title="wordpress blog stats" href="http://www.statcounter.com/wordpress.com/" target="_blank"><img class="statcounter" src="http://c.statcounter.com/5230524/0/5b0b2ca6/1/" alt="wordpress blog stats"></a></div>
    </noscript>

</body>

</html>