<?php
require_once "../../config/settings.php";

putenv("TZ=UTC");

if (isset($argv)) {
    for ($i = 1; $i < count($argv); $i++) {
        $it = explode("=", $argv[$i]);
        $_GET[$it[0]] = $it[1];
    }
}

$uri = 'meteograms.phtml';

$site = isset($_GET["site"]) ? $_GET["site"] : "kdsm";
$var = isset($_GET["var"]) ? $_GET["var"] : "tf";
$nam = isset($_GET["nam"]) ? $_GET["nam"] : "1";
$namm = isset($_GET["namm"]) ? $_GET["namm"] : "1";
$gfs = isset($_GET["gfs"]) ? $_GET["gfs"] : "1";
$gfsm = isset($_GET["gfsm"]) ? $_GET["gfsm"] : "1";
$ruc = isset($_GET["ruc"]) ? $_GET["ruc"] : "1";
$nam_mos = isset($_GET["nam_mos"]) ? $_GET["nam_mos"] : "1";
$namm_mos = isset($_GET["namm_mos"]) ? $_GET["namm_mos"] : "1";
$gfs_mos = isset($_GET["gfs_mos"]) ? $_GET["gfs_mos"] : "1";
$gfsm_mos = isset($_GET["gfsm_mos"]) ? $_GET["gfsm_mos"] : "1";
$con = isset($_GET["con"]) ? $_GET["con"] : "1";
$obs = isset($_GET["obs"]) ? $_GET["obs"] : "1";
$nws = isset($_GET["nws"]) ? $_GET["nws"] : "1";
$ratio = isset($_GET["ratio"]) ? $_GET["ratio"] : "11";
$compaction = isset($_GET["compaction"]) ? $_GET["compaction"] : "1";
$cobb = isset($_GET["cobb"]) ? $_GET["cobb"] : "1";
$max_t = isset($_GET["max_t"]) ? $_GET["max_t"] : "1";
$mean_mt = isset($_GET["mean_mt"]) ? $_GET["mean_mt"] : "1";
$max_mt = isset($_GET["max_mt"]) ? $_GET["max_mt"] : "1";
$mean = isset($_GET["mean"]) ? $_GET["mean"] : "1";

// convert # symbol for some sites
$sym = "#";
$site_l = $site;
preg_match_all(".$sym.", $site, $id);
$check1 = @$id[0][0];
if ($check1 == $sym) {
    $exam = str_split($site);
    if ($exam[0] == $sym) {
        $exam[0] = "%23";
    }
    if ($exam[1] == $sym) {
        $exam[1] = "%23";
    }
    if ($exam[2] == $sym) {
        $exam[2] = "%23";
    }
    $site_l = "" . $exam[0] . "" . $exam[1] . "" . $exam[2] . "";
}

// check if site is in master list.  If not, terminate script and tell user
$found = 0;
for ($z = 0; $z <= 1; $z++) {
    if ($z == 0) {
        $master_list = "images/nam_bufrstations.txt";
    } elseif ($z == 1) {
        $master_list = "images/gfs3_bufrstations.txt";
    }
    $data = file($master_list);
    $sites = array();
    foreach ($data as $line) {
        $d = explode(" ", trim(preg_replace("/ +/", " ", $line)));
        $sites[] = strtolower($d[3]);
        if ($site == strtolower($d[3])) {
            $found = 1;
            if ($z == 0) {
                $lat = $d[1];
                $lon = $d[2];
            } elseif ($z == 1) {
                if (strpbrk($d[1], "N")) {
                    $lat = trim($d[1], "N");
                } else {
                    $lat = trim($d[1], "S") * -1;
                }
                if (strpbrk($d[2], "E")) {
                    $lon = trim($d[2], "E");
                } else {
                    $lon = trim($d[2], "W") * -1;
                }
            }
            break;
        }
    }
    if ($found == 1) {
        break;
    }
}

if (!(in_array($site, $sites))) {
    die("Site " . $site . " is not available.  Try again.");
}

?>

<html>

<head>

    <script type="text/javascript">
        function writeText(txt) {
            document.getElementById("desc").innerHTML = txt;
        }
    </script>

    <script type="text/javascript" src="images/neat.js">
    </script>

    <meta name="keywords" content="bufkit, bufkit warehouse, bufkit data,
bufkit documentation, bufkit files, bufkit download, bufkit links, install
bufkit, bufget, use bufkit, bufkit archive, meteogram, generator">

    <style rel="stylesheet" type="text/css">
        body {
            background: #FFFFFF;
        }

        th {
            background: #dddddd;
            font-size: 10pt;
            font-family: helvetica;
            text-align: center;
        }

        td {
            font-size: 8pt;
            font-family: helvetica;
        }

        h2 {
            font-size: 18pt;
            font-family: helvetica;
            text-align: center;
        }

        #menu {
            display: block;
            position: fixed;
            left: 1040px;
            top: 98px;
        }

        * html #menu {
            position: absolute;
        }

        #menus {
            display: block;
            position: absolute;
            left: 2px;
            top: 243px;
        }

        #clock {
            display: block;
            position: absolute;
            left: 10px;
            top: 20px;
        }

        #header {
            display: block;
            position: fixed;
            left: 2px;
            top: 0px;
        }

        * html #header {
            position: absolute;
        }

        #hoverText {
            display: block;
            position: fixed;
            left: 2px;
            top: 98px;
        }

        * html #hoverText {
            position: absolute;
        }

        #hoverTextTitle {
            display: block;
            position: absolute;
            left: 182px;
            top: 131px;
        }

        * html #hoverTextTitle {
            position: absolute;
        }

        #activeRead {
            display: block;
            position: absolute;
            left: 182px;
            top: 98px;
        }

        * html #activeRead {
            position: absolute;
        }

        #activeNam {
            display: block;
            position: absolute;
            left: 2px;
            top: 98px;
        }

        * html #activeNam {
            position: absolute;
        }

        #activeNamm {
            display: block;
            position: absolute;
            left: 365px;
            top: 98px;
        }

        * html #activeNamm {
            position: absolute;
        }

        #hoverTextNamm {
            display: block;
            position: absolute;
            left: 365px;
            top: 131px;
        }

        * html #hoverTextNamm {
            position: absolute;
        }

        #sidemenus {
            display: block;
            position: fixed;
            left: 1112px;
            top: 243px;
        }

        * html #sidemenus {
            position: absolute;
        }

        .clock {
            background: #FFFFFF;
            border: solid black 3px;
            height: 33px;
            width: 170px;
        }

        .hoverText {
            background: #FFFFFF;
            border: solid black 3px;
            height: 148px;
            width: 1040px;
        }

        .hoverTextTitle {
            background: #FFFFFF;
            border: solid black 3px;
            height: 67px;
            width: 100px;
        }

        .header {
            background: #FFFFFF;
            border: solid black 3px;
            height: 100px;
            width: 1260px;
        }

        .activeRead {
            background: #FFFFFF;
            border: solid black 3px;
            height: 33px;
            width: 100px;
        }

        .activeNam {
            background: #FFFFFF;
            border: solid black 3px;
            height: 33px;
            width: 83px;
        }

        .activeNamm {
            background: #FFFFFF;
            border: solid black 3px;
            height: 33px;
            width: 83px;
        }

        .hoverTextNamm {
            background: #FFFFFF;
            border: solid black 3px;
            height: 67px;
            width: 83px;
        }

        .select {
            background: #FFFFFF;
            border: solid black 3px;
            height: 406;
            width: 170;
        }

        .smselect {
            background: #FFFFFF;
            border: solid black 3px;
        }

        .menu {
            background: #FFFFFF;
            border: solid black 3px;
            width: 222;
            height: 148;
        }

        .menus {
            background: #FFFFFF;
            border: solid black 3px;
            height: 2000;
            width: 1100;
            cursor: crosshair;
        }

        .basemap {
            position: absolute;
            left: 0px;
            top: 40px;
            border: solid black 3px;
            cursor: crosshair;
        }

        .imClass {
            position: absolute;
            left: 0px;
            top: 40px;
            visibility: hidden;
            border: solid black 3px;
            cursor: crosshair;
        }

        .imClassPrecip {
            position: absolute;
            left: 0px;
            top: 40px;
            visibility: visible;
            border: solid black 3px;
            cursor: crosshair;
        }

        .sidemenus {
            background: #FFFFFF;
            border: solid black 3px;
            height: 3226;
            width: 150;
        }
    </style>

    <title>Meteogram Generator</title>
</head>

<body>

    <div id="menus">
        <table class="menus">
            <tr>
                <td valign="top" align="center">

                    <?php
                    echo "<p>";
                    echo "<img src=\"images/nam_snow_accum.php?site=" . $site_l . "&ratio=" . $ratio . "&compaction=" . $compaction . "&cobb=" . $cobb . "&max_t=" . $max_t . "\" alt=\"snow accumulation plot\" usemap=\"#precip\" border=\"0\">";
                    echo "</p>";
                    ?>

                    <p>
                        <img src="images/nam_precip_accum.php?model=nam&site=<?php echo $site_l; ?>" alt="precip accumulation plot" usemap="#precip" border="0">
                    </p>
                    <p>
                        <img src="images/nam_temp.php?model=nam&site=<?php echo $site_l; ?>" alt="temperature plot" usemap="#precip" border="0">
                    </p>
                    <p>
                        <img src="images/hi_wc.php?site=<?php echo $site_l; ?>" alt="heat index plot" usemap="#precip" border="0">
                    </p>
                    <p>
                        <img src="images/nam_dewpoint.php?model=nam&site=<?php echo $site_l; ?>" alt="dewpoint plot" usemap="#precip" border="0">
                    </p>

                    <?php
                    echo "<p>";
                    echo "<img src=\"images/wind_speed.php?site=" . $site_l . "&mean=" . $mean . "&mean_mt=" . $mean_mt . "&max_mt=" . $max_mt . "\" alt=\"wind speed plot\" usemap=\"#precip\" border=\"0\">";
                    echo "</p>";
                    ?>

                    <p>
                        <img src="images/nam_wind_dir.php?model=nam&site=<?php echo $site_l; ?>" alt="wind direction plot" usemap="#precip" border="0">
                    </p>

                </td>
            </tr>
        </table>
    </div>

    <div id="sidemenus">
        <table class="sidemenus">
            <form action="image_loader.phtml?site=<?php echo $site_l; ?>" method="get">
                <tr>
                    <td valign="top" align="left">
                        <p>
                            <center>
                                <b><u>Configuration Options:</b></u>
                        </p>
                        <p>
                            <u>Site:</u>
                            <input type="text" size="5" name="site" value="<?php echo $site; ?>" maxlength=5 />
                        </p>
                        <p>
                            <input type="submit" value="Re-Generate!" />
                        </p>
                        <hr color=#000000>
                        <p>
                            <b><u>Snowfall Plot:</b></u>
                        </p>
                        <p>
                            <u>Snow Ratio:</u>
                            <select name="ratio">
                                <option value="30" <?php if ($ratio == 30) {
                                                        echo "Selected";
                                                    } ?>>30
                                <option value="29" <?php if ($ratio == 29) {
                                                        echo "Selected";
                                                    } ?>>29
                                <option value="28" <?php if ($ratio == 28) {
                                                        echo "Selected";
                                                    } ?>>28
                                <option value="27" <?php if ($ratio == 27) {
                                                        echo "Selected";
                                                    } ?>>27
                                <option value="26" <?php if ($ratio == 26) {
                                                        echo "Selected";
                                                    } ?>>26
                                <option value="25" <?php if ($ratio == 25) {
                                                        echo "Selected";
                                                    } ?>>25
                                <option value="24" <?php if ($ratio == 24) {
                                                        echo "Selected";
                                                    } ?>>24
                                <option value="23" <?php if ($ratio == 23) {
                                                        echo "Selected";
                                                    } ?>>23
                                <option value="22" <?php if ($ratio == 22) {
                                                        echo "Selected";
                                                    } ?>>22
                                <option value="21" <?php if ($ratio == 21) {
                                                        echo "Selected";
                                                    } ?>>21
                                <option value="20" <?php if ($ratio == 20) {
                                                        echo "Selected";
                                                    } ?>>20
                                <option value="19" <?php if ($ratio == 19) {
                                                        echo "Selected";
                                                    } ?>>19
                                <option value="18" <?php if ($ratio == 18) {
                                                        echo "Selected";
                                                    } ?>>18
                                <option value="17" <?php if ($ratio == 17) {
                                                        echo "Selected";
                                                    } ?>>17
                                <option value="16" <?php if ($ratio == 16) {
                                                        echo "Selected";
                                                    } ?>>16
                                <option value="15" <?php if ($ratio == 15) {
                                                        echo "Selected";
                                                    } ?>>15
                                <option value="14" <?php if ($ratio == 14) {
                                                        echo "Selected";
                                                    } ?>>14
                                <option value="13" <?php if ($ratio == 13) {
                                                        echo "Selected";
                                                    } ?>>13
                                <option value="12" <?php if ($ratio == 12) {
                                                        echo "Selected";
                                                    } ?>>12
                                <option value="11" <?php if ($ratio == 11) {
                                                        echo "Selected";
                                                    } ?>>11
                                <option value="10" <?php if ($ratio == 10) {
                                                        echo "Selected";
                                                    } ?>>10
                                <option value="9" <?php if ($ratio == 9) {
                                                        echo "Selected";
                                                    } ?>>9
                                <option value="8" <?php if ($ratio == 8) {
                                                        echo "Selected";
                                                    } ?>>8
                                <option value="7" <?php if ($ratio == 7) {
                                                        echo "Selected";
                                                    } ?>>7
                                <option value="6" <?php if ($ratio == 6) {
                                                        echo "Selected";
                                                    } ?>>6
                                <option value="5" <?php if ($ratio == 5) {
                                                        echo "Selected";
                                                    } ?>>5
                                <option value="4" <?php if ($ratio == 4) {
                                                        echo "Selected";
                                                    } ?>>4
                                <option value="3" <?php if ($ratio == 3) {
                                                        echo "Selected";
                                                    } ?>>3
                                <option value="2" <?php if ($ratio == 2) {
                                                        echo "Selected";
                                                    } ?>>2
                                <option value="1" <?php if ($ratio == 1) {
                                                        echo "Selected";
                                                    } ?>>1
                                <option value="0" <?php if ($ratio == 0) {
                                                        echo "Selected";
                                                    } ?>>NP
                                </option>
                            </select>
                            :1</font>
                        </p>

                        <p>
                            <select name="max_t">
                                <option value="1" <?php if ($max_t == 1) {
                                                        echo "Selected";
                                                    } ?>>Plot Max-T
                                <option value="0" <?php if ($max_t == 0) {
                                                        echo "Selected";
                                                    } ?>>No Max-T
                                </option>
                            </select>
                        </p>

                        <p>
                            <select name="cobb">
                                <option value="1" <?php if ($cobb == 1) {
                                                        echo "Selected";
                                                    } ?>>Plot Cobb
                                <option value="0" <?php if ($cobb == 0) {
                                                        echo "Selected";
                                                    } ?>>No Cobb
                                </option>
                            </select>
                        </p>

                        <p>
                            <select name="compaction">
                                <option value="1" <?php if ($compaction == 1) {
                                                        echo "Selected";
                                                    } ?>>Compaction
                                <option value="0" <?php if ($compaction == 0) {
                                                        echo "Selected";
                                                    } ?>>No Compaction
                                </option>
                            </select>
                        </p>
                        <p>
                            <a href="compaction.html">What is Compaction?</a>
                        </p>
                        <p>
                            <input type="submit" value="Re-Generate!" />
                        </p>
                        <hr color=#000000>
                        <p>
                            <b><u>Wind Speed Plot:</b></u>
                        </p>

                        <p>
                            <select name="mean_mt">
                                <option value="1" <?php if ($mean_mt == 1) {
                                                        echo "Selected";
                                                    } ?>>Plot Mean MT
                                <option value="0" <?php if ($mean_mt == 0) {
                                                        echo "Selected";
                                                    } ?>>No Mean MT
                                </option>
                            </select>
                        </p>

                        <p>
                            <select name="max_mt">
                                <option value="1" <?php if ($max_mt == 1) {
                                                        echo "Selected";
                                                    } ?>>Plot Max MT
                                <option value="0" <?php if ($max_mt == 0) {
                                                        echo "Selected";
                                                    } ?>>No Max MT
                                </option>
                            </select>
                        </p>

                        <p>
                            <select name="mean">
                                <option value="1" <?php if ($mean == 1) {
                                                        echo "Selected";
                                                    } ?>>Plot Mean Wind
                                <option value="0" <?php if ($mean == 0) {
                                                        echo "Selected";
                                                    } ?>>No Mean Wind
                                </option>
                            </select>
                        </p>

                        <p>
                            <a href="momentum_transfer.html">Momentum Transfer (MT)?</a>
                        </p>
                        <p>
                            <input type="submit" value="Re-Generate!" />
                        </p>
                        <hr color=#000000>

                        <p>
                            <b><u>Other:</b></u>
                        </p>
                        <p>
                            <a href="apparent_temperature.html">Apparent Temperature?</a>
                        </p>

                        </center>
                    </td>
                </tr>
        </table>
        </form>
    </div>

    <div id="header">
        <table class="header">

            <tr>
                <td align=center>
                    <img src="images/title.png" alt="Header" usemap="#ThisMap" border="0">
                    <MAP name="ThisMap">

                        <area shape=rect coords="748,23,820,68"
                            href="http://mesonet.agron.iastate.edu" alt="IEM"
                            title="IEM" />

                        <area shape=rect coords="866,23,1125,71"
                            href="/" alt="Bufkit Warehouse"
                            title="Bufkit Warehouse" />

                </td>
            </tr>

        </table>
    </div>


    <div id="menu">
        <table class="menu">
            <tr>
                <td valign="top" align="center">
                        Browse the <a href="data/index.html">Google Map</a> for other locations (click <b>Visualize Data!</b>).
                        <br>
                        <p>
                    </p>
                    <u>Questions/Comments?</u>
                    karstens.chris@gmail.com
            </tr>
            </td>
        </table>
    </div>

    <div id="hoverText">
        <table class="hoverText" border="0">
            <tr>
                <td valign="top" align="left">
                    <table border="0" cellspacing="0" cellpadding="0">

                        <tr>
                            <td align=center>
                                <p id="desc"></p>
                            </td>
                        </tr>

                    </table>
                </td>
            </tr>
        </table>
    </div>


    <?php

    $line_count = 11237;
    $line_count2 = 11232;
    $line_count3 = 11235;
    $line_count4 = 11230;
    $line_count5 = 11230;
    $j = 0;
    $i = -1;
    $k = -1;
    $l = -1;
    $m = -1;
    $v = -1;
    $link = METFS1 . "bufkit/nam/nam_" . $site . ".buf";

    $data = file($link) or die('Could not read file!');
    foreach ($data as $line) {

        $j++;

        if ($j == $line_count5 && $j <= 11734) {
            $v++;
            $line_count5 = $line_count5 + 6;
            $found_t = explode(" ", $line);
            $s = str_split($found_t[1]);
            $year = "20" . $s[0] . "" . $s[1] . "";
            $mon = "" . $s[2] . "" . $s[3] . "";
            $day = "" . $s[4] . "" . $s[5] . "";
            $hr = "" . $s[7] . "" . $s[8] . "";
            if ($j == 11230) {
                $hr_nam_init = $hr;
            }
            if ($year >= 2008) {
                $t[$v] = strtotime("" . $year . "-" . $mon . "-" . $day . " " . $hr . ":00:00Z");
            }
        }

        if ($j == $line_count4 && $j <= 11734) {

            $m++;
            $line_count4 = $line_count4 + 6;
            $found_txt = explode(" ", $line);
            $txt = str_split($found_txt[1]);
            $mon = "" . $txt[2] . "" . $txt[3] . "";
            $day = "" . $txt[4] . "" . $txt[5] . "";
            $time = "" . $txt[7] . "" . $txt[8] . "";
            $date[$m] = "" . $mon . "/" . $day . " @ " . $time . "z";
        }
        if ($j == $line_count) {

            $i++;
            $line_count = $line_count + 6;
            $found_it = explode(" ", trim($line));

            //precip calculations

            $mm = $found_it[0];
            $in = 0.03937008;
            $mm_to_in = round(($mm * $in), 2);
            $precip[$i] = "" . $mm_to_in . " in.";
            $acum[$i] = $mm_to_in;
            $add[$i] = array_sum($acum);
            $sum[$i] = "" . $add[$i] . " in.";
        }

        if ($j == $line_count3) {

            $l++;
            $line_count3 = $line_count3 + 6;
            $found_dpt = trim($line);
            $dew_f = round(((($found_dpt) * (9 / 5)) + 32), 0);
            if ($dew_f > -200) {
                $dew[$l] = "" . $dew_f . " F";
            } else {
                $dew[$l] = "-";
            }
            $dew2[$l] = $dew_f;
        }

        if ($j == $line_count2) {

            $k++;
            $line_count2 = $line_count2 + 6;
            $found_it2 = explode(" ", trim($line));

            //snow on ground

            $snra = $found_it2[0];
            $in = 0.03937008;
            $snra_to_in = round(($snra * $in), 3);
            $snow[$k] = "" . $snra_to_in . " in.";

            //snow melt

            $ro1m = $found_it2[3];
            $ro1m_to_in = round(($ro1m * $in), 3);
            $store1[$k] = "" . $ro1m_to_in . " in.";
            $acum_ro1m[$k] = $ro1m_to_in;
            $add_ro1m[$k] = array_sum($acum_ro1m);
            $sum_ro1m[$k] = "" . $add_ro1m[$k] . " in.";

            //storm runoff

            $bfgr = $found_it2[4];
            $bfgr_to_in = round(($bfgr * $in), 3);
            $store2[$k] = "" . $bfgr_to_in . " in.";
            $acum_bfgr[$k] = $bfgr_to_in;
            $add_bfgr[$k] = array_sum($acum_bfgr);
            $sum_bfgr[$k] = "" . $add_bfgr[$k] . " in.";

            //10m wind

            $winds_10m = sqrt(($found_it2[1] * $found_it2[1]) + ($found_it2[2] * $found_it2[2]));
            $ms_to_mph = round(($winds_10m * 2.23693629), 0);
            $wind_10m[$k] = "" . $ms_to_mph . " mph";
            $wind_10m2[$k] = $ms_to_mph;
            $nam_wind_x[] = $found_it2[1];
            $nam_wind_y[] = $found_it2[2];
            $wind_dir = @rad2deg(atan($found_it2[2] / $found_it2[1]));
            if ($found_it2[1] < 0 && $found_it2[2] > 0) {
                $wind_dir = $wind_dir + 180;
            }
            if ($found_it2[1] == 0 && $found_it2[2] > 0) {
                $wind_dir = $wind_dir + 90;
            } elseif ($found_it2[1] < 0 && $found_it2[2] <= 0) {
                $wind_dir = $wind_dir + 180;
            }
            $cam_ang = (($wind_dir * (-1)) + 270);

            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $met_dir[$k] = "$dir";

            //temp calculations

            $temp_c = $found_it2[5];
            $temp_f = round(((($temp_c) * (9 / 5)) + 32), 0);
            $temp[$k] = "" . $temp_f . " F";
            $temp2[] = $temp_f;
        }
    }

    ?>

    <?php

    $line_count = 11237;
    $line_count2 = 11232;
    $line_count3 = 11235;
    $line_count4 = 11230;
    $line_count5 = 11230;
    $j = 0;
    $i = -1;
    $k = -1;
    $l = -1;
    $m = -1;
    $a = -1;
    $link = METFS1 . "bufkit/namm/namm_" . $site . ".buf";

    $data = file($link) or die('Could not read file!');
    foreach ($data as $line) {

        $j++;

        if ($j == $line_count5 && $j <= 11734) {
            $a++;
            $line_count5 = $line_count5 + 6;
            $found_t = explode(" ", $line);
            $s = str_split($found_t[1]);
            $year = "20" . $s[0] . "" . $s[1] . "";
            $mon = "" . $s[2] . "" . $s[3] . "";
            $day = "" . $s[4] . "" . $s[5] . "";
            $hr = "" . $s[7] . "" . $s[8] . "";
            if ($j == 11230) {
                $hr_namm_init = $hr;
            }
            if ($year >= 2008) {
                $t_namm[$a] = strtotime("" . $year . "-" . $mon . "-" . $day . " " . $hr . ":00:00Z");
            }
        }

        if ($j == $line_count4 && $j <= 11734) {

            $m++;
            $line_count4 = $line_count4 + 6;
            $found_txt = explode(" ", $line);
            $txt = str_split($found_txt[1]);
            $mon = "" . $txt[2] . "" . $txt[3] . "";
            $day = "" . $txt[4] . "" . $txt[5] . "";
            $time = "" . $txt[7] . "" . $txt[8] . "";
            $date_namm[$m] = "" . $mon . "/" . $day . " @ " . $time . "z";
        }
        if ($j == $line_count) {

            $i++;
            $line_count = $line_count + 6;
            $found_it = explode(" ", trim($line));

            //precip calculations

            $mm = $found_it[0];
            $in = 0.03937008;
            $mm_to_in = round(($mm * $in), 2);
            $precip_namm[$i] = "" . $mm_to_in . " in.";
            $acum_namm[$i] = $mm_to_in;
            $add_namm[$i] = array_sum($acum_namm);
            $sum_namm[$i] = "" . $add_namm[$i] . " in.";
        }

        if ($j == $line_count3) {

            $l++;
            $line_count3 = $line_count3 + 6;
            $found_dpt = trim($line);
            $dew_f = round(((($found_dpt) * (9 / 5)) + 32), 0);
            if ($dew_f > -200) {
                $dew_namm[$l] = "" . $dew_f . " F";
            } else {
                $dew_namm[$l] = "-";
            }
            $dew_namm2[$l] = $dew_f;
        }

        if ($j == $line_count2) {

            $k++;
            $line_count2 = $line_count2 + 6;
            $found_it2 = explode(" ", trim($line));

            //snow on ground

            $snra = $found_it2[0];
            $in = 0.03937008;
            $snra_to_in = round(($snra * $in), 3);
            $snow_namm[$k] = "" . $snra_to_in . " in.";

            //snow melt

            $ro1m = $found_it2[3];
            $ro1m_to_in = round(($ro1m * $in), 3);
            $store1_namm[$k] = "" . $ro1m_to_in . " in.";
            $acum_ro1m_namm[$k] = $ro1m_to_in;
            $add_ro1m_namm[$k] = array_sum($acum_ro1m_namm);
            $sum_ro1m_namm[$k] = "" . $add_ro1m_namm[$k] . " in.";

            //storm runoff

            $bfgr = $found_it2[4];
            $bfgr_to_in = round(($bfgr * $in), 3);
            $store2_namm[$k] = "" . $bfgr_to_in . " in.";
            $acum_bfgr_namm[$k] = $bfgr_to_in;
            $add_bfgr_namm[$k] = array_sum($acum_bfgr_namm);
            $sum_bfgr_namm[$k] = "" . $add_bfgr_namm[$k] . " in.";

            //10m wind

            $winds_10m = sqrt(($found_it2[1] * $found_it2[1]) + ($found_it2[2] * $found_it2[2]));
            $ms_to_mph = round(($winds_10m * 2.23693629), 0);
            $wind_10m_namm[$k] = "" . $ms_to_mph . " mph";
            $wind_10m_namm2[$k] = $ms_to_mph;
            $namm_wind_x[] = $found_it2[1];
            $namm_wind_y[] = $found_it2[2];
            $wind_dir = @rad2deg(atan($found_it2[2] / $found_it2[1]));
            if ($found_it2[1] < 0 && $found_it2[2] > 0) {
                $wind_dir = $wind_dir + 180;
            }
            if ($found_it2[1] == 0 && $found_it2[2] > 0) {
                $wind_dir = $wind_dir + 90;
            } elseif ($found_it2[1] < 0 && $found_it2[2] <= 0) {
                $wind_dir = $wind_dir + 180;
            }
            $cam_ang = (($wind_dir * (-1)) + 270);

            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $met_dir_namm[$k] = "$dir";

            //temp calculations

            $temp_c = $found_it2[5];
            $temp_f = round(((($temp_c) * (9 / 5)) + 32), 0);
            $temp_namm[$k] = "" . $temp_f . " F";
            $temp_namm2[] = $temp_f;
        }
    }

    ?>

    <?php

    $line_count = 8548;
    $line_count2 = 8550;
    $line_count3 = 8551;
    $line_count4 = 8548;
    $line_count5 = 8548;
    $line_count6 = 8549;
    $j = 0;
    $i = -1;
    $k = -1;
    $l = -1;
    $m = -1;
    $b = -1;
    $x = -1;
    $link = METFS1 . "bufkit/gfs/gfs3_" . $site . ".buf";

    $data = file($link) or die('Could not read file!');
    foreach ($data as $line) {

        $j++;

        if ($j == $line_count5 && $j <= 8791) {
            $b++;
            $line_count5 = $line_count5 + 4;
            $found_t = explode(" ", $line);
            $s = str_split($found_t[1]);
            $year = "20" . $s[0] . "" . $s[1] . "";
            $mon = "" . $s[2] . "" . $s[3] . "";
            $day = "" . $s[4] . "" . $s[5] . "";
            $hr = "" . $s[7] . "" . $s[8] . "";
            if ($j == 8548) {
                $hr_gfs_init = $hr;
            }
            if ($year >= 2008) {
                $t_gfs[$b] = strtotime("" . $year . "-" . $mon . "-" . $day . " " . $hr . ":00:00Z");
            }
        }

        if ($j == $line_count4 && $j <= 8791) {

            $m++;
            $line_count4 = $line_count4 + 4;
            $found_txt = explode(" ", $line);
            $txt = str_split($found_txt[1]);
            $mon = "" . $txt[2] . "" . $txt[3] . "";
            $day = "" . $txt[4] . "" . $txt[5] . "";
            $time = "" . $txt[7] . "" . $txt[8] . "";
            $date_gfs[$m] = "" . $mon . "/" . $day . " @ " . $time . "z";
        }
        if ($j == $line_count && $j <= 8791) {

            $i++;
            $line_count = $line_count + 4;
            $found_it = explode(" ", trim($line));

            //precip calculations

            $mm = $found_it[7];
            $in = 0.03937008;
            $mm_to_in = round(($mm * $in), 2);
            $precip_gfs[$i] = "" . $mm_to_in . " in.";
            $acum_gfs[$i] = $mm_to_in;
            $add_gfs[$i] = array_sum($acum_gfs);
            $sum_gfs[$i] = "" . $add_gfs[$i] . " in.";
        }

        if ($j == $line_count3 && $j <= 8791) {

            $x++;
            $line_count3 = $line_count3 + 4;
            $found_dpt = explode(" ", trim($line));
            $dew_f = round(((($found_dpt[2]) * (9 / 5)) + 32), 0);
            $dew_gfs[$x] = "" . $dew_f . " F";
            $dew_gfs2[$x] = $dew_f;
        }

        if ($j == $line_count6 && $j <= 8791) {

            $l++;
            $line_count6 = $line_count6 + 4;
            $found_u_wind = explode(" ", trim($line));
            $u_wind = $found_u_wind[5];
        }

        if ($j == $line_count2 && $j <= 8791) {

            $k++;
            $line_count2 = $line_count2 + 4;
            $found_it2 = explode(" ", trim($line));

            //10m wind

            $v_wind = $found_it2[0];
            $mag = pow((($u_wind * $u_wind) + ($v_wind * $v_wind)), (1 / 2)) * 2.23693629;
            $ms_to_mph = round($mag, 0);
            $wind_10m_gfs[$k] = "" . $ms_to_mph . " mph";
            $wind_10m_gfs2[$k] = $ms_to_mph;
            $gfs_wind_x[] = $u_wind;
            $gfs_wind_y[] = $v_wind;
            $wind_dir = @rad2deg(atan($v_wind / $u_wind));
            if ($u_wind < 0 && $v_wind > 0) {
                $wind_dir = $wind_dir + 180;
            }
            if ($u_wind == 0 && $v_wind > 0) {
                $wind_dir = $wind_dir + 90;
            } elseif ($u_wind < 0 && $v_wind <= 0) {
                $wind_dir = $wind_dir + 180;
            }
            $cam_ang = (($wind_dir * (-1)) + 270);

            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $met_dir_gfs[$k] = "$dir";

            //temp calculations

            $temp_c = $found_it2[1];
            $temp_f = round(((($temp_c) * (9 / 5)) + 32), 0);
            $temp_gfs[$k] = "" . $temp_f . " F";
            $temp_gfs2[] = $temp_f;
        }
    }

    ?>

    <?php

    $line_count = 8548;
    $line_count2 = 8550;
    $line_count3 = 8551;
    $line_count4 = 8548;
    $line_count5 = 8548;
    $line_count6 = 8549;
    $j = 0;
    $i = -1;
    $k = -1;
    $l = -1;
    $m = -1;
    $c = -1;
    $x = -1;
    $link = METFS1 . "bufkit/gfsm/gfs3_" . $site . ".buf";

    $data = file($link) or die('Could not read file!');
    foreach ($data as $line) {

        $j++;

        if ($j == $line_count5 && $j <= 8791) {
            $c++;
            $line_count5 = $line_count5 + 4;
            $found_t = explode(" ", $line);
            $s = str_split($found_t[1]);
            $year = "20" . $s[0] . "" . $s[1] . "";
            $mon = "" . $s[2] . "" . $s[3] . "";
            $day = "" . $s[4] . "" . $s[5] . "";
            $hr = "" . $s[7] . "" . $s[8] . "";
            if ($j == 8548) {
                $hr_gfsm_init = $hr;
            }
            if ($year >= 2008) {
                $t_gfsm[$c] = strtotime("" . $year . "-" . $mon . "-" . $day . " " . $hr . ":00:00Z");
            }
        }

        if ($j == $line_count4 && $j <= 8791) {

            $m++;
            $line_count4 = $line_count4 + 4;
            $found_txt = explode(" ", $line);
            $txt = str_split($found_txt[1]);
            $mon = "" . $txt[2] . "" . $txt[3] . "";
            $day = "" . $txt[4] . "" . $txt[5] . "";
            $time = "" . $txt[7] . "" . $txt[8] . "";
            $date_gfsm[$m] = "" . $mon . "/" . $day . " @ " . $time . "z";
        }
        if ($j == $line_count && $j <= 8791) {

            $i++;
            $line_count = $line_count + 4;
            $found_it = explode(" ", trim($line));

            //precip calculations

            $mm = $found_it[7];
            $in = 0.03937008;
            $mm_to_in = round(($mm * $in), 2);
            $precip_gfsm[$i] = "" . $mm_to_in . " in.";
            $acum_gfsm[$i] = $mm_to_in;
            $add_gfsm[$i] = array_sum($acum_gfsm);
            $sum_gfsm[$i] = "" . $add_gfsm[$i] . " in.";
        }

        if ($j == $line_count3 && $j <= 8791) {

            $x++;
            $line_count3 = $line_count3 + 4;
            $found_dpt = explode(" ", trim($line));
            $dew_f = round(((($found_dpt[2]) * (9 / 5)) + 32), 0);
            $dew_gfsm[$x] = "" . $dew_f . " F";
            $dew_gfsm2[$x] = $dew_f;
        }

        if ($j == $line_count6 && $j <= 8791) {

            $l++;
            $line_count6 = $line_count6 + 4;
            $found_u_wind = explode(" ", trim($line));
            $u_wind = $found_u_wind[5];
        }

        if ($j == $line_count2 && $j <= 8791) {

            $k++;
            $line_count2 = $line_count2 + 4;
            $found_it2 = explode(" ", trim($line));

            //10m wind

            $v_wind = $found_it2[0];
            $mag = pow((($u_wind * $u_wind) + ($v_wind * $v_wind)), (1 / 2)) * 2.23693629;
            $ms_to_mph = round($mag, 0);
            $wind_10m_gfsm[$k] = "" . $ms_to_mph . " mph";
            $wind_10m_gfsm2[$k] = $ms_to_mph;
            $gfsm_wind_x[] = $u_wind;
            $gfsm_wind_y[] = $v_wind;
            $wind_dir = @rad2deg(atan($v_wind / $u_wind));
            if ($u_wind < 0 && $v_wind > 0) {
                $wind_dir = $wind_dir + 180;
            }
            if ($u_wind == 0 && $v_wind > 0) {
                $wind_dir = $wind_dir + 90;
            } elseif ($u_wind < 0 && $v_wind <= 0) {
                $wind_dir = $wind_dir + 180;
            }
            $cam_ang = (($wind_dir * (-1)) + 270);

            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $met_dir_gfsm[$k] = "$dir";

            //temp calculations

            $temp_c = $found_it2[1];
            $temp_f = round(((($temp_c) * (9 / 5)) + 32), 0);
            $temp_gfsm[$k] = "" . $temp_f . " F";
            $temp_gfsm2[] = $temp_f;
        }
    }

    ?>

    //ruc
    <?php

    $line_count = 2145;
    $line_count2 = 2140;
    $line_count3 = 2143;
    $line_count4 = 2138;
    $line_count5 = 2138;
    $j = 0;
    $i = -1;
    $k = -1;
    $l = -1;
    $m = -1;
    $v = -1;
    $link = METFS1 . "bufkit/ruc/ruc_{$site}.buf";

    $data = file($link) or die('Could not read ruc file!');
    foreach ($data as $line) {
        $j++;

        if ($j == $line_count5 && $j <= 2251) {
            $v++;
            $line_count5 = $line_count5 + 6;
            $found_t = explode(" ", $line);
            $s = str_split($found_t[1]);
            $year = "20" . $s[0] . "" . $s[1] . "";
            $mon = "" . $s[2] . "" . $s[3] . "";
            $day = "" . $s[4] . "" . $s[5] . "";
            $hr = "" . $s[7] . "" . $s[8] . "";
            if ($j == 2138) {
                $hr_ruc_init = $hr;
            }
            if ($year >= 2008) {
                $t_ruc[$v] = strtotime("" . $year . "-" . $mon . "-" . $day . " " . $hr . ":00:00Z");
            }
        }

        if ($j == $line_count4 && $j <= 2251) {

            $m++;
            $line_count4 = $line_count4 + 6;
            $found_txt = explode(" ", $line);
            $txt = str_split($found_txt[1]);
            $mon = "" . $txt[2] . "" . $txt[3] . "";
            $day = "" . $txt[4] . "" . $txt[5] . "";
            $time = "" . $txt[7] . "" . $txt[8] . "";
            $date_ruc[$m] = "" . $mon . "/" . $day . " @ " . $time . "z";
        }
        if ($j == $line_count) {

            $i++;
            $line_count = $line_count + 6;
            $found_it = explode(" ", trim($line));

            //precip calculations

            $mm = $found_it[0];
            $in = 0.03937008;
            $mm_to_in = round(($mm * $in), 2);
            $precip_ruc[$i] = "" . $mm_to_in . " in.";
            $acum_ruc[$i] = $mm_to_in;
            $add_ruc[$i] = array_sum($acum_ruc);
            $sum_ruc[$i] = "" . $add_ruc[$i] . " in.";
        }

        if ($j == $line_count3) {

            $l++;
            $line_count3 = $line_count3 + 6;
            $found_dpt = trim($line);
            $dew_f = round(((($found_dpt) * (9 / 5)) + 32), 0);
            $dew_ruc[$l] = "" . $dew_f . " F";
            $dew_ruc2[$l] = $dew_f;
        }

        if ($j == $line_count2) {

            $k++;
            $line_count2 = $line_count2 + 6;
            $found_it2 = explode(" ", trim($line));

            //snow on ground

            $snra = $found_it2[0];
            $in = 0.03937008;
            $snra_to_in = round(($snra * $in), 3);
            $snow_ruc[$k] = "" . $snra_to_in . " in.";

            //snow melt

            $ro1m = $found_it2[3];
            $ro1m_to_in = round(($ro1m * $in), 3);
            $store1_ruc[$k] = "" . $ro1m_to_in . " in.";
            $acum_ro1m_ruc[$k] = $ro1m_to_in;
            $add_ro1m_ruc[$k] = array_sum($acum_ro1m_ruc);
            $sum_ro1m_ruc[$k] = "" . $add_ro1m_ruc[$k] . " in.";

            //storm runoff

            $bfgr = $found_it2[4];
            $bfgr_to_in = round(($bfgr * $in), 3);
            $store2_ruc[$k] = "" . $bfgr_to_in . " in.";
            $acum_bfgr_ruc[$k] = $bfgr_to_in;
            $add_bfgr_ruc[$k] = array_sum($acum_bfgr_ruc);
            $sum_bfgr_ruc[$k] = "" . $add_bfgr_ruc[$k] . " in.";

            //10m wind

            $winds_10m = sqrt(($found_it2[1] * $found_it2[1]) + ($found_it2[2] * $found_it2[2]));
            $ms_to_mph = round(($winds_10m * 2.23693629), 0);
            $wind_10m_ruc[$k] = "" . $ms_to_mph . " mph";
            $wind_10m_ruc2[$k] = $ms_to_mph;
            $ruc_wind_x[] = $found_it2[1];
            $ruc_wind_y[] = $found_it2[2];
            $wind_dir = @rad2deg(atan($found_it2[2] / $found_it2[1]));
            if ($found_it2[1] < 0 && $found_it2[2] > 0) {
                $wind_dir = $wind_dir + 180;
            }
            if ($found_it2[1] == 0 && $found_it2[2] > 0) {
                $wind_dir = $wind_dir + 90;
            } elseif ($found_it2[1] < 0 && $found_it2[2] <= 0) {
                $wind_dir = $wind_dir + 180;
            }
            $cam_ang = (($wind_dir * (-1)) + 270);

            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $met_dir_ruc[$k] = "$dir";

            //temp calculations

            $temp_c = $found_it2[5];
            $temp_f = round(((($temp_c) * (9 / 5)) + 32), 0);
            $temp_ruc[$k] = "" . $temp_f . " F";
            $temp_ruc2[] = $temp_f;
        }
    }

    ?>


    <?php

    $link2 = "images/bufkit.cty";
    $lat = 41.98;
    $lon = 87.90;

    if ($site != "kord") {
        $data = file($link2);
        foreach ($data as $line) {

            $find_site = explode(",", trim($line));
            $found_site = $find_site[2];
            $site_upper_case = strtoupper($site);
            if ($site_upper_case == $found_site) {
                $lat = $find_site[0];
                $lon = $find_site[1];
                break;
            }
        }
    }

    $min = min($t[0], $t_namm[0], $t_gfs[0], $t_gfsm[0]);
    $link3 = "http://mesonet.agron.iastate.edu/request/asos/csv.php?lat=" . $lat . "&lon=-" . $lon . "";
    $counter = 2;
    $trip = 0;
    $k = -1;
    $kf = -1;
    $ob_temp = array();
    $ob_dew = array();

    $data = file($link3);
    foreach ($data as $line) {
        $obs = explode(",", trim($line));
        $ob_time = strtotime("" . $obs[1] . "Z");
        $get_time = str_split($obs[1]);
        $minute = "" . @$get_time[14] . "" . @$get_time[15] . "";
        if ($ob_time >= $min && $minute >= 51 && $minute <= 55) {
            $k++;
            $kf++;
            $obs_time[$kf] = $ob_time;
            $obs_mon = date('m', $obs_time[$kf]);
            $obs_day = date('d', $obs_time[$kf]);
            $obs_hr = date('H', $obs_time[$kf]) + 1;
            $obs_date[$k] = "" . $obs_mon . "/" . $obs_day . " @ " . $obs_hr . "z";
            $acum_obs[$k] = $obs[6];
            $obs_sum[$k] = "" . array_sum($acum_obs) . " in.";
            $obs_precip[$k] = "" . $acum_obs[$k] . " in.";
            $obs_temp[$k] = "" . round($obs[2], 1) . " F";
            $obs_dpt[$k] = "" . round($obs[3], 1) . " F";
            $obs_wind_spd[$k] = "" . round($obs[4] * 1.15077945, 1) . " mph";
            $ob_station = $obs[0];
            $cam_ang = $obs[5];
            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $obs_wind_dir[$k] = "$dir";
        }
    }

    //start of NWS fetching

    $min = min($t[0], $t_namm[0], $t_gfs[0], $t_gfsm[0]);
    $max = max($t[$v], $t_namm[$a], $t_gfs[$b], $t_gfsm[$c]);
    $init_year = date('Y', $min);
    $init_mon = date('m', $min);
    $init_day = date('d', $min);
    $init_h = date('H', $min);
    $end_year = date('Y', $max);
    $end_mon = date('m', $max);
    $end_day = date('d', $max);
    $end_h = date('H', $max);

    $init_time =  "" . $init_year . "-" . $init_mon . "-" . $init_day . "T" . $init_h . "";
    $end_time =  "" . $end_year . "-" . $end_mon . "-" . $end_day . "T" . $end_h . "";

    $link4_1 = "http://www.weather.gov/forecasts/xml/SOAP_server/ndfdXMLclient.php?whichClient=NDFDgen&lat=" . $lat . "&lon=-" . $lon . "&listLatLon=&lat1=&lon1=&lat2=&lon2=&resolutionSub=&listLat1=&listLon1=";
    $link4_2 = "&listLat2=&listLon2=&resolutionList=&endPoint1Lat=&endPoint1Lon=&endPoint2Lat=&endPoint2Lon=&listEndPoint1Lat=&listEndPoint1Lon=&listEndPoint2Lat=&listEndPoint2Lon=&zipCodeList=";
    $link4_3 = "&listZipCodeList=&centerPointLat=&centerPointLon=&distanceLat=&distanceLon=&resolutionSquare=&listCenterPointLat=&listCenterPointLon=&listDistanceLat=&listDistanceLon=";
    $link4_4 = "&listResolutionSquare=&citiesLevel=&listCitiesLevel=&sector=&gmlListLatLon=&featureType=&requestedTime=&startTime=&endTime=&compType=&propertyName=";
    $link4_5 = "&product=time-series&begin=" . $init_time . "%3A00%3A00&end=" . $end_time . "%3A00%3A00&temp=temp&qpf=qpf&dew=dew&wspd=wspd&wdir=wdir&Submit=Submit";
    $link4 = "" . $link4_1 . "" . $link4_2 . "" . $link4_3 . "" . $link4_4 . "" . $link4_5 . "";
    //echo $link4;
    //die();

    $nws_start_time_1 = "start-valid-time";
    $nws_end_time_1 = "/time-layout";
    $nws_start_time_2 = "end-valid-time";
    $nws_end_time_2 = "/time-layout";
    $nws_wind_dir_start = "<name>Wind Direction</name>";
    $nws_wind_dir_end = "</direction>";
    $nws_wind_spd_start = "<name>Wind Speed</name>";
    $nws_wind_spd_end = "</wind-speed>";
    $nws_temp_start = "<name>Temperature</name>";
    $nws_temp_end = "</temperature>";
    $nws_dpt_start = "<name>Dew Point Temperature</name>";
    $nws_dpt_end = "</temperature>";
    $nws_precip_start = "<name>Liquid Precipitation Amount</name>";
    $nws_precip_end = "</precipitation>";

    $nws_int = 0;
    $trip1 = 1;
    $trip2 = 0;
    $precip_trip = 0;
    $temp_trip = 0;
    $dpt_trip = 0;
    $wind_spd_trip = 0;
    $wind_dir_trip = 0;
    $q = -1;
    $lf = -1;
    $m = -1;
    $p = -1;
    $tn = -1;
    $d = -1;
    $w = -1;
    $value = "value";

    $data = file($link4) or die('Could not read file!');
    foreach ($data as $line) {
        preg_match_all(".$nws_start_time_1.", $line, $id1);
        $check1 = @$id1[0][0];

        preg_match_all(".$nws_end_time_1.", $line, $id2);
        $check2 = @$id2[0][0];

        preg_match_all(".$nws_start_time_2.", $line, $id3);
        $check3 = @$id3[0][0];

        preg_match_all(".$nws_end_time_2.", $line, $id4);
        $check4 = @$id4[0][0];

        preg_match_all(".$nws_precip_start.", $line, $id5);
        $check5 = @$id5[0][0];

        preg_match_all(".$nws_precip_end.", $line, $id6);
        $check6 = @$id6[0][0];

        preg_match_all(".$nws_temp_start.", $line, $id7);
        $check7 = @$id7[0][0];

        preg_match_all(".$nws_temp_end.", $line, $id8);
        $check8 = @$id8[0][0];

        preg_match_all(".$nws_dpt_start.", $line, $id9);
        $check9 = @$id9[0][0];

        preg_match_all(".$nws_dpt_end.", $line, $id10);
        $check10 = @$id10[0][0];

        preg_match_all(".$nws_wind_spd_start.", $line, $id11);
        $check11 = @$id11[0][0];

        preg_match_all(".$nws_wind_spd_end.", $line, $id12);
        $check12 = @$id12[0][0];

        preg_match_all(".$nws_wind_dir_start.", $line, $id13);
        $check13 = @$id13[0][0];

        preg_match_all(".$nws_wind_dir_end.", $line, $id14);
        $check14 = @$id14[0][0];

        preg_match_all(".$value.", $line, $id15);
        $check15 = @$id15[0][0];

        if ($check2 == $nws_end_time_1) {
            $trip1 = 0;
        }

        //get nws precip time
        if ($check4 == $nws_end_time_2) {
            $trip2 = $trip2 + 1;
        }
        if ($check3 == $nws_start_time_2 && $trip2 == 1) {
            $q++;
            $get_t_1 = explode(">", trim($line));
            $get_t_2 = explode("-", trim($get_t_1[1]));
            $t_array = array($get_t_2[0], $get_t_2[1], $get_t_2[2]);
            $get_t = implode("-", $t_array);
            $nws_time_2[$q] = strtotime($get_t) + 21600;
        }

        //get nws precip
        if ($check5 == $nws_precip_start) {
            $precip_trip = 1;
        }

        if ($check6 == $nws_precip_end) {
            $precip_trip = 0;
        }
        if ($check15 == $value && $precip_trip == 1) {
            $p++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_precip[$p] = "" . $get_nws_t2[0] . " in.";
            $nws_precip2[$p] = $get_nws_t2[0];
            $add_nws_precip[$p] = array_sum($nws_precip2);
            $nws_sum[$p] = "" . $add_nws_precip[$p] . " in.";
            $p++;
            $nws_precip[$p] = "" . $get_nws_t2[0] . " in.";
            $nws_sum[$p] = "" . $add_nws_precip[$p - 1] . " in.";
        }


        //get nws time 1
        if ($check1 == $nws_start_time_1 && $trip1 == 1) {
            $lf++;
            $get_t_1 = explode(">", trim($line));
            $get_t_2 = explode("<", trim($get_t_1[1]));
            $get_t = $get_t_2[0];
            $nws_time_1[$lf] = strtotime($get_t);
            if ((@$nws_time_1[$lf] - @$nws_time_1[$lf - 1]) == 10800) {
                $nws_int++;
            }
            $nws_mon = date('m', $nws_time_1[$lf]);
            $nws_day = date('d', $nws_time_1[$lf]);
            $nws_hr = date('H', $nws_time_1[$lf]);
            $nws_date[$lf] = "" . $nws_mon . "/" . $nws_day . " @ " . $nws_hr . "z";
            $nws_precip[$lf] = "-";
            $nws_sum[$lf] = "-";
        }

        //get nws temp
        if ($check7 == $nws_temp_start) {
            $temp_trip = 1;
        }
        if ($check8 == $nws_temp_end) {
            $temp_trip = 0;
        }
        if ($check15 == $value && $temp_trip == 1) {
            $tn++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_temp[$tn] = "" . $get_nws_t2[0] . " F";
        }

        //get nws dewpoint  
        if ($check9 == $nws_dpt_start) {
            $dpt_trip = 1;
        }
        if ($check10 == $nws_dpt_end) {
            $dpt_trip = 0;
        }
        if ($check15 == $value && $dpt_trip == 1) {
            $d++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_dpt[$d] = "" . $get_nws_t2[0] . " F";
        }

        //get nws wind speed
        if ($check11 == $nws_wind_spd_start) {
            $wind_spd_trip = 1;
        }
        if ($check12 == $nws_wind_spd_end) {
            $wind_spd_trip = 0;
        }
        if ($check15 == $value && $wind_spd_trip == 1) {
            $w++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $nws_wind_spd[$w] = "" . $get_nws_t2[0] . " mph";
        }

        //get nws wind direction
        if ($check13 == $nws_wind_dir_start) {
            $wind_dir_trip = 1;
        }
        if ($check14 == $nws_wind_dir_end) {
            $wind_dir_trip = 0;
        }
        if ($check15 == $value && $wind_dir_trip == 1) {
            $m++;
            $get_nws_t1 = explode(">", trim($line));
            $get_nws_t2 = explode("<", $get_nws_t1[1]);
            $cam_ang = $get_nws_t2[0];
            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }
            $nws_wind_dir[$m] = $dir;
        }
    }



    //end of NWS fetching
    //start of MOS fetching

    $mos_year = date('Y', $t[0]);
    $mos_mon = date('m', $t[0]);
    $mos_day = date('d', $t[0]);
    $mos_h = date('H', $t[0]);

    $mos_time = "" . $mos_year . "-" . $mos_mon . "-" . $mos_day . "%20" . $mos_h . ":00";

    $r = -1;
    $tmp = "tmp";
    $link5 = "http://mesonet.agron.iastate.edu/mos/csv.php?station=K" . $ob_station . "&runtime=" . $mos_time . "&model=NAM";

    $data = file($link5) or die('Could not read file!');
    foreach ($data as $line) {
        $r++;
        $mos = explode(",", trim($line));
        if ($mos[5] == $tmp) {
        } else {
            $nam_mos_time[$r] = strtotime($mos[3]);
            $get_md = str_split($mos[3]);
            $nam_mos_date[$r] = "" . $get_md[5] . "" . $get_md[6] . "/" . $get_md[8] . "" . $get_md[9] . " @ " . $get_md[11] . "" . $get_md[12] . "z";
            $nam_mos_precip[$r] = "-";
            $nam_mos_sum[$r] = "-";
            //          $nam_mos_precip[$r] = $mos[12];
            //          $nam_mos_sum[$r] = array_sum($nam_mos_precip);
            $nam_mos_temp[$r] = "" . $mos[5] . " F";
            $nam_mos_dpt[$r] = "" . $mos[6] . " F";
            $nam_mos_wind_spd[$r] = "" . round($mos[9] * 1.15077945, 0) . " mph";
            $nam_mos_temp2[$r] = $mos[5];
            $nam_mos_dpt2[$r] = $mos[6];
            $nam_mos_wind_spd2[$r] = round($mos[9] * 1.15077945, 0);
            $cam_ang = $mos[8];
            $wind_dir = 270 - $cam_ang;
            $nam_mos_wind_x[] = cos(deg2rad($wind_dir)) * ($mos[9] * 0.514444444);
            $nam_mos_wind_y[] = sin(deg2rad($wind_dir)) * ($mos[9] * 0.514444444);
            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $nam_mos_wind_dir[$r] = $dir;
        }
    }

    //print_r($nam_mos_wind_x);
    //print_r($nam_mos_wind_y);
    //die();

    $mos_year = date('Y', $t_gfs[0]);
    $mos_mon = date('m', $t_gfs[0]);
    $mos_day = date('d', $t_gfs[0]);
    $mos_h = date('H', $t_gfs[0]);

    $mos_time = "" . $mos_year . "-" . $mos_mon . "-" . $mos_day . "%20" . $mos_h . ":00";

    $r = -1;
    $link5 = "http://mesonet.agron.iastate.edu/mos/csv.php?station=K" . $ob_station . "&runtime=" . $mos_time . "&model=GFS";

    $data = file($link5) or die('Could not read file!');
    foreach ($data as $line) {
        $r++;
        $mos = explode(",", trim($line));
        if ($mos[5] == $tmp) {
        } else {
            $gfs_mos_time[$r] = strtotime($mos[3]);
            $get_md = str_split($mos[3]);
            $gfs_mos_date[$r] = "" . $get_md[5] . "" . $get_md[6] . "/" . $get_md[8] . "" . $get_md[9] . " @ " . $get_md[11] . "" . $get_md[12] . "z";
            $gfs_mos_precip[$r] = "-";
            $gfs_mos_sum[$r] = "-";
            $gfs_mos_temp[$r] = "" . $mos[5] . " F";
            $gfs_mos_dpt[$r] = "" . $mos[6] . " F";
            $gfs_mos_wind_spd[$r] = "" . round($mos[9] * 1.15077945, 0) . " mph";
            $gfs_mos_temp2[$r] = $mos[5];
            $gfs_mos_dpt2[$r] = $mos[6];
            $gfs_mos_wind_spd2[$r] = round($mos[9] * 1.15077945, 0);
            $cam_ang = $mos[8];
            $wind_dir = 270 - $cam_ang;
            $gfs_mos_wind_x[] = cos(deg2rad($wind_dir)) * ($mos[9] * 0.514444444);
            $gfs_mos_wind_y[] = sin(deg2rad($wind_dir)) * ($mos[9] * 0.514444444);
            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $gfs_mos_wind_dir[$r] = $dir;
        }
    }

    $mos_year = date('Y', $t_gfsm[0]);
    $mos_mon = date('m', $t_gfsm[0]);
    $mos_day = date('d', $t_gfsm[0]);
    $mos_h = date('H', $t_gfsm[0]);

    $mos_time = "" . $mos_year . "-" . $mos_mon . "-" . $mos_day . "%20" . $mos_h . ":00";

    $r = -1;
    $link5 = "http://mesonet.agron.iastate.edu/mos/csv.php?station=K" . $ob_station . "&runtime=" . $mos_time . "&model=GFS";

    $data = file($link5) or die('Could not read file!');
    foreach ($data as $line) {
        $r++;
        $mos = explode(",", trim($line));
        if ($mos[5] == $tmp) {
        } else {
            $gfsm_mos_time[$r] = strtotime($mos[3]);
            $get_md = str_split($mos[3]);
            $gfsm_mos_date[$r] = "" . $get_md[5] . "" . $get_md[6] . "/" . $get_md[8] . "" . $get_md[9] . " @ " . $get_md[11] . "" . $get_md[12] . "z";
            $gfsm_mos_precip[$r] = "-";
            $gfsm_mos_sum[$r] = "-";
            $gfsm_mos_temp[$r] = "" . $mos[5] . " F";
            $gfsm_mos_dpt[$r] = "" . $mos[6] . " F";
            $gfsm_mos_wind_spd[$r] = "" . round($mos[9] * 1.15077945, 0) . " mph";
            $gfsm_mos_temp2[$r] = $mos[5];
            $gfsm_mos_dpt2[$r] = $mos[6];
            $gfsm_mos_wind_spd2[$r] = round($mos[9] * 1.15077945, 0);
            $cam_ang = $mos[8];
            $wind_dir = 270 - $cam_ang;
            $gfsm_mos_wind_x[] = cos(deg2rad($wind_dir)) * ($mos[9] * 0.514444444);
            $gfsm_mos_wind_y[] = sin(deg2rad($wind_dir)) * ($mos[9] * 0.514444444);
            if (0 <= $cam_ang && $cam_ang <= 11) {
                $dir = "N";
            } elseif (11 < $cam_ang && $cam_ang <= 34) {
                $dir = "NNE";
            } elseif (34 < $cam_ang && $cam_ang <= 45) {
                $dir = "NE";
            } elseif (45 < $cam_ang && $cam_ang <= 56) {
                $dir = "NE";
            } elseif (56 < $cam_ang && $cam_ang <= 79) {
                $dir = "ENE";
            } elseif (79 < $cam_ang && $cam_ang <= 101) {
                $dir = "E";
            } elseif (101 < $cam_ang && $cam_ang <= 124) {
                $dir = "ESE";
            } elseif (124 < $cam_ang && $cam_ang <= 135) {
                $dir = "SE";
            } elseif (135 < $cam_ang && $cam_ang <= 146) {
                $dir = "SE";
            } elseif (146 < $cam_ang && $cam_ang <= 169) {
                $dir = "SSE";
            } elseif (169 < $cam_ang && $cam_ang <= 191) {
                $dir = "S";
            } elseif (191 < $cam_ang && $cam_ang <= 214) {
                $dir = "SSW";
            } elseif (214 < $cam_ang && $cam_ang <= 225) {
                $dir = "SW";
            } elseif (225 < $cam_ang && $cam_ang <= 236) {
                $dir = "SW";
            } elseif (236 < $cam_ang && $cam_ang <= 259) {
                $dir = "WSW";
            } elseif (259 < $cam_ang && $cam_ang <= 281) {
                $dir = "W";
            } elseif (281 < $cam_ang && $cam_ang <= 304) {
                $dir = "WNW";
            } elseif (304 < $cam_ang && $cam_ang <= 315) {
                $dir = "NW";
            } elseif (315 < $cam_ang && $cam_ang <= 326) {
                $dir = "NW";
            } elseif (326 < $cam_ang && $cam_ang <= 349) {
                $dir = "NNW";
            } elseif (349 < $cam_ang && $cam_ang <= 360) {
                $dir = "N";
            }

            $gfsm_mos_wind_dir[$r] = $dir;
        }
    }


    ?>
    <?php
    //3-hourly model consensus
    for ($i = $min; $i <= $max; $i = $i + 10800) {
        $total_temp = 0;
        $total_dew = 0;
        $total_ws = 0;
        $total_wd = 0;
        $total_wd_x = 0;
        $total_wd_y = 0;
        $total_p = 0;
        $total_pa = 0;
        $n = 0;
        if (in_array($i, $t)) {
            $n++;
            $index = array_search($i, $t);
            $total_p = $total_p + $add[$index];
            $total_pa = $total_pa + $acum[$index];
            $total_temp = $total_temp + $temp2[$index];
            if ($dew2[$index] > -200) {
                $total_dew = $total_dew + $dew2[$index];
            }
            $total_ws = $total_ws + $wind_10m2[$index];
            $total_wd_x = $total_wd_x + $nam_wind_x[$index];
            $total_wd_y = $total_wd_y + $nam_wind_y[$index];
        }
        if (in_array($i, $t_namm)) {
            $n++;
            $index = array_search($i, $t_namm);
            $total_p = $total_p + $add_namm[$index];
            $total_pa = $total_pa + $acum_namm[$index];
            $total_temp = $total_temp + $temp_namm2[$index];
            if ($dew_namm2[$index] > -200) {
                $total_dew = $total_dew + $dew_namm2[$index];
            }
            $total_ws = $total_ws + $wind_10m_namm2[$index];
            $total_wd_x = $total_wd_x + $namm_wind_x[$index];
            $total_wd_y = $total_wd_y + $namm_wind_y[$index];
        }
        if (in_array($i, $t_gfs)) {
            $n++;
            $index = array_search($i, $t_gfs);
            $total_p = $total_p + $add_gfs[$index];
            $total_pa = $total_pa + $acum_gfs[$index];
            $total_temp = $total_temp + $temp_gfs2[$index];
            $total_dew = $total_dew + $dew_gfs2[$index];
            $total_ws = $total_ws + $wind_10m_gfs2[$index];
            $total_wd_x = $total_wd_x + $gfs_wind_x[$index];
            $total_wd_y = $total_wd_y + $gfs_wind_y[$index];
        }
        if (in_array($i, $t_gfsm)) {
            $n++;
            $index = array_search($i, $t_gfsm);
            $total_p = $total_p + $add_gfsm[$index];
            $total_pa = $total_pa + $acum_gfsm[$index];
            $total_temp = $total_temp + $temp_gfsm2[$index];
            $total_dew = $total_dew + $dew_gfsm2[$index];
            $total_ws = $total_ws + $wind_10m_gfsm2[$index];
            $total_wd_x = $total_wd_x + $gfsm_wind_x[$index];
            $total_wd_y = $total_wd_y + $gfsm_wind_y[$index];
        }
        if (in_array($i, $t_ruc)) {
            $n++;
            $index = array_search($i, $t_ruc);
            $total_p = $total_p + $add_ruc[$index];
            $total_pa = $total_pa + $acum_ruc[$index];
            $total_temp = $total_temp + $temp_ruc2[$index];
            $total_dew = $total_dew + $dew_ruc2[$index];
            $total_ws = $total_ws + $wind_10m_ruc2[$index];
            $total_wd_x = $total_wd_x + $ruc_wind_x[$index];
            $total_wd_y = $total_wd_y + $ruc_wind_y[$index];
        }
        if (in_array($i, $gfs_mos_time)) {
            $n++;
            $index = array_search($i, $gfs_mos_time);
            $total_temp = $total_temp + $gfs_mos_temp2[$index];
            $total_dew = $total_dew + $gfs_mos_dpt2[$index];
            $total_ws = $total_ws + $gfs_mos_wind_spd2[$index];
            $total_wd_x = $total_wd_x + $gfs_mos_wind_x[$index - 1];
            $total_wd_y = $total_wd_y + $gfs_mos_wind_y[$index - 1];
        }
        if (in_array($i, $gfsm_mos_time)) {
            $n++;
            $index = array_search($i, $gfsm_mos_time);
            $total_temp = $total_temp + $gfsm_mos_temp2[$index];
            $total_dew = $total_dew + $gfsm_mos_dpt2[$index];
            $total_ws = $total_ws +    $gfsm_mos_wind_spd2[$index];
            $total_wd_x = $total_wd_x + $gfsm_mos_wind_x[$index - 1];
            $total_wd_y = $total_wd_y + $gfsm_mos_wind_y[$index - 1];
        }
        if (in_array($i, $nam_mos_time)) {
            $n++;
            $index = array_search($i, $nam_mos_time);
            $total_temp = $total_temp + $nam_mos_temp2[$index];
            $total_dew = $total_dew + $nam_mos_dpt2[$index];
            $total_ws = $total_ws + $nam_mos_wind_spd2[$index];
            $total_wd_x = $total_wd_x + $nam_mos_wind_x[$index - 1];
            $total_wd_y = $total_wd_y + $nam_mos_wind_y[$index - 1];
        }

        $con_temp[] = round($total_temp / $n, 0);
        $nd = $n;
        if (in_array($i, $t)) {
            $index = array_search($i, $t);
            if ($dew2[$index] < -200) {
                $nd = $nd - 1;
            }
        }
        if (in_array($i, $t_namm)) {
            $index = array_search($i, $t_namm);
            if ($dew_namm2[$index] < -200) {
                $nd = $nd - 1;
            }
        }
        $con_dew[] = round($total_dew / $nd, 0);
        $con_ws[] = round($total_ws / $n, 0);
        $con_p[] = round($total_p / $n, 2);
        $con_pa[] = round($total_pa / $n, 2);
        $total_wind_x = $total_wd_x / $n;
        $total_wind_y = $total_wd_y / $n;
        $wind_dir = @rad2deg(atan($total_wind_y / $total_wind_x));
        if ($total_wind_x < 0 && $total_wind_y > 0) {
            $wind_dir = $wind_dir + 180;
        }
        if ($total_wind_x == 0 && $total_wind_y > 0) {
            $wind_dir = $wind_dir + 90;
        } elseif ($total_wind_x < 0 && $total_wind_y <= 0) {
            $wind_dir = $wind_dir + 180;
        }
        $cam_ang = (($wind_dir * (-1)) + 270);
        if (0 <= $cam_ang && $cam_ang <= 11) {
            $dir = "N";
        } elseif (11 < $cam_ang && $cam_ang <= 34) {
            $dir = "NNE";
        } elseif (34 < $cam_ang && $cam_ang <= 45) {
            $dir = "NE";
        } elseif (45 < $cam_ang && $cam_ang <= 56) {
            $dir = "NE";
        } elseif (56 < $cam_ang && $cam_ang <= 79) {
            $dir = "ENE";
        } elseif (79 < $cam_ang && $cam_ang <= 101) {
            $dir = "E";
        } elseif (101 < $cam_ang && $cam_ang <= 124) {
            $dir = "ESE";
        } elseif (124 < $cam_ang && $cam_ang <= 135) {
            $dir = "SE";
        } elseif (135 < $cam_ang && $cam_ang <= 146) {
            $dir = "SE";
        } elseif (146 < $cam_ang && $cam_ang <= 169) {
            $dir = "SSE";
        } elseif (169 < $cam_ang && $cam_ang <= 191) {
            $dir = "S";
        } elseif (191 < $cam_ang && $cam_ang <= 214) {
            $dir = "SSW";
        } elseif (214 < $cam_ang && $cam_ang <= 225) {
            $dir = "SW";
        } elseif (225 < $cam_ang && $cam_ang <= 236) {
            $dir = "SW";
        } elseif (236 < $cam_ang && $cam_ang <= 259) {
            $dir = "WSW";
        } elseif (259 < $cam_ang && $cam_ang <= 281) {
            $dir = "W";
        } elseif (281 < $cam_ang && $cam_ang <= 304) {
            $dir = "WNW";
        } elseif (304 < $cam_ang && $cam_ang <= 315) {
            $dir = "NW";
        } elseif (315 < $cam_ang && $cam_ang <= 326) {
            $dir = "NW";
        } elseif (326 < $cam_ang && $cam_ang <= 349) {
            $dir = "NNW";
        } elseif (349 < $cam_ang && $cam_ang <= 360) {
            $dir = "N";
        }

        $con_wd[] = $dir;


        $consensus_t[] = $i;
    }

    //print_r($consensus);
    //print_r($consensus_t);
    //die();
    ?>


    <map id="precip" name="precip">

        <?php

        $ul = 61;
        $ur = 41;
        $lr = 64;
        $ll = 359;
        $ul1 = $ul;
        $lr1 = $lr;

        $i_nam = 0;
        $i_namm = 0;
        $i_ruc = 0;
        $i_gfs = 0;
        $i_gfsm = 0;
        $i_nam_mos = 1;
        $i_gfs_mos = 1;
        $i_gfsm_mos = 1;
        $i_nws = 0;
        $i_obs = 0;

        $trip_nam = 0;
        $trip_namm = 0;
        $trip_ruc = 0;
        $trip_gfs = 0;
        $trip_gfs2 = 0;
        $trip_gfsm = 0;
        $trip_gfsm2 = 0;
        $trip_nam_mos = 0;
        $trip_nam_mos2 = 0;
        $trip_gfs_mos = 0;
        $trip_gfs_mos2 = 0;
        $trip_gfsm_mos = 0;
        $trip_gfsm_mos2 = 0;
        $trip_nws = 0;
        $trip_nws2 = 0;
        $trip_obs = 0;

        $gfs_check_time = $t_gfs[0];
        $gfsm_check_time = $t_gfsm[0];
        $nam_mos_check_time = $t[6];
        $gfs_mos_check_time = $t_gfs[2];
        $gfsm_mos_check_time = $t_gfsm[2];
        $nws_check_time = $nws_time_1[0];

        //$min = min($t[0],$t_namm[0],$t_gfs[0],$t_gfsm[0]);
        //$max = max($t[$v],$t_namm[$a],$t_gfs[$b],$t_gfsm[$c]);

        $cur_time = $min;
        $add_time = ($max - $min) / 3600;
        $model_count = $add_time;
        //echo "".$t[0].",".$min."";
        //die();
        for ($num = 0; $num <= $model_count; $num++) {

            if (is_int(($num - 1) / 3)) {
                $index = (($num - 1) / 3) + 1;
                $con_time = $min + (($num - 1) * 3600) + 10800;
                $con_date = "" . date("m", $con_time) . "/" . date("d", $con_time) . " @ " . date("H", $con_time) . "z";
                $string_con1 = "<td width=86 align=center><font color=000000><b>Model Average</b></font></td>";
                $string_con2 = "<td width=86 align=center><font color=000000><b>" . $con_date . "</b></font></td>";
                $string_con3 = "<td width=86 align=center><font color=0000FF><b>" . $con_pa[$index] . " in.</b></font></td>";
                $string_con4 = "<td width=86 align=center><font color=000099><b>" . $con_p[$index] . " in.</b></font></td>";
                $string_con5 = "<td width=86 align=center><font color=CC0000><b>" . $con_temp[$index] . " F</b></font></td>";
                if ($con_dew[$index] > -200) {
                    $string_con6 = "<td width=86 align=center><font color=006600><b>" . $con_dew[$index] . " F</b></font></td>";
                } else {
                    $string_con6 = "<td width=86 align=center><font color=006600><b>-</b></font></td>";
                }
                $string_con7 = "<td width=86 align=center><font color=000000><b>" . $con_ws[$index] . " mph</b></font></td>";
                $string_con8 = "<td width=86 align=center><font color=000000><b>" . $con_wd[$index] . "</b></font></td>";
                $string_con = "" . $string_con1 . "" . $string_con2 . "" . $string_con3 . "" . $string_con4 . "" . $string_con5 . "" . $string_con6 . "" . $string_con7 . "" . $string_con8 . "";
            } elseif ($num == 0) {
                $index = 0;
                $con_time = $min;
                $con_date = "" . date("m", $con_time) . "/" . date("d", $con_time) . " @ " . date("H", $con_time) . "z";
                $string_con1 = "<td width=86 align=center><font color=000000><b>Model Average</b></font></td>";
                $string_con2 = "<td width=86 align=center><font color=000000><b>" . $con_date . "</b></font></td>";
                $string_con3 = "<td width=86 align=center><font color=0000FF><b>" . $con_pa[$index] . " in.</b></font></td>";
                $string_con4 = "<td width=86 align=center><font color=000099><b>" . $con_p[$index] . " in.</b></font></td>";
                $string_con5 = "<td width=86 align=center><font color=CC0000><b>" . $con_temp[$index] . " F</b></font></td>";
                if ($con_dew[$index] > -200) {
                    $string_con6 = "<td width=86 align=center><font color=006600><b>" . $con_dew[$index] . " F</b></font></td>";
                } else {
                    $string_con6 = "<td width=86 align=center><font color=006600><b>-</b></font></td>";
                }
                $string_con7 = "<td width=86 align=center><font color=000000><b>" . $con_ws[$index] . " mph</b></font></td>";
                $string_con8 = "<td width=86 align=center><font color=000000><b>" . $con_wd[$index] . "</b></font></td>";
                $string_con = "" . $string_con1 . "" . $string_con2 . "" . $string_con3 . "" . $string_con4 . "" . $string_con5 . "" . $string_con6 . "" . $string_con7 . "" . $string_con8 . "";
            }

            $hr = $num + 1;

            if ($min + 3600 == $cur_time) {
                $trip_obs = 1;
            }
            if ($nws_time_1[0] == $cur_time) {
                $trip_nws = 1;
                $trip_nws2 = 1;
            }
            if ($nws_check_time == $cur_time) {
                $trip_nws = 1;
                $trip_nws2 = 1;
            }
            if ($i_nws > $lf) {
                $trip_nws2 = 0;
            }

            if ($t[0] == $cur_time) {
                $trip_nam = 1;
            }
            if ($t[6] == $cur_time) {
                $trip_nam_mos = 1;
                $trip_nam_mos2 = 1;
            }
            if ($nam_mos_check_time == $cur_time) {
                $trip_nam_mos = 1;
                $trip_nam_mos2 = 1;
            }
            if ($i_nam_mos > 21) {
                $trip_nam_mos2 = 0;
            }
            if ($t_namm[0] == $cur_time) {
                $trip_namm = 1;
            }
            if ($t_ruc[0] == $cur_time) {
                $trip_ruc = 1;
            }

            if ($t_gfs[2] == $cur_time) {
                $trip_gfs_mos = 1;
                $trip_gfs_mos2 = 1;
            }
            if ($gfs_mos_check_time == $cur_time) {
                $trip_gfs_mos = 1;
                $trip_gfs_mos2 = 1;
            }
            if ($i_gfs_mos > 21) {
                $trip_gfs_mos2 = 0;
            }

            if ($t_gfsm[2] == $cur_time) {
                $trip_gfsm_mos = 1;
                $trip_gfsm_mos2 = 1;
            }
            if ($gfsm_mos_check_time == $cur_time) {
                $trip_gfsm_mos = 1;
                $trip_gfsm_mos2 = 1;
            }
            if ($i_gfsm_mos > 21) {
                $trip_gfsm_mos2 = 0;
            }

            if ($gfs_check_time == $cur_time) {
                $trip_gfs = 1;
                $trip_gfs2 = 1;
            }
            if ($i_gfs > 60) {
                $trip_gfs2 = 0;
            }
            if ($gfsm_check_time == $cur_time) {
                $trip_gfsm = 1;
                $trip_gfsm2 = 1;
            }
            if ($i_gfsm > 60) {
                $trip_gfsm2 = 0;
            }


            //     $string_begin = "<area shape =\"rect\" coords =\"".$ul.",".$ur.",".$lr.",".$ll."\"onMouseOver=\"writeText('";
            $string_begin = "<area shape=rect coords=" . $ul . "," . $ur . "," . $lr . "," . $ll . " onMouseOver=\"writeText('";
            //     $string_end = "')\"/>\n";
            $string_end = "')\" />\n";

            if ($trip_nam == 0 || $i_nam > 84) {
                $string_nam1 = "<td width=86 align=center><font color=000000>" . $hr_nam_init . "z NAM</font></td>";
                $string_nam2 = "<td width=86></td>";
                $string_nam3 = "<td width=86></td>";
                $string_nam4 = "<td width=86></td>";
                $string_nam5 = "<td width=86></td>";
                $string_nam6 = "<td width=86></td>";
                $string_nam7 = "<td width=86></td>";
                $string_nam8 = "<td width=86></td>";
                $string_nam = "" . $string_nam1 . "" . $string_nam2 . "" . $string_nam3 . "" . $string_nam4 . "" . $string_nam5 . "" . $string_nam6 . "" . $string_nam7 . "" . $string_nam8 . "";
            }
            if ($trip_nam == 1 && $i_nam <= 84) {
                $string_nam1 = "<td width=86 align=center><font color=000000>" . $hr_nam_init . "z NAM</font></td>";
                $string_nam2 = "<td width=86 align=center><font color=000000>" . $date[$i_nam] . "</font></td>";
                $string_nam3 = "<td width=86 align=center><font color=0000FF>" . $precip[$i_nam] . "</font></td>";
                $string_nam4 = "<td width=86 align=center><font color=000099>" . $sum[$i_nam] . "</font></td>";
                $string_nam5 = "<td width=86 align=center><font color=CC0000>" . $temp[$i_nam] . "</font></td>";
                $string_nam6 = "<td width=86 align=center><font color=006600>" . $dew[$i_nam] . "</font></td>";
                $string_nam7 = "<td width=86 align=center><font color=000000>" . $wind_10m[$i_nam] . "</font></td>";
                $string_nam8 = "<td width=86 align=center><font color=000000>" . $met_dir[$i_nam] . "</font></td>";
                $string_nam = "" . $string_nam1 . "" . $string_nam2 . "" . $string_nam3 . "" . $string_nam4 . "" . $string_nam5 . "" . $string_nam6 . "" . $string_nam7 . "" . $string_nam8 . "";
                $i_nam++;
            }
            if ($trip_namm == 0 || $i_namm > 84) {
                $string_namm1 = "<td width=86 align=center><font color=000000>" . $hr_namm_init . "z NAM</font></td>";
                $string_namm2 = "<td width=86></td>";
                $string_namm3 = "<td width=86></td>";
                $string_namm4 = "<td width=86></td>";
                $string_namm5 = "<td width=86></td>";
                $string_namm6 = "<td width=86></td>";
                $string_namm7 = "<td width=86></td>";
                $string_namm8 = "<td width=86></td>";
                $string_namm = "" . $string_namm1 . "" . $string_namm2 . "" . $string_namm3 . "" . $string_namm4 . "" . $string_namm5 . "" . $string_namm6 . "" . $string_namm7 . "" . $string_namm8 . "";
            }
            if ($trip_namm == 1 && $i_namm <= 84) {
                $string_namm1 = "<td width=86 align=center><font color=000000>" . $hr_namm_init . "z NAM</font></td>";
                $string_namm2 = "<td width=86 align=center><font color=000000>" . $date_namm[$i_namm] . "</font></td>";
                $string_namm3 = "<td width=86 align=center><font color=0000FF>" . $precip_namm[$i_namm] . "</font></td>";
                $string_namm4 = "<td width=86 align=center><font color=000099>" . $sum_namm[$i_namm] . "</font></td>";
                $string_namm5 = "<td width=86 align=center><font color=CC0000>" . $temp_namm[$i_namm] . "</font></td>";
                $string_namm6 = "<td width=86 align=center><font color=006600>" . $dew_namm[$i_namm] . "</font></td>";
                $string_namm7 = "<td width=86 align=center><font color=000000>" . $wind_10m_namm[$i_namm] . "</font></td>";
                $string_namm8 = "<td width=86 align=center><font color=000000>" . $met_dir_namm[$i_namm] . "</font></td>";
                $string_namm = "" . $string_namm1 . "" . $string_namm2 . "" . $string_namm3 . "" . $string_namm4 . "" . $string_namm5 . "" . $string_namm6 . "" . $string_namm7 . "" . $string_namm8 . "";
                $i_namm++;
            }
            if ($trip_gfs == 0) {
                if ($trip_gfs2 == 0) {
                    $string_gfs1 = "<td width=86 align=center><font color=000000>" . $hr_gfs_init . "z GFS</font></td>";
                    $string_gfs2 = "<td width=86></td>";
                    $string_gfs3 = "<td width=86></td>";
                    $string_gfs4 = "<td width=86></td>";
                    $string_gfs5 = "<td width=86></td>";
                    $string_gfs6 = "<td width=86></td>";
                    $string_gfs7 = "<td width=86></td>";
                    $string_gfs8 = "<td width=86></td>";
                    $string_gfs = "" . $string_gfs1 . "" . $string_gfs2 . "" . $string_gfs3 . "" . $string_gfs4 . "" . $string_gfs5 . "" . $string_gfs6 . "" . $string_gfs7 . "" . $string_gfs8 . "";
                }
                if ($trip_gfs2 == 1 && $i_gfs <= 60) {
                    $string_gfs1 = "<td width=86 align=center><font color=000000>" . $hr_gfs_init . "z GFS</font></td>";
                    $string_gfs2 = "<td width=86 align=center><font color=000000>" . $date_gfs[$i_gfs] . "</font></td>";
                    $string_gfs3 = "<td width=86 align=center><font color=0000FF>" . $precip_gfs[$i_gfs] . "</font></td>";
                    $string_gfs4 = "<td width=86 align=center><font color=000099>" . $sum_gfs[$i_gfs] . "</font></td>";
                    $string_gfs5 = "<td width=86 align=center><font color=CC0000>" . $temp_gfs[$i_gfs] . "</font></td>";
                    $string_gfs6 = "<td width=86 align=center><font color=006600>" . $dew_gfs[$i_gfs] . "</font></td>";
                    $string_gfs7 = "<td width=86 align=center><font color=000000>" . $wind_10m_gfs[$i_gfs] . "</font></td>";
                    $string_gfs8 = "<td width=86 align=center><font color=000000>" . $met_dir_gfs[$i_gfs] . "</font></td>";
                    $string_gfs = "" . $string_gfs1 . "" . $string_gfs2 . "" . $string_gfs3 . "" . $string_gfs4 . "" . $string_gfs5 . "" . $string_gfs6 . "" . $string_gfs7 . "" . $string_gfs8 . "";
                }
            }

            if ($trip_gfs == 1 && $i_gfs <= 60) {
                $string_gfs1 = "<td width=86 align=center><font color=000000>" . $hr_gfs_init . "z GFS</font></td>";
                $string_gfs2 = "<td width=86 align=center><font color=000000>" . $date_gfs[$i_gfs] . "</font></td>";
                $string_gfs3 = "<td width=86 align=center><font color=0000FF>" . $precip_gfs[$i_gfs] . "</font></td>";
                $string_gfs4 = "<td width=86 align=center><font color=000099>" . $sum_gfs[$i_gfs] . "</font></td>";
                $string_gfs5 = "<td width=86 align=center><font color=CC0000>" . $temp_gfs[$i_gfs] . "</font></td>";
                $string_gfs6 = "<td width=86 align=center><font color=006600>" . $dew_gfs[$i_gfs] . "</font></td>";
                $string_gfs7 = "<td width=86 align=center><font color=000000>" . $wind_10m_gfs[$i_gfs] . "</font></td>";
                $string_gfs8 = "<td width=86 align=center><font color=000000>" . $met_dir_gfs[$i_gfs] . "</font></td>";
                $string_gfs = "" . $string_gfs1 . "" . $string_gfs2 . "" . $string_gfs3 . "" . $string_gfs4 . "" . $string_gfs5 . "" . $string_gfs6 . "" . $string_gfs7 . "" . $string_gfs8 . "";
                $i_gfs++;
                $gfs_check_time = $gfs_check_time + 10800;
                $trip_gfs = 0;
            }

            if ($trip_gfsm == 0) {
                if ($trip_gfsm2 == 0) {
                    $string_gfsm1 = "<td width=86 align=center><font color=000000>" . $hr_gfsm_init . "z GFS</font></td>";
                    $string_gfsm2 = "<td width=86></td>";
                    $string_gfsm3 = "<td width=86></td>";
                    $string_gfsm4 = "<td width=86></td>";
                    $string_gfsm5 = "<td width=86></td>";
                    $string_gfsm6 = "<td width=86></td>";
                    $string_gfsm7 = "<td width=86></td>";
                    $string_gfsm8 = "<td width=86></td>";
                    $string_gfsm = "" . $string_gfsm1 . "" . $string_gfsm2 . "" . $string_gfsm3 . "" . $string_gfsm4 . "" . $string_gfsm5 . "" . $string_gfsm6 . "" . $string_gfsm7 . "" . $string_gfsm8 . "";
                }
                if ($trip_gfsm2 == 1 && $i_gfsm <= 60) {
                    $string_gfsm1 = "<td width=86 align=center><font color=000000>" . $hr_gfsm_init . "z GFS</font></td>";
                    $string_gfsm2 = "<td width=86 align=center><font color=000000>" . $date_gfsm[$i_gfsm] . "</font></td>";
                    $string_gfsm3 = "<td width=86 align=center><font color=0000FF>" . $precip_gfsm[$i_gfsm] . "</font></td>";
                    $string_gfsm4 = "<td width=86 align=center><font color=000099>" . $sum_gfsm[$i_gfsm] . "</font></td>";
                    $string_gfsm5 = "<td width=86 align=center><font color=CC0000>" . $temp_gfsm[$i_gfsm] . "</font></td>";
                    $string_gfsm6 = "<td width=86 align=center><font color=006600>" . $dew_gfsm[$i_gfsm] . "</font></td>";
                    $string_gfsm7 = "<td width=86 align=center><font color=000000>" . $wind_10m_gfsm[$i_gfsm] . "</font></td>";
                    $string_gfsm8 = "<td width=86 align=center><font color=000000>" . $met_dir_gfsm[$i_gfsm] . "</font></td>";
                    $string_gfsm = "" . $string_gfsm1 . "" . $string_gfsm2 . "" . $string_gfsm3 . "" . $string_gfsm4 . "" . $string_gfsm5 . "" . $string_gfsm6 . "" . $string_gfsm7 . "" . $string_gfsm8 . "";
                }
            }

            if ($trip_gfsm == 1 && $i_gfsm <= 60) {
                $string_gfsm1 = "<td width=86 align=center><font color=000000>" . $hr_gfsm_init . "z GFS</font></td>";
                $string_gfsm2 = "<td width=86 align=center><font color=000000>" . $date_gfsm[$i_gfsm] . "</font></td>";
                $string_gfsm3 = "<td width=86 align=center><font color=0000FF>" . $precip_gfsm[$i_gfsm] . "</font></td>";
                $string_gfsm4 = "<td width=86 align=center><font color=000099>" . $sum_gfsm[$i_gfsm] . "</font></td>";
                $string_gfsm5 = "<td width=86 align=center><font color=CC0000>" . $temp_gfsm[$i_gfsm] . "</font></td>";
                $string_gfsm6 = "<td width=86 align=center><font color=006600>" . $dew_gfsm[$i_gfsm] . "</font></td>";
                $string_gfsm7 = "<td width=86 align=center><font color=000000>" . $wind_10m_gfsm[$i_gfsm] . "</font></td>";
                $string_gfsm8 = "<td width=86 align=center><font color=000000>" . $met_dir_gfsm[$i_gfsm] . "</font></td>";
                $string_gfsm = "" . $string_gfsm1 . "" . $string_gfsm2 . "" . $string_gfsm3 . "" . $string_gfsm4 . "" . $string_gfsm5 . "" . $string_gfsm6 . "" . $string_gfsm7 . "" . $string_gfsm8 . "";
                $i_gfsm++;
                $gfsm_check_time = $gfsm_check_time + 10800;
                $trip_gfsm = 0;
            }

            if ($trip_ruc == 0 || $i_ruc > 18) {
                $string_ruc1 = "<td width=86 align=center><font color=000000>" . $hr_ruc_init . "z RUC</font></td>";
                $string_ruc2 = "<td width=86></td>";
                $string_ruc3 = "<td width=86></td>";
                $string_ruc4 = "<td width=86></td>";
                $string_ruc5 = "<td width=86></td>";
                $string_ruc6 = "<td width=86></td>";
                $string_ruc7 = "<td width=86></td>";
                $string_ruc8 = "<td width=86></td>";
                $string_ruc = "" . $string_ruc1 . "" . $string_ruc2 . "" . $string_ruc3 . "" . $string_ruc4 . "" . $string_ruc5 . "" . $string_ruc6 . "" . $string_ruc7 . "" . $string_ruc8 . "";
            }
            if ($trip_ruc == 1 && $i_ruc <= 18) {
                $string_ruc1 = "<td width=86 align=center><font color=000000>" . $hr_ruc_init . "z RUC</font></td>";
                $string_ruc2 = "<td width=86 align=center><font color=000000>" . $date_ruc[$i_ruc] . "</font></td>";
                $string_ruc3 = "<td width=86 align=center><font color=0000FF>" . $precip_ruc[$i_ruc] . "</font></td>";
                $string_ruc4 = "<td width=86 align=center><font color=000099>" . $sum_ruc[$i_ruc] . "</font></td>";
                $string_ruc5 = "<td width=86 align=center><font color=CC0000>" . $temp_ruc[$i_ruc] . "</font></td>";
                $string_ruc6 = "<td width=86 align=center><font color=006600>" . $dew_ruc[$i_ruc] . "</font></td>";
                $string_ruc7 = "<td width=86 align=center><font color=000000>" . $wind_10m_ruc[$i_ruc] . "</font></td>";
                $string_ruc8 = "<td width=86 align=center><font color=000000>" . $met_dir_ruc[$i_ruc] . "</font></td>";
                $string_ruc = "" . $string_ruc1 . "" . $string_ruc2 . "" . $string_ruc3 . "" . $string_ruc4 . "" . $string_ruc5 . "" . $string_ruc6 . "" . $string_ruc7 . "" . $string_ruc8 . "";
                $i_ruc++;
            }

            if ($trip_nam_mos == 0 || $i_nam_mos > 21) {
                if ($trip_nam_mos2 == 0) {
                    $string_nam_mos1 = "<td width=86 align=center><font color=000000>" . $hr_nam_init . "z NAM MOS</font></td>";
                    $string_nam_mos2 = "<td width=86></td>";
                    $string_nam_mos3 = "<td width=86></td>";
                    $string_nam_mos4 = "<td width=86></td>";
                    $string_nam_mos5 = "<td width=86></td>";
                    $string_nam_mos6 = "<td width=86></td>";
                    $string_nam_mos7 = "<td width=86></td>";
                    $string_nam_mos8 = "<td width=86></td>";
                    $string_nam_mos = "" . $string_nam_mos1 . "" . $string_nam_mos2 . "" . $string_nam_mos3 . "" . $string_nam_mos4 . "" . $string_nam_mos5 . "" . $string_nam_mos6 . "" . $string_nam_mos7 . "" . $string_nam_mos8 . "";
                }
                if ($trip_nam_mos2 == 1 && $i_nam_mos <= 21) {
                    $string_nam_mos1 = "<td width=86 align=center><font color=000000>" . $hr_nam_init . "z NAM MOS</font></td>";
                    $string_nam_mos2 = "<td width=86 align=center><font color=000000>" . $nam_mos_date[$i_nam_mos] . "</font></td>";
                    $string_nam_mos3 = "<td width=86 align=center><font color=0000FF>" . $nam_mos_precip[$i_nam_mos] . "</font></td>";
                    $string_nam_mos4 = "<td width=86 align=center><font color=000099>" . $nam_mos_sum[$i_nam_mos] . "</font></td>";
                    $string_nam_mos5 = "<td width=86 align=center><font color=CC0000>" . $nam_mos_temp[$i_nam_mos] . "</font></td>";
                    $string_nam_mos6 = "<td width=86 align=center><font color=006600>" . $nam_mos_dpt[$i_nam_mos] . "</font></td>";
                    $string_nam_mos7 = "<td width=86 align=center><font color=000000>" . $nam_mos_wind_spd[$i_nam_mos] . "</font></td>";
                    $string_nam_mos8 = "<td width=86 align=center><font color=000000>" . $nam_mos_wind_dir[$i_nam_mos] . "</font></td>";
                    $string_nam_mos = "" . $string_nam_mos1 . "" . $string_nam_mos2 . "" . $string_nam_mos3 . "" . $string_nam_mos4 . "" . $string_nam_mos5 . "" . $string_nam_mos6 . "" . $string_nam_mos7 . "" . $string_nam_mos8 . "";
                }
            }
            if ($trip_nam_mos == 1 && $i_nam_mos <= 21) {
                $string_nam_mos1 = "<td width=86 align=center><font color=000000>" . $hr_nam_init . "z NAM MOS</font></td>";
                $string_nam_mos2 = "<td width=86 align=center><font color=000000>" . $nam_mos_date[$i_nam_mos] . "</font></td>";
                $string_nam_mos3 = "<td width=86 align=center><font color=0000FF>" . $nam_mos_precip[$i_nam_mos] . "</font></td>";
                $string_nam_mos4 = "<td width=86 align=center><font color=000099>" . $nam_mos_sum[$i_nam_mos] . "</font></td>";
                $string_nam_mos5 = "<td width=86 align=center><font color=CC0000>" . $nam_mos_temp[$i_nam_mos] . "</font></td>";
                $string_nam_mos6 = "<td width=86 align=center><font color=006600>" . $nam_mos_dpt[$i_nam_mos] . "</font></td>";
                $string_nam_mos7 = "<td width=86 align=center><font color=000000>" . $nam_mos_wind_spd[$i_nam_mos] . "</font></td>";
                $string_nam_mos8 = "<td width=86 align=center><font color=000000>" . $nam_mos_wind_dir[$i_nam_mos] . "</font></td>";
                $string_nam_mos = "" . $string_nam_mos1 . "" . $string_nam_mos2 . "" . $string_nam_mos3 . "" . $string_nam_mos4 . "" . $string_nam_mos5 . "" . $string_nam_mos6 . "" . $string_nam_mos7 . "" . $string_nam_mos8 . "";
                $i_nam_mos++;
                $nam_mos_check_time = $nam_mos_check_time + 10800;
                if ($i_nam_mos >= 20) {
                    $nam_mos_check_time = $nam_mos_check_time + 10800;
                }
                $trip_nam_mos = 0;
            }

            if ($trip_gfs_mos == 0 || $i_gfs_mos > 21) {
                if ($trip_gfs_mos2 == 0) {
                    $string_gfs_mos1 = "<td width=86 align=center><font color=000000>" . $hr_gfs_init . "z GFS MOS</font></td>";
                    $string_gfs_mos2 = "<td width=86></td>";
                    $string_gfs_mos3 = "<td width=86></td>";
                    $string_gfs_mos4 = "<td width=86></td>";
                    $string_gfs_mos5 = "<td width=86></td>";
                    $string_gfs_mos6 = "<td width=86></td>";
                    $string_gfs_mos7 = "<td width=86></td>";
                    $string_gfs_mos8 = "<td width=86></td>";
                    $string_gfs_mos = "" . $string_gfs_mos1 . "" . $string_gfs_mos2 . "" . $string_gfs_mos3 . "" . $string_gfs_mos4 . "" . $string_gfs_mos5 . "" . $string_gfs_mos6 . "" . $string_gfs_mos7 . "" . $string_gfs_mos8 . "";
                }
                if ($trip_gfs_mos2 == 1 && $i_gfs_mos <= 21) {
                    $string_gfs_mos1 = "<td width=86 align=center><font color=000000>" . $hr_gfs_init . "z GFS MOS</font></td>";
                    $string_gfs_mos2 = "<td width=86 align=center><font color=000000>" . $gfs_mos_date[$i_gfs_mos] . "</font></td>";
                    $string_gfs_mos3 = "<td width=86 align=center><font color=0000FF>" . $gfs_mos_precip[$i_gfs_mos] . "</font></td>";
                    $string_gfs_mos4 = "<td width=86 align=center><font color=000099>" . $gfs_mos_sum[$i_gfs_mos] . "</font></td>";
                    $string_gfs_mos5 = "<td width=86 align=center><font color=CC0000>" . $gfs_mos_temp[$i_gfs_mos] . "</font></td>";
                    $string_gfs_mos6 = "<td width=86 align=center><font color=006600>" . $gfs_mos_dpt[$i_gfs_mos] . "</font></td>";
                    $string_gfs_mos7 = "<td width=86 align=center><font color=000000>" . $gfs_mos_wind_spd[$i_gfs_mos] . "</font></td>";
                    $string_gfs_mos8 = "<td width=86 align=center><font color=000000>" . $gfs_mos_wind_dir[$i_gfs_mos] . "</font></td>";
                    $string_gfs_mos = "" . $string_gfs_mos1 . "" . $string_gfs_mos2 . "" . $string_gfs_mos3 . "" . $string_gfs_mos4 . "" . $string_gfs_mos5 . "" . $string_gfs_mos6 . "" . $string_gfs_mos7 . "" . $string_gfs_mos8 . "";
                }
            }
            if ($trip_gfs_mos == 1 && $i_gfs_mos <= 21) {
                $string_gfs_mos1 = "<td width=86 align=center><font color=000000>" . $hr_gfs_init . "z GFS MOS</font></td>";
                $string_gfs_mos2 = "<td width=86 align=center><font color=000000>" . $gfs_mos_date[$i_gfs_mos] . "</font></td>";
                $string_gfs_mos3 = "<td width=86 align=center><font color=0000FF>" . $gfs_mos_precip[$i_gfs_mos] . "</font></td>";
                $string_gfs_mos4 = "<td width=86 align=center><font color=000099>" . $gfs_mos_sum[$i_gfs_mos] . "</font></td>";
                $string_gfs_mos5 = "<td width=86 align=center><font color=CC0000>" . $gfs_mos_temp[$i_gfs_mos] . "</font></td>";
                $string_gfs_mos6 = "<td width=86 align=center><font color=006600>" . $gfs_mos_dpt[$i_gfs_mos] . "</font></td>";
                $string_gfs_mos7 = "<td width=86 align=center><font color=000000>" . $gfs_mos_wind_spd[$i_gfs_mos] . "</font></td>";
                $string_gfs_mos8 = "<td width=86 align=center><font color=000000>" . $gfs_mos_wind_dir[$i_gfs_mos] . "</font></td>";
                $string_gfs_mos = "" . $string_gfs_mos1 . "" . $string_gfs_mos2 . "" . $string_gfs_mos3 . "" . $string_gfs_mos4 . "" . $string_gfs_mos5 . "" . $string_gfs_mos6 . "" . $string_gfs_mos7 . "" . $string_gfs_mos8 . "";
                $i_gfs_mos++;
                $gfs_mos_check_time = $gfs_mos_check_time + 10800;
                if ($i_gfs_mos >= 20) {
                    $gfs_mos_check_time = $gfs_mos_check_time + 10800;
                }
                $trip_gfs_mos = 0;
            }

            if ($trip_gfsm_mos == 0 || $i_gfsm_mos > 21) {
                if ($trip_gfsm_mos2 == 0) {
                    $string_gfsm_mos1 = "<td width=86 align=center><font color=000000>" . $hr_gfsm_init . "z GFS MOS</font></td>";
                    $string_gfsm_mos2 = "<td width=86></td>";
                    $string_gfsm_mos3 = "<td width=86></td>";
                    $string_gfsm_mos4 = "<td width=86></td>";
                    $string_gfsm_mos5 = "<td width=86></td>";
                    $string_gfsm_mos6 = "<td width=86></td>";
                    $string_gfsm_mos7 = "<td width=86></td>";
                    $string_gfsm_mos8 = "<td width=86></td>";
                    $string_gfsm_mos = "" . $string_gfsm_mos1 . "" . $string_gfsm_mos2 . "" . $string_gfsm_mos3 . "" . $string_gfsm_mos4 . "" . $string_gfsm_mos5 . "" . $string_gfsm_mos6 . "" . $string_gfsm_mos7 . "" . $string_gfsm_mos8 . "";
                }
                if ($trip_gfsm_mos2 == 1 && $i_gfsm_mos <= 21) {
                    $string_gfsm_mos1 = "<td width=86 align=center><font color=000000>" . $hr_gfsm_init . "z GFS MOS</font></td>";
                    $string_gfsm_mos2 = "<td width=86 align=center><font color=000000>" . $gfsm_mos_date[$i_gfsm_mos] . "</font></td>";
                    $string_gfsm_mos3 = "<td width=86 align=center><font color=0000FF>" . $gfsm_mos_precip[$i_gfsm_mos] . "</font></td>";
                    $string_gfsm_mos4 = "<td width=86 align=center><font color=000099>" . $gfsm_mos_sum[$i_gfsm_mos] . "</font></td>";
                    $string_gfsm_mos5 = "<td width=86 align=center><font color=CC0000>" . $gfsm_mos_temp[$i_gfsm_mos] . "</font></td>";
                    $string_gfsm_mos6 = "<td width=86 align=center><font color=006600>" . $gfsm_mos_dpt[$i_gfsm_mos] . "</font></td>";
                    $string_gfsm_mos7 = "<td width=86 align=center><font color=000000>" . $gfsm_mos_wind_spd[$i_gfsm_mos] . "</font></td>";
                    $string_gfsm_mos8 = "<td width=86 align=center><font color=000000>" . $gfsm_mos_wind_dir[$i_gfsm_mos] . "</font></td>";
                    $string_gfsm_mos = "" . $string_gfsm_mos1 . "" . $string_gfsm_mos2 . "" . $string_gfsm_mos3 . "" . $string_gfsm_mos4 . "" . $string_gfsm_mos5 . "" . $string_gfsm_mos6 . "" . $string_gfsm_mos7 . "" . $string_gfsm_mos8 . "";
                }
            }
            if ($trip_gfsm_mos == 1 && $i_gfsm_mos <= 21) {
                $string_gfsm_mos1 = "<td width=86 align=center><font color=000000>" . $hr_gfsm_init . "z GFS MOS</font></td>";
                $string_gfsm_mos2 = "<td width=86 align=center><font color=000000>" . $gfsm_mos_date[$i_gfsm_mos] . "</font></td>";
                $string_gfsm_mos3 = "<td width=86 align=center><font color=0000FF>" . $gfsm_mos_precip[$i_gfsm_mos] . "</font></td>";
                $string_gfsm_mos4 = "<td width=86 align=center><font color=000099>" . $gfsm_mos_sum[$i_gfsm_mos] . "</font></td>";
                $string_gfsm_mos5 = "<td width=86 align=center><font color=CC0000>" . $gfsm_mos_temp[$i_gfsm_mos] . "</font></td>";
                $string_gfsm_mos6 = "<td width=86 align=center><font color=006600>" . $gfsm_mos_dpt[$i_gfsm_mos] . "</font></td>";
                $string_gfsm_mos7 = "<td width=86 align=center><font color=000000>" . $gfsm_mos_wind_spd[$i_gfsm_mos] . "</font></td>";
                $string_gfsm_mos8 = "<td width=86 align=center><font color=000000>" . $gfsm_mos_wind_dir[$i_gfsm_mos] . "</font></td>";
                $string_gfsm_mos = "" . $string_gfsm_mos1 . "" . $string_gfsm_mos2 . "" . $string_gfsm_mos3 . "" . $string_gfsm_mos4 . "" . $string_gfsm_mos5 . "" . $string_gfsm_mos6 . "" . $string_gfsm_mos7 . "" . $string_gfsm_mos8 . "";
                $i_gfsm_mos++;
                $gfsm_mos_check_time = $gfsm_mos_check_time + 10800;
                if ($i_gfsm_mos >= 20) {
                    $gfsm_mos_check_time = $gfsm_mos_check_time + 10800;
                }
                $trip_gfsm_mos = 0;
            }

            if ($trip_nws == 0 || $i_nws > $lf) {
                if ($trip_nws2 == 0) {
                    $string_nws1 = "<td width=86 align=center><font color=000000>NWS</font></td>";
                    $string_nws2 = "<td width=86></td>";
                    $string_nws3 = "<td width=86></td>";
                    $string_nws4 = "<td width=86></td>";
                    $string_nws5 = "<td width=86></td>";
                    $string_nws6 = "<td width=86></td>";
                    $string_nws7 = "<td width=86></td>";
                    $string_nws8 = "<td width=86></td>";
                    $string_nws = "" . $string_nws1 . "" . $string_nws2 . "" . $string_nws3 . "" . $string_nws4 . "" . $string_nws5 . "" . $string_nws6 . "" . $string_nws7 . "" . $string_nws8 . "";
                }
                if ($trip_nws2 == 1 && $i_nws <= $lf) {
                    $string_nws1 = "<td width=86 align=center><font color=000000>NWS</font></td>";
                    $string_nws2 = "<td width=86 align=center><font color=000000>" . $nws_date[$i_nws] . "</font></td>";
                    $string_nws3 = "<td width=86 align=center><font color=0000FF>" . $nws_precip[$i_nws] . "</font></td>";
                    $string_nws4 = "<td width=86 align=center><font color=000099>" . $nws_sum[$i_nws] . "</font></td>";
                    $string_nws5 = "<td width=86 align=center><font color=CC0000>" . $nws_temp[$i_nws] . "</font></td>";
                    $string_nws6 = "<td width=86 align=center><font color=006600>" . $nws_dpt[$i_nws] . "</font></td>";
                    $string_nws7 = "<td width=86 align=center><font color=000000>" . $nws_wind_spd[$i_nws] . "</font></td>";
                    $string_nws8 = "<td width=86 align=center><font color=000000>" . @$nws_wind_dir[$i_nws] . "</font></td>";
                    $string_nws = "" . $string_nws1 . "" . $string_nws2 . "" . $string_nws3 . "" . $string_nws4 . "" . $string_nws5 . "" . $string_nws6 . "" . $string_nws7 . "" . $string_nws8 . "";
                }
            }
            if ($trip_nws == 1 && $i_nws <= $lf) {
                $string_nws1 = "<td width=86 align=center><font color=000000>NWS</font></td>";
                $string_nws2 = "<td width=86 align=center><font color=000000>" . $nws_date[$i_nws] . "</font></td>";
                $string_nws3 = "<td width=86 align=center><font color=0000FF>" . $nws_precip[$i_nws] . "</font></td>";
                $string_nws4 = "<td width=86 align=center><font color=000099>" . $nws_sum[$i_nws] . "</font></td>";
                $string_nws5 = "<td width=86 align=center><font color=CC0000>" . $nws_temp[$i_nws] . "</font></td>";
                $string_nws6 = "<td width=86 align=center><font color=006600>" . $nws_dpt[$i_nws] . "</font></td>";
                $string_nws7 = "<td width=86 align=center><font color=000000>" . $nws_wind_spd[$i_nws] . "</font></td>";
                $string_nws8 = "<td width=86 align=center><font color=000000>" . @$nws_wind_dir[$i_nws] . "</font></td>";
                $string_nws = "" . $string_nws1 . "" . $string_nws2 . "" . $string_nws3 . "" . $string_nws4 . "" . $string_nws5 . "" . $string_nws6 . "" . $string_nws7 . "" . $string_nws8 . "";
                $i_nws++;
                $nws_check_time = $nws_check_time + 10800;
                if ($i_nws >= $nws_int) {
                    $nws_check_time = $nws_check_time + 10800;
                }
                $trip_nws = 0;
            }

            if ($trip_obs == 0 || $i_obs > $kf) {
                $string_obs1 = "<td width=86 align=center><font color=000000>OBS - K" . @$ob_station . "</font></td>";
                $string_obs2 = "<td width=86></td>";
                $string_obs3 = "<td width=86></td>";
                $string_obs4 = "<td width=86></td>";
                $string_obs5 = "<td width=86></td>";
                $string_obs6 = "<td width=86></td>";
                $string_obs7 = "<td width=86></td>";
                $string_obs8 = "<td width=86></td>";
                $string_obs = "" . $string_obs1 . "" . $string_obs2 . "" . $string_obs3 . "" . $string_obs4 . "" . $string_obs5 . "" . $string_obs6 . "" . $string_obs7 . "" . $string_obs8 . "";
            } else {
                $string_obs1 = "<td width=86 align=center><font color=000000>OBS - K" . $ob_station . "</font></td>";
                $string_obs2 = "<td width=86 align=center><font color=000000>" . $obs_date[$i_obs] . "</font></td>";
                $string_obs3 = "<td width=86 align=center><font color=0000FF>" . $obs_precip[$i_obs] . "</font></td>";
                $string_obs4 = "<td width=86 align=center><font color=000099>" . $obs_sum[$i_obs] . "</font></td>";
                $string_obs5 = "<td width=86 align=center><font color=CC0000>" . $obs_temp[$i_obs] . "</font></td>";
                $string_obs6 = "<td width=86 align=center><font color=006600>" . $obs_dpt[$i_obs] . "</font></td>";
                $string_obs7 = "<td width=86 align=center><font color=000000>" . $obs_wind_spd[$i_obs] . "</font></td>";
                $string_obs8 = "<td width=86 align=center><font color=000000>" . $obs_wind_dir[$i_obs] . "</font></td>";
                $string_obs = "" . $string_obs1 . "" . $string_obs2 . "" . $string_obs3 . "" . $string_obs4 . "" . $string_obs5 . "" . $string_obs6 . "" . $string_obs7 . "" . $string_obs8 . "";
                $i_obs++;
            }

            //     echo "".$string_begin."".$string_nam."".$string_namm."".$string_gfs."".$string_gfsm."".$string_ruc."".$string_nam_mos."".$string_gfs_mos."".$string_gfsm_mos."".$string_con."".$string_nws."".$string_obs."".$string_end."";
            $str_new1 = "<tr><td><u>Model:</u></td>" . $string_nam1 . "" . $string_namm1 . "" . $string_gfs1 . "" . $string_gfsm1 . "" . $string_ruc1 . "" . $string_nam_mos1 . "" . $string_gfs_mos1 . "" . $string_gfsm_mos1 . "" . $string_con1 . "" . $string_nws1 . "" . $string_obs1 . "</tr>";
            $str_new2 = "<tr><td><u>Day/Time:</u></td>" . $string_nam2 . "" . $string_namm2 . "" . $string_gfs2 . "" . $string_gfsm2 . "" . $string_ruc2 . "" . $string_nam_mos2 . "" . $string_gfs_mos2 . "" . $string_gfsm_mos2 . "" . $string_con2 . "" . $string_nws2 . "" . $string_obs2 . "</tr>";
            $str_new3 = "<tr><td><u>Hourly Precip:</u></td>" . $string_nam3 . "" . $string_namm3 . "" . $string_gfs3 . "" . $string_gfsm3 . "" . $string_ruc3 . "" . $string_nam_mos3 . "" . $string_gfs_mos3 . "" . $string_gfsm_mos3 . "" . $string_con3 . "" . $string_nws3 . "" . $string_obs3 . "</tr>";
            $str_new4 = "<tr><td><u>Accum. Precip:</u></td>" . $string_nam4 . "" . $string_namm4 . "" . $string_gfs4 . "" . $string_gfsm4 . "" . $string_ruc4 . "" . $string_nam_mos4 . "" . $string_gfs_mos4 . "" . $string_gfsm_mos4 . "" . $string_con4 . "" . $string_nws4 . "" . $string_obs4 . "</tr>";
            $str_new5 = "<tr><td><u>2m Temp:</u></td>" . $string_nam5 . "" . $string_namm5 . "" . $string_gfs5 . "" . $string_gfsm5 . "" . $string_ruc5 . "" . $string_nam_mos5 . "" . $string_gfs_mos5 . "" . $string_gfsm_mos5 . "" . $string_con5 . "" . $string_nws5 . "" . $string_obs5 . "</tr>";
            $str_new6 = "<tr><td><u>2m Dew Point:</u></td>" . $string_nam6 . "" . $string_namm6 . "" . $string_gfs6 . "" . $string_gfsm6 . "" . $string_ruc6 . "" . $string_nam_mos6 . "" . $string_gfs_mos6 . "" . $string_gfsm_mos6 . "" . $string_con6 . "" . $string_nws6 . "" . $string_obs6 . "</tr>";
            $str_new7 = "<tr><td><u>10m Wind Spd:</u></td>" . $string_nam7 . "" . $string_namm7 . "" . $string_gfs7 . "" . $string_gfsm7 . "" . $string_ruc7 . "" . $string_nam_mos7 . "" . $string_gfs_mos7 . "" . $string_gfsm_mos7 . "" . $string_con7 . "" . $string_nws7 . "" . $string_obs7 . "</tr>";
            $str_new8 = "<tr><td><u>10m Wind Dir:</u></td>" . $string_nam8 . "" . $string_namm8 . "" . $string_gfs8 . "" . $string_gfsm8 . "" . $string_ruc8 . "" . $string_nam_mos8 . "" . $string_gfs_mos8 . "" . $string_gfsm_mos8 . "" . $string_con8 . "" . $string_nws8 . "" . $string_obs8 . "</tr>";

            echo "" . $string_begin . "<table border=0 cellspacing=0 cellpadding=0>" . $str_new1 . "" . $str_new2 . "" . $str_new3 . "" . $str_new4 . "" . $str_new5 . "" . $str_new6 . "" . $str_new7 . "" . $str_new8 . "" . $string_end . "</table>";

            $ul1 = $ul1 + (899 / ($model_count + 1));
            $lr1 = $lr1 + (899 / ($model_count + 1));

            $ul = round(($ul1), 0);
            $lr = round(($lr1), 0);

            $cur_time = $cur_time + 3600;
        }

        ?>

    </map>
</body>

</html>
